/* Dojo Marugoto - unidad 3, ほっとする食べ物
   Marugoto A2/B1 Parte 2 - clase 1 = libro p44-49 - clase 2 = p50-53

   De donde salen los huecos:
     h3-01 a h3-03  p46, 文1     (〜ないですか / 〜ませんか)
     h3-04 a h3-06  p48, 文2     (〜から / 〜ので)
     h3-07 a h3-10  p51, 文2     (〜みたい)
     h3-11 a h3-14  p52, 文3     (〜ないです / 〜ありません, el dialogo)
     h3-15 a h3-19  p52, la tabla de negativos
     h3-20 a h3-28  los dialogos de p47-49 y los textos de p50 y p53

   El tema es de vocabulario mas que de verbos: el indice solo trae 11, y
   varios ya estan en otras unidades con otro sentido (あう, きく, ひく). El
   peso esta en los adjetivos de sabor y en los sustantivos de comida. */

CONTENIDO.unidades.push({
  n: 3,
  titulo: "ほっとする食べ物",
  es: "La comida que reconforta",
  paginas: { 1: "44-49", 2: "50-53" },
  estado: "lista",

  /* Dos formas nuevas: 〜ないです (el negativo hablado de la tabla de p52) y
     〜すぎます (p46: 大きすぎます, 少なすぎませんか). */
  formas: {
    1: ["masu", "masen", "nai", "naidesu", "ta", "te", "tai", "sugi", "tara"],
    2: ["masu", "nai", "naidesu", "te", "temo", "ta", "sugi", "pot"]
  },

  patrones: [
    { pat:"〜ないですか", tipo:"gramatica",
      oficial:"～ないですか",
      lectura:"nai desu ka",
      es:"¿no es…?, ¿no te parece…?",
      formula:"adjetivo い sin la い + くないですか (うすくないですか); sustantivo y adjetivo な + じゃないですか",
      uso:"Una opinión hecha pregunta, para no imponerla: «¿no está un poco soso?». Es la manera educada de decir que algo no te convence.",
      ejemplo:"うどんは、外国の人には、味がうすくないですか。" },

    { pat:"〜ませんか（すぎ）", tipo:"gramatica",
      oficial:"～ませんか",
      lectura:"masen ka",
      es:"¿no es demasiado…?",
      formula:"adjetivo い sin la い + すぎませんか (少なすぎませんか); raíz de ます + すぎませんか",
      uso:"Lo mismo que 〜ないですか pero con すぎる: ¿no es demasiado poco, demasiado grande? Señala un exceso con cuidado.",
      ejemplo:"ホセさんには、定食は、量が少なすぎませんか。" },

    { pat:"〜から（りゆう）", tipo:"gramatica",
      oficial:"～から",
      lectura:"kara",
      es:"porque…",
      formula:"forma simple + から、+ consecuencia",
      uso:"La razón dicha por uno mismo, sin rodeos: como en el súper hay de todo, no hay problema.",
      ejemplo:"野菜や魚は近所のスーパーに何でもあるから、問題ないです。" },

    { pat:"〜ので", tipo:"gramatica",
      oficial:"～ので",
      lectura:"node",
      es:"como…, dado que…",
      formula:"forma simple + ので. Sustantivo y adjetivo な llevan な: 日本人なので",
      uso:"La causa presentada como un hecho, más suave que から. Ojo con el な de los sustantivos: 日本人なので, no 日本人ので.",
      ejemplo:"私、日本人なので、白いご飯とみそしるが一番ほっとするんですよ。" },

    { pat:"〜みたい", tipo:"gramatica",
      oficial:"～みたい",
      lectura:"mitai",
      es:"parece…, como si fuera…",
      formula:"N2 + みたいな + N1 (ラーメンみたいな食べ物); N1 は N2 + みたいです (ジャムみたいです)",
      uso:"Comparar por el aspecto, el olor o el sabor: una comida como el ramen, algo que parece mermelada. Es hablado; en el papel sería 〜のよう.",
      ejemplo:"ラーメンみたいな食べ物は海外にもいろいろあるので、それも楽しんでいるんですが、日本のラーメンとはちがいます。" },

    { pat:"〜ないです／〜ありません", tipo:"gramatica",
      oficial:"～ないです／ありません",
      lectura:"nai desu / arimasen",
      es:"no… (las dos formas del negativo cortés)",
      formula:"verbo: forma ない + です (しないです) = 〜ません; adjetivo い: 〜くないです = 〜くありません; sustantivo y adjetivo な: 〜じゃないです = 〜じゃありません",
      uso:"El negativo cortés tiene dos caras y las dos valen: 〜ないです suena a conversación, 〜ありません a escrito o a más formal. La tabla de p52 las pone lado a lado.",
      ejemplo:"ラーメンは毎日食べてもあきないです。ベジマイトはあまくありません。" },

    { pat:"〜すぎる", tipo:"gramatica",
      lectura:"sugiru",
      es:"demasiado…",
      formula:"adjetivo い sin la い + すぎます (大きすぎます); raíz de ます + すぎます (食べすぎます)",
      uso:"Un exceso, y siempre con matiz negativo: demasiado grande, demasiado poco, comí de más. Nunca es «muy».",
      ejemplo:"このとんかつは、大きすぎます。" },

    { pat:"〜ようにしています", tipo:"gramatica",
      lectura:"yō ni shite imasu",
      es:"procuro…, hago por…",
      formula:"forma diccionario (o forma ない) + ようにしています",
      uso:"Un hábito que uno se impone: procuro comer verdura, procuro comer comida japonesa cuando salgo. No es «puedo», es «me esfuerzo».",
      ejemplo:"私は健康のために、できるだけ野菜を食べるようにしています。" },

    { pat:"〜にとって（は）", tipo:"gramatica",
      lectura:"ni totte (wa)",
      es:"para…, desde el punto de vista de…",
      formula:"persona + にとって（は）+ juicio",
      uso:"Fija desde quién se juzga: para un indio, el curry es lo que reconforta; para mí, es el sabor de Australia.",
      ejemplo:"妻はあまり食べませんが、私にとってはなつかしいオーストラリアの味なんです。" },

    { pat:"〜たくなる", tipo:"gramatica",
      lectura:"taku naru",
      es:"me entran ganas de…",
      formula:"raíz de ます + たくなります. Es 〜たい hecho verbo de cambio con なる",
      uso:"Las ganas que aparecen: una vez al día me entran ganas de arroz blanco. Distinto de 食べたい, que es el deseo ya presente.",
      ejemplo:"1日に1回は、白いご飯とみそしるが食べたくなります。" },

    { pat:"どんなに〜ても", tipo:"gramatica",
      lectura:"donna ni ~ temo",
      es:"por muy… que sea",
      formula:"どんなに + forma ても",
      uso:"Concede al máximo y aun así: por muy buena que esté la comida japonesa, lo que reconforta es el curry.",
      ejemplo:"どんなに日本料理がおいしくても、インド人にとってはスパイスのきいたカリーが一番ほっとします。" },

    { pat:"〜てもあきない", tipo:"gramatica",
      lectura:"temo akinai",
      es:"no me canso aunque…",
      formula:"forma ても + あきないです",
      uso:"Aunque lo coma todos los días, no me harto. あきる es cansarse de algo por repetición.",
      ejemplo:"ラーメンは毎日食べてもあきないです。" },

    { pat:"〜というのは", tipo:"gramatica",
      lectura:"to iu no wa",
      es:"lo que se llama…, eso de…",
      formula:"nombre + というのは、+ explicación",
      uso:"Para explicar qué es algo que el otro no conoce: «el Vegemite, para que lo entiendas, parece mermelada».",
      ejemplo:"ベジマイトというのは、見た目はジャムみたいですが、味はあまくありません。" },

    { pat:"〜とか、〜とか", tipo:"gramatica",
      lectura:"toka, toka",
      es:"cosas como…, por ejemplo…",
      formula:"sustantivo + とか、+ sustantivo + とか",
      uso:"Ejemplos sueltos de una lista que no se cierra: udon, sushi y cosas así. Más hablado que や.",
      ejemplo:"そうですね、うどんとか、おすしとか、よく食べます。" },

    { pat:"〜させてください", tipo:"gramatica",
      lectura:"sasete kudasai",
      es:"déjame…, permíteme…",
      formula:"forma causativa + てください. てつだう → てつだわせてください",
      uso:"Pedir permiso para hacer algo por el otro. Es la forma cortés de ofrecerse: «deja que te ayude».",
      ejemplo:"私にもてつだわせてください。" },

    { pat:"はじめは〜が、今は〜", tipo:"expresion",
      lectura:"hajime wa ~ ga, ima wa ~",
      es:"al principio…, pero ahora…",
      formula:"はじめは + lo de antes + が、今は + lo de ahora",
      uso:"El cambio de opinión con el tiempo: al principio me pareció soso, ahora me gusta. La respuesta típica a «¿ya te acostumbraste?».",
      ejemplo:"はじめはそう思いましたが、今はおいしいです。" },

    { pat:"口にあいます", tipo:"expresion",
      lectura:"くちにあいます · kuchi ni aimasu",
      es:"es de mi gusto (una comida)",
      formula:"comida + が + 口にあいます／あいません",
      uso:"Decir que una comida te va o no te va, sin decir que está mala. Literalmente «encaja en la boca».",
      ejemplo:"この魚料理、どうですか。口にあいますか。" },

    { pat:"いかがですか", tipo:"expresion",
      lectura:"ikaga desu ka",
      es:"¿qué tal…?",
      formula:"tema + はいかがですか。 Es el どうですか formal",
      uso:"Preguntar qué le parece algo al otro con cortesía. どうですか vale igual entre cercanos.",
      ejemplo:"日本の食べ物はいかがですか。" },

    { pat:"もうなれましたか", tipo:"expresion",
      lectura:"mō naremashita ka",
      es:"¿ya te has acostumbrado?",
      formula:"もう + なれましたか. Se responde ええ、もうなれました o まだです",
      uso:"La pregunta que se le hace a quien lleva un tiempo en el país. なれる es acostumbrarse.",
      ejemplo:"日本の食べ物にはもうなれましたか。" },

    { pat:"それで／でも", tipo:"expresion",
      lectura:"sore de / demo",
      es:"por eso / pero",
      formula:"それで、+ consecuencia · でも、+ objeción. Van al principio de la frase",
      uso:"Los dos conectores del texto de p50: それで saca la consecuencia, でも le pone un pero. El ejercicio (3) pide elegir cuál va en cada hueco.",
      ejemplo:"それで、海外には日本のカップラーメンを持っていきます。でも、朝食のトーストには、やっぱりベジマイトがないとだめです。" },

    { pat:"〜ないとだめです", tipo:"expresion",
      lectura:"nai to dame desu",
      es:"sin… no hay manera",
      formula:"forma ない + とだめです",
      uso:"Algo imprescindible: sin Vegemite en la tostada, no. Más rotundo que 〜なければなりません.",
      ejemplo:"朝食のトーストには、やっぱりオーストラリアのベジマイトがないとだめです。" }
  ],

  verbos: [
    { kana:"なれる", kanji:"なれる", g:2, es:"acostumbrarse", c:1 },
    { kana:"あきる", kanji:"あきる", g:2, es:"cansarse de, hartarse", c:2, nota:"Grupo 2, aunque termine en 〜きる" },
    { kana:"のこす", kanji:"のこす", g:1, es:"dejar (sin terminar)", c:1 },
    { kana:"もつ", kanji:"持つ", g:1, es:"tener, llevar", c:2 },
    { kana:"あじわう", kanji:"味わう", g:1, es:"saborear, degustar", c:2 },
    { kana:"ちがう", kanji:"ちがう", g:1, es:"ser distinto", c:2 },
    { kana:"よぶ", kanji:"よぶ", g:1, es:"llamar, invitar", c:2 },
    { kana:"きをつける", kanji:"気をつける", g:2, es:"tener cuidado, fijarse", c:1 },
    { kana:"ほっとする", kanji:"ほっとする", g:3, es:"sentir alivio, reconfortarse", c:1 },
    { kana:"もってくる", kanji:"持ってくる", g:3, es:"traer", c:2, nota:"Es 持って + くる: se conjuga el くる del final" },
    { kana:"がいしょくする", kanji:"外食する", g:3, es:"comer fuera", c:1 }
  ],

  vocab: [
    /* las comidas del tema (p44, p46, p50, p51) */
    { jp:"食べ物", kana:"たべもの", es:"comida, alimento", c:1, cat:"comida" },
    { jp:"料理", kana:"りょうり", es:"cocina, plato", c:1, cat:"comida" },
    { jp:"和食", kana:"わしょく", es:"comida japonesa", c:1, cat:"comida" },
    { jp:"家庭料理", kana:"かていりょうり", es:"comida casera", c:2, cat:"comida" },
    { jp:"ご飯", kana:"ごはん", es:"arroz (cocido), comida", c:1, cat:"comida" },
    { jp:"米", kana:"こめ", es:"arroz (grano)", c:1, cat:"comida" },
    { jp:"〜食", kana:"〜しょく", es:"comida (朝食, 昼食, 夕食, 外食, 定食)", c:1, cat:"comida" },
    { jp:"みそしる", kana:"みそしる", es:"sopa de miso", c:1, cat:"comida" },
    { jp:"うどん", kana:"うどん", es:"udon", c:1, cat:"comida" },
    { jp:"ラーメン", kana:"ラーメン", es:"ramen", c:1, cat:"comida" },
    { jp:"カップラーメン", kana:"カップラーメン", es:"ramen instantáneo", c:2, cat:"comida" },
    { jp:"おすし", kana:"おすし", es:"sushi", c:1, cat:"comida" },
    { jp:"とんかつ", kana:"とんかつ", es:"tonkatsu", c:1, cat:"comida" },
    { jp:"てんぷら", kana:"てんぷら", es:"tempura", c:1, cat:"comida" },
    { jp:"親子どん", kana:"おやこどん", es:"oyakodon", c:1, cat:"comida" },
    { jp:"やき魚", kana:"やきざかな", es:"pescado a la plancha", c:1, cat:"comida" },
    { jp:"肉じゃが", kana:"にくじゃが", es:"nikujaga", c:1, cat:"comida" },
    { jp:"にもの", kana:"にもの", es:"guiso, cocido", c:1, cat:"comida" },
    { jp:"なっとう", kana:"なっとう", es:"natto", c:2, cat:"comida" },
    { jp:"とうふ", kana:"とうふ", es:"tofu", c:2, cat:"comida" },
    { jp:"のり", kana:"のり", es:"alga nori", c:2, cat:"comida" },
    { jp:"カリー", kana:"カリー", es:"curry", c:2, cat:"comida" },
    { jp:"スパイス", kana:"スパイス", es:"especias", c:2, cat:"comida" },
    { jp:"ジャム", kana:"ジャム", es:"mermelada", c:2, cat:"comida" },
    { jp:"トースト", kana:"トースト", es:"tostada", c:2, cat:"comida" },
    { jp:"くだもの", kana:"くだもの", es:"fruta", c:1, cat:"comida" },
    { jp:"野菜", kana:"やさい", es:"verdura", c:1, cat:"comida" },
    { jp:"魚", kana:"さかな", es:"pescado", c:1, cat:"comida" },
    { jp:"お茶", kana:"おちゃ", es:"té", c:2, cat:"comida" },
    { jp:"ソフトドリンク", kana:"ソフトドリンク", es:"refresco", c:2, cat:"comida" },
    { jp:"お菓子", kana:"おかし", es:"dulces, golosinas", c:2, cat:"comida" },
    { jp:"ごちそう", kana:"ごちそう", es:"banquete, comida especial", c:2, cat:"comida" },
    { jp:"定食", kana:"ていしょく", es:"menú (plato combinado)", c:1, cat:"comida" },

    /* las comidas del dia y el comer (p45, p48, p49) */
    { jp:"食事", kana:"しょくじ", es:"comida (el acto de comer)", c:1, cat:"comida" },
    { jp:"食生活", kana:"しょくせいかつ", es:"hábitos de comida", c:1, cat:"abstracto" },
    { jp:"朝食", kana:"ちょうしょく", es:"desayuno", c:1, cat:"tiempo" },
    { jp:"昼食", kana:"ちゅうしょく", es:"almuerzo", c:1, cat:"tiempo" },
    { jp:"夕食", kana:"ゆうしょく", es:"cena", c:1, cat:"tiempo" },
    { jp:"外食", kana:"がいしょく", es:"comer fuera", c:1, cat:"abstracto" },
    { jp:"材料", kana:"ざいりょう", es:"ingredientes", c:1, cat:"comida" },
    { jp:"量", kana:"りょう", es:"cantidad", c:1, cat:"abstracto" },
    { jp:"味", kana:"あじ", es:"sabor", c:1, cat:"abstracto" },
    { jp:"におい", kana:"におい", es:"olor", c:2, cat:"abstracto" },
    { jp:"見た目", kana:"みため", es:"aspecto", c:2, cat:"abstracto" },
    { jp:"ねだん", kana:"ねだん", es:"precio", c:1, cat:"abstracto" },
    { jp:"健康", kana:"けんこう", es:"salud", c:1, cat:"abstracto" },
    { jp:"体", kana:"からだ", es:"cuerpo", c:1, cat:"abstracto" },
    { jp:"調子", kana:"ちょうし", es:"estado (de salud, de ánimo)", c:1, cat:"abstracto" },
    { jp:"好ききらい", kana:"すききらい", es:"manías con la comida", c:1, cat:"abstracto" },
    { jp:"半分", kana:"はんぶん", es:"la mitad", c:1, cat:"abstracto" },
    { jp:"半年", kana:"はんとし", es:"medio año", c:1, cat:"tiempo" },
    { jp:"近所", kana:"きんじょ", es:"el vecindario", c:1, cat:"lugar" },
    { jp:"デパート", kana:"デパート", es:"grandes almacenes", c:1, cat:"lugar" },
    { jp:"町", kana:"まち", es:"ciudad, pueblo", c:2, cat:"lugar" },
    { jp:"海外", kana:"かいがい", es:"el extranjero", c:2, cat:"lugar" },
    { jp:"外国", kana:"がいこく", es:"país extranjero", c:1, cat:"lugar" },
    { jp:"国", kana:"くに", es:"país", c:1, cat:"lugar" },
    { jp:"妻", kana:"つま", es:"mi esposa", c:2, cat:"persona" },
    { jp:"胃", kana:"い", es:"estómago", c:1, cat:"abstracto" },
    { jp:"いのち", kana:"いのち", es:"la vida, lo esencial", c:2, cat:"abstracto" },
    { jp:"自信", kana:"じしん", es:"confianza en uno mismo", c:2, cat:"abstracto" },

    /* los sabores y como esta la comida (p46, p50, p52) */
    { jp:"おいしい", kana:"おいしい", es:"rico, bueno", c:1, cat:"cualidad" },
    { jp:"あまい", kana:"あまい", es:"dulce", c:1, cat:"cualidad" },
    { jp:"しょっぱい", kana:"しょっぱい", es:"salado", c:2, cat:"cualidad" },
    { jp:"うすい", kana:"うすい", es:"soso, suave (de sabor)", c:1, cat:"cualidad" },
    { jp:"苦手", kana:"にがて", es:"que no se me da bien, que no me va", c:1, cat:"cualidad" },
    { jp:"きらい", kana:"きらい", es:"que no me gusta", c:2, cat:"cualidad" },
    { jp:"なつかしい", kana:"なつかしい", es:"que trae nostalgia", c:2, cat:"cualidad" },
    { jp:"ぜいたく", kana:"ぜいたく", es:"de lujo, un capricho", c:1, cat:"cualidad" },
    { jp:"ふつう", kana:"ふつう", es:"normal, corriente", c:1, cat:"cualidad" },
    { jp:"白い", kana:"しろい", es:"blanco", c:1, cat:"cualidad" },
    { jp:"悪い", kana:"わるい", es:"malo", c:1, cat:"cualidad" },

    /* adverbios y muletillas */
    { jp:"ほとんど", kana:"ほとんど", es:"casi (siempre, todo)", c:1, cat:"conector" },
    { jp:"できるだけ", kana:"できるだけ", es:"en lo posible", c:1, cat:"conector" },
    { jp:"一番", kana:"いちばん", es:"lo que más, el mejor", c:1, cat:"conector" },
    { jp:"ぜんぜん", kana:"ぜんぜん", es:"en absoluto (con negativo)", c:2, cat:"conector" },
    { jp:"どうしても", kana:"どうしても", es:"sea como sea, sin remedio", c:2, cat:"conector" },
    { jp:"やっぱり", kana:"やっぱり", es:"al final, como era de esperar", c:2, cat:"conector" },
    { jp:"いつも", kana:"いつも", es:"siempre", c:1, cat:"conector" },
    { jp:"いかが", kana:"いかが", es:"qué tal (formal)", c:1, cat:"reaccion" },
    { jp:"いただきます", kana:"いただきます", es:"(lo que se dice antes de comer)", c:2, cat:"reaccion" },
    { jp:"どうぞ", kana:"どうぞ", es:"adelante, sírvete", c:2, cat:"reaccion" },
    { jp:"さあ", kana:"さあ", es:"venga, vamos", c:2, cat:"reaccion" }
  ],

  frases: [
    { k:"f3-01", es:"El udon, para un extranjero, ¿no está un poco soso?", c:1, pat:"〜ないですか",
      ok:["うどんは、外国の人には、味がうすくないですか。","うどんは、がいこくのひとには、あじがうすくないですか。"] },
    { k:"f3-02", es:"Para José, ¿el menú no es demasiado poca cantidad?", c:1, pat:"〜ませんか（すぎ）",
      ok:["ホセさんには、定食は、量が少なすぎませんか。","ホセさんには、ていしょくは、りょうがすくなすぎませんか。"] },
    { k:"f3-03", es:"Este tonkatsu es demasiado grande.", c:1, pat:"〜すぎる",
      ok:["このとんかつは、大きすぎます。","このとんかつは、おおきすぎます。"] },
    { k:"f3-04", es:"Verdura y pescado hay de todo en el súper del barrio, así que no hay problema.", c:1, pat:"〜から（りゆう）",
      ok:["野菜や魚は近所のスーパーに何でもあるから、問題ないです。","やさいやさかなはきんじょのスーパーになんでもあるから、もんだいないです。"] },
    { k:"f3-05", es:"Como soy japonesa, lo que más me reconforta es el arroz blanco con sopa de miso.", c:1, pat:"〜ので",
      ok:["私、日本人なので、白いご飯とみそしるが一番ほっとするんですよ。","わたし、にほんじんなので、しろいごはんとみそしるがいちばんほっとするんですよ。"] },
    { k:"f3-06", es:"Voy a hacer algo rico un día de estos, así que ven a comer.", c:1, pat:"〜から（りゆう）",
      ok:["こんど何かおいしいもの作りますから、食べに来てください。","こんどなにかおいしいものつくりますから、たべにきてください。"] },
    { k:"f3-07", es:"Deja que te ayude yo también.", c:1, pat:"〜させてください",
      ok:["私にもてつだわせてください。","わたしにもてつだわせてください。"] },
    { k:"f3-08", es:"¿Qué tal la comida japonesa?", c:1, pat:"いかがですか",
      ok:["日本の食べ物はいかがですか。","にほんのたべものはいかがですか。"] },
    { k:"f3-09", es:"¿Ya te has acostumbrado a la comida japonesa?", c:1, pat:"もうなれましたか",
      ok:["日本の食べ物にはもうなれましたか。","にほんのたべものにはもうなれましたか。"] },
    { k:"f3-10", es:"Pues udon, sushi y cosas así como a menudo.", c:1, pat:"〜とか、〜とか",
      ok:["そうですね、うどんとか、おすしとか、よく食べます。","そうですね、うどんとか、おすしとか、よくたべます。"] },
    { k:"f3-11", es:"Al principio me lo pareció, pero ahora me gusta.", c:1, pat:"はじめは〜が、今は〜",
      ok:["はじめはそう思いましたが、今はおいしいです。","はじめはそうおもいましたが、いまはおいしいです。"] },
    { k:"f3-12", es:"Este pescado, ¿qué tal? ¿Es de tu gusto?", c:1, pat:"口にあいます",
      ok:["この魚料理、どうですか。口にあいますか。","このさかなりょうり、どうですか。くちにあいますか。"] },
    { k:"f3-13", es:"Por salud, procuro comer toda la verdura que puedo.", c:1, pat:"〜ようにしています",
      ok:["私は健康のために、できるだけ野菜を食べるようにしています。","わたしはけんこうのために、できるだけやさいをたべるようにしています。"] },
    { k:"f3-14", es:"Una vez al día me entran ganas de arroz blanco con sopa de miso.", c:1, pat:"〜たくなる",
      ok:["1日に1回は、白いご飯とみそしるが食べたくなります。","1にちに1かいは、しろいごはんとみそしるがたべたくなります。"] },
    { k:"f3-15", es:"Comida como el ramen hay de muchas clases en el extranjero, pero es distinta del ramen de Japón.", c:2, pat:"〜みたい",
      ok:["ラーメンみたいな食べ物は海外にもいろいろあるので、それも楽しんでいるんですが、日本のラーメンとはちがいます。","ラーメンみたいなたべものはかいがいにもいろいろあるので、それもたのしんでいるんですが、にほんのラーメンとはちがいます。"] },
    { k:"f3-16", es:"El kimbap es una comida parecida al sushi.", c:2, pat:"〜みたい",
      ok:["キンパはおすしみたいな食べ物です。","キンパはおすしみたいなたべものです。"] },
    { k:"f3-17", es:"El ramen no me cansa aunque lo coma todos los días. El Vegemite no es dulce.", c:2, pat:"〜ないです／〜ありません",
      ok:["ラーメンは毎日食べてもあきないです。ベジマイトはあまくありません。","ラーメンはまいにちたべてもあきないです。ベジマイトはあまくありません。"] },
    { k:"f3-18", es:"El ramen no me cansa aunque lo coma todos los días.", c:2, pat:"〜てもあきない",
      ok:["ラーメンは毎日食べてもあきないです。","ラーメンはまいにちたべてもあきないです。"] },
    { k:"f3-19", es:"El Vegemite, para que lo entiendas, parece mermelada, pero no es dulce.", c:2, pat:"〜というのは",
      ok:["ベジマイトというのは、見た目はジャムみたいですが、味はあまくありません。","ベジマイトというのは、みためはジャムみたいですが、あじはあまくありません。"] },
    { k:"f3-20", es:"Mi mujer casi no lo come, pero para mí es el sabor nostálgico de Australia.", c:2, pat:"〜にとって（は）",
      ok:["妻はあまり食べませんが、私にとってはなつかしいオーストラリアの味なんです。","つまはあまりたべませんが、わたしにとってはなつかしいオーストラリアのあじなんです。"] },
    { k:"f3-21", es:"Por eso me llevo ramen instantáneo japonés al extranjero. Pero para la tostada del desayuno tiene que haber Vegemite.", c:2, pat:"それで／でも",
      ok:["それで、海外には日本のカップラーメンを持っていきます。でも、朝食のトーストには、やっぱりベジマイトがないとだめです。","それで、かいがいにはにほんのカップラーメンをもっていきます。でも、ちょうしょくのトーストには、やっぱりベジマイトがないとだめです。"] },
    { k:"f3-22", es:"Para la tostada del desayuno, sin el Vegemite australiano no hay manera.", c:2, pat:"〜ないとだめです",
      ok:["朝食のトーストには、やっぱりオーストラリアのベジマイトがないとだめです。","ちょうしょくのトーストには、やっぱりオーストラリアのベジマイトがないとだめです。"] },
    { k:"f3-23", es:"Por muy buena que esté la comida japonesa, para un indio lo que más reconforta es un curry con buenas especias.", c:2, pat:"どんなに〜ても",
      ok:["どんなに日本料理がおいしくても、インド人にとってはスパイスのきいたカリーが一番ほっとします。","どんなににほんりょうりがおいしくても、インドじんにとってはスパイスのきいたカリーがいちばんほっとします。"] }
  ],

  huecos: [
    /* p46, 文1 */
    { k:"h3-01", pat:"〜ないですか", pre:"肉じゃがも、親子どんも、味が（", post:"）。", hint:"あまいです → 〜ないですか", ok:["あまくないですか"], c:1, es:"El nikujaga y el oyakodon, ¿no están dulces?" },
    { k:"h3-02", pat:"〜ないですか", pre:"くだものは、ねだんが（", post:"）。", hint:"高いです → 〜ないですか", ok:["高くないですか","たかくないですか"], c:1, es:"La fruta, ¿no es cara?" },
    { k:"h3-03", pat:"〜ませんか（すぎ）", pre:"このとんかつは、（", post:"）。", hint:"大きすぎます → 〜ませんか", ok:["大きすぎませんか","おおきすぎませんか"], c:1, es:"Este tonkatsu, ¿no es demasiado grande?" },
    /* p48, 文2 */
    { k:"h3-04", pat:"〜ので", pre:"私、（", post:"）ので、白いご飯とみそしるが一番ほっとするんですよ。", hint:"日本人です → sustantivo + な", ok:["日本人な","にほんじんな"], c:1, es:"Como soy japonesa, lo que más me reconforta es el arroz blanco con sopa de miso." },
    { k:"h3-05", pat:"〜から（りゆう）", pre:"野菜や魚は近所のスーパーに何でも（", post:"）から、問題ないです。", hint:"あります → forma simple", ok:["ある"], c:1, es:"Verdura y pescado hay de todo en el súper del barrio, así que no hay problema." },
    { k:"h3-06", pat:"〜から（りゆう）", pre:"こんど何かおいしいもの（", post:"）から、食べに来てください。", hint:"作ります (aquí en cortés, delante de から)", ok:["作ります","つくります"], c:1, es:"Voy a hacer algo rico un día de estos, así que ven a comer." },
    /* p51, 文2 */
    { k:"h3-07", pat:"〜みたい", pre:"キンパは（", post:"）食べ物です。", hint:"おすし → 〜みたいな", ok:["おすしみたいな"], c:2, es:"El kimbap es una comida parecida al sushi." },
    { k:"h3-08", pat:"〜みたい", pre:"このお茶は（", post:"）においがします。", hint:"花 → 〜みたいな", ok:["花みたいな","はなみたいな"], c:2, es:"Este té huele como a flores." },
    { k:"h3-09", pat:"〜みたい", pre:"バウムクーヘンは見た目が（", post:"）。", hint:"木 → 〜みたいです", ok:["木みたいです","きみたいです"], c:2, es:"El baumkuchen parece un tronco." },
    { k:"h3-10", pat:"〜みたい", pre:"このソフトドリンクは味が（", post:"）。", hint:"しょうゆ → 〜みたいです", ok:["しょうゆみたいです"], c:2, es:"Este refresco sabe como a salsa de soja." },
    /* p52, el dialogo */
    { k:"h3-11", pat:"〜ないです／〜ありません", pre:"さあ、家庭料理で、（", post:"）が、どうぞ。", hint:"ごちそうです → 〜じゃありません", ok:["ごちそうじゃありません","ごちそうじゃないです"], c:2, es:"Venga, es comida casera, nada especial, pero sírvete." },
    { k:"h3-12", pat:"〜ないです／〜ありません", pre:"そうですか。（", post:"）けど…。きらいなものはのこしてくださいね。", hint:"じしんがあります → 〜ありません", ok:["じしんありません","自信ありません","じしんないです"], c:2, es:"¿Sí? No estoy muy segura, pero… Lo que no te guste, déjalo." },
    { k:"h3-13", pat:"〜ないですか", pre:"それ、ちょっと（", post:"）か。", hint:"しょっぱいです → 〜くないです", ok:["しょっぱくないです"], c:2, es:"Eso, ¿no está un poco salado?" },
    { k:"h3-14", pat:"〜ないです／〜ありません", pre:"いえ、ぜんぜん（", post:"）。とってもおいしいです。", hint:"問題があります → 〜ないですよ", ok:["問題ないですよ","もんだいないですよ","問題ないです"], c:2, es:"No, en absoluto. Está riquísimo." },
    /* p52, la tabla */
    { k:"h3-15", pat:"〜ないです／〜ありません", pre:"おかしです → （", post:"）／おかしじゃありません", hint:"sustantivo: 〜じゃないです", ok:["おかしじゃないです"], c:2, es:"Es un dulce → no es un dulce." },
    { k:"h3-16", pat:"〜ないです／〜ありません", pre:"おいしいです → おいしくないです／（", post:"）", hint:"adjetivo い: 〜くありません", ok:["おいしくありません"], c:2, es:"Está rico → no está rico." },
    { k:"h3-17", pat:"〜ないです／〜ありません", pre:"すきです → （", post:"）／すきじゃありません", hint:"adjetivo な: 〜じゃないです", ok:["すきじゃないです"], c:2, es:"Me gusta → no me gusta." },
    { k:"h3-18", pat:"〜ないです／〜ありません", pre:"します → （", post:"）／しません", hint:"verbo: forma ない + です", ok:["しないです"], c:2, es:"Lo hago → no lo hago." },
    { k:"h3-19", pat:"〜ないです／〜ありません", pre:"あります → （", post:"）／ありません", hint:"ある: su ない es irregular", ok:["ないです"], c:2, es:"Hay → no hay." },
    /* dialogos y textos */
    { k:"h3-20", pat:"〜ないですか", pre:"うどんは、外国の人には、味が（", post:"）。", hint:"うすいです → 〜ないですか", ok:["うすくないですか"], c:1, es:"El udon, para un extranjero, ¿no está un poco soso?" },
    { k:"h3-21", pat:"はじめは〜が、今は〜", pre:"はじめは（", post:"）が、今はおいしいです。", hint:"そう思います → forma ました", ok:["そう思いました","そうおもいました"], c:1, es:"Al principio me lo pareció, pero ahora me gusta." },
    { k:"h3-22", pat:"〜させてください", pre:"私にも（", post:"）。", hint:"てつだいます → causativo + てください", ok:["てつだわせてください","手伝わせてください"], c:1, es:"Deja que te ayude yo también." },
    { k:"h3-23", pat:"〜ようにしています", pre:"私は健康のために、できるだけ野菜を（", post:"）。", hint:"食べます → 〜ようにしています", ok:["食べるようにしています","たべるようにしています"], c:1, es:"Por salud, procuro comer toda la verdura que puedo." },
    { k:"h3-24", pat:"〜たくなる", pre:"1日に1回は、白いご飯とみそしるが（", post:"）。", hint:"食べます → 〜たくなります", ok:["食べたくなります","たべたくなります"], c:1, es:"Una vez al día me entran ganas de arroz blanco con sopa de miso." },
    { k:"h3-25", pat:"それで／でも", pre:"（", post:"）、海外には日本のカップラーメンを持っていきます。", hint:"それで o でも: aquí es una consecuencia", ok:["それで"], c:2, es:"Por eso me llevo ramen instantáneo japonés al extranjero." },
    { k:"h3-26", pat:"それで／でも", pre:"（", post:"）、朝食のトーストには、やっぱりベジマイトがないとだめです。", hint:"それで o でも: aquí es un pero", ok:["でも"], c:2, es:"Pero para la tostada del desayuno tiene que haber Vegemite." },
    { k:"h3-27", pat:"どんなに〜ても", pre:"どんなに日本料理が（", post:"）、インド人にとってはカリーが一番ほっとします。", hint:"おいしいです → 〜くても", ok:["おいしくても"], c:2, es:"Por muy buena que esté la comida japonesa, para un indio lo que más reconforta es el curry." },
    { k:"h3-28", pat:"〜てもあきない", pre:"ラーメンは毎日（", post:"）あきないです。", hint:"食べます → 〜ても", ok:["食べても","たべても"], c:2, es:"El ramen no me cansa aunque lo coma todos los días." }
  ],

  armar: [
    { k:"a3-01", es:"¿Qué tal la comida japonesa? ¿Ya te has acostumbrado?", c:1, chips:["日本の食べ物は","いかがですか。","もう","なれましたか"] },
    { k:"a3-02", es:"Pues udon, sushi y cosas así como a menudo.", c:1, chips:["そうですね、","うどんとか、","おすしとか、","よく食べます"] },
    { k:"a3-03", es:"El udon, para un extranjero, ¿no está un poco soso?", c:1, chips:["うどんは、","外国の人には、","味が","うすくないですか"] },
    { k:"a3-04", es:"Al principio me lo pareció, pero ahora me gusta.", c:1, chips:["はじめは","そう思いましたが、","今は","おいしいです"] },
    { k:"a3-05", es:"Como soy japonesa, lo que más me reconforta es el arroz blanco con sopa de miso.", c:1, chips:["私、日本人なので、","白いご飯とみそしるが","一番","ほっとするんですよ"] },
    { k:"a3-06", es:"Verdura y pescado hay de todo en el súper del barrio, así que no hay problema.", c:1, chips:["野菜や魚は","近所のスーパーに","何でもあるから、","問題ないです"] },
    { k:"a3-07", es:"Voy a hacer algo rico un día de estos, así que ven a comer.", c:1, chips:["こんど","何かおいしいもの","作りますから、","食べに来てください"] },
    { k:"a3-08", es:"Por salud, procuro comer toda la verdura que puedo.", c:1, chips:["私は健康のために、","できるだけ","野菜を","食べるようにしています"] },
    { k:"a3-09", es:"Una vez al día me entran ganas de arroz blanco con sopa de miso.", c:1, chips:["1日に1回は、","白いご飯と","みそしるが","食べたくなります"] },
    { k:"a3-10", es:"El kimbap es una comida parecida al sushi.", c:2, chips:["キンパは","おすし","みたいな","食べ物です"] },
    { k:"a3-11", es:"El ramen no me cansa aunque lo coma todos los días.", c:2, chips:["ラーメンは","毎日","食べても","あきないです"] },
    { k:"a3-12", es:"El Vegemite parece mermelada, pero no es dulce.", c:2, chips:["ベジマイトというのは、","見た目はジャムみたいですが、","味は","あまくありません"] },
    { k:"a3-13", es:"Mi mujer casi no lo come, pero para mí es el sabor nostálgico de Australia.", c:2, chips:["妻はあまり食べませんが、","私にとっては","なつかしい","オーストラリアの味なんです"] },
    { k:"a3-14", es:"Venga, es comida casera, nada especial, pero sírvete.", c:2, chips:["さあ、","家庭料理で、","ごちそうじゃありませんが、","どうぞ"] },
    { k:"a3-15", es:"Eso, ¿no está un poco salado? — No, en absoluto. Está riquísimo.", c:2, chips:["それ、ちょっと","しょっぱくないですか。","いえ、ぜんぜん問題ないですよ。","とってもおいしいです"] },
    { k:"a3-16", es:"Cuando salgo a comer procuro, en lo posible, comer comida japonesa.", c:2, chips:["私は外食のときは、","できるだけ","日本料理を","食べるようにしています"] }
  ]
});
