/* Dojo Marugoto - unidad 4, 訪問
   Marugoto A2/B1 Parte 2 - clase 1 = libro p54-59 - clase 2 = p60-63

   De donde salen los huecos:
     h4-01 a h4-05  p55, ejercicio 2   (como se nombra a la familia: 父 / お父さん)
     h4-06 a h4-11  p58-59, 文2        (estilo cortes y estilo llano: a quien se habla)
     h4-12 a h4-19  p61, 文2           (〜てくれます)
     h4-20 a h4-25  p62, 文3           (〜てもらいます)
     h4-26 a h4-32  los dialogos de p56-58 y los textos de p60 y p63

   Clase 1 = la visita y la familia (p54-59); clase 2 = los dos cuadros de
   dar y recibir favores y los textos (p60-63). */

CONTENIDO.unidades.push({
  n: 4,
  titulo: "訪問",
  es: "De visita",
  paginas: { 1: "54-59", 2: "60-63" },
  estado: "lista",

  /* Dos formas nuevas, las dos del mismo molde: forma て + くれました (alguien
     hizo algo por mi) y forma て + もらいました (consegui que alguien lo
     hiciera). Son los cuadros 文2 y 文3 de p61-62. */
  formas: {
    1: ["masu", "masen", "nai", "ta", "te", "tara", "tai", "pot"],
    2: ["masu", "nai", "ta", "te", "tekureru", "temorau", "tara", "pot"]
  },

  patrones: [
    { pat:"ていねいたい・ふつうたい", tipo:"gramatica",
      oficial:"普通体・丁寧体使い分け",
      lectura:"ていねいたい・ふつうたい · teineitai / futsūtai",
      es:"estilo cortés y estilo llano",
      formula:"a la visita, cortés: 〜ました, 〜です · en familia, llano: 〜た, 〜だ, 〜ね, 〜よね",
      uso:"Con quién se habla decide la forma. ようこ le dice a カール 親切な人が多くてたすかりました y a su marido 家族でよく旅行したね. El ejercicio de p58 pide adivinar a quién va cada frase.",
      ejemplo:"親切な人が多くてたすかりました。家族でよく旅行したね。" },

    { pat:"〜てくれます", tipo:"gramatica",
      oficial:"～てくれる",
      lectura:"te kuremasu",
      es:"alguien hace algo por mí",
      formula:"persona + は／が + forma て + くれます. El que recibe soy yo (o los míos), y no hace falta decirlo",
      uso:"El favor visto desde quien lo recibe: アニス me invitó a casa, me escribió la dirección. Sin くれる la frase es un hecho seco; con él, un agradecimiento.",
      ejemplo:"アニスさんが家によんでくれました。" },

    { pat:"〜てもらいます", tipo:"gramatica",
      oficial:"～てもらう",
      lectura:"te moraimasu",
      es:"consigo que alguien haga algo por mí",
      formula:"persona + に + forma て + もらいます. El sujeto soy yo, que recibo",
      uso:"El mismo favor, contado desde el que lo pide o lo recibe: le pedí a アニス que me hiciera de intérprete. La persona lleva に, no が.",
      ejemplo:"アニスさんにつうやくをしてもらいました。" },

    { pat:"〜たこと、ありますか", tipo:"gramatica",
      lectura:"ta koto, arimasu ka",
      es:"¿has estado alguna vez…?, ¿alguna vez…?",
      formula:"forma た + こと（が）ありますか",
      uso:"La experiencia: ¿has ido alguna vez a Estados Unidos? En conversación la が se cae y queda una coma.",
      ejemplo:"山本さんは、アメリカに行ったこと、ありますか。" },

    { pat:"〜んですよ", tipo:"gramatica",
      lectura:"n desu yo",
      es:"es que…, resulta que…",
      formula:"forma simple + んですよ",
      uso:"Contar algo propio que el otro no sabe y que explica la situación: resulta que vivimos en Nueva York. El よ lo entrega como novedad.",
      ejemplo:"カールさん、私たち、ニューヨークに住んでたんですよ。" },

    { pat:"〜から〜まで、約〜", tipo:"gramatica",
      lectura:"kara ~ made, yaku ~",
      es:"de… a…, unos…",
      formula:"año + から + año + まで、約 + duración + 間",
      uso:"Situar un periodo y redondearlo: de 2004 a 2010, unos seis años. 約 es el «aproximadamente» del recuadro de kanji.",
      ejemplo:"2004年から2010年まで、約6年間です。" },

    { pat:"〜なくてこまったけど、〜てたすかりました", tipo:"gramatica",
      lectura:"nakute komatta kedo, te tasukarimashita",
      es:"lo pasé mal por…, pero me salvó que…",
      formula:"forma ない sin la い + くてこまったけど、+ forma て + たすかりました",
      uso:"La experiencia difícil y lo que la alivió: sin entender el idioma me vi en apuros, pero había gente amable. たすかる es «salvarse», «ser un alivio».",
      ejemplo:"ことばがわからなくてこまったけど、親切な人が多くてたすかりました。" },

    { pat:"〜そうです（伝聞）", tipo:"gramatica",
      lectura:"〜そうです（でんぶん）· sō desu",
      es:"dicen que…, me han contado que…",
      formula:"forma simple + そうです. Sustantivo + だそうです",
      uso:"Transmitir lo que otro contó: la abuela de 田中 trabajó en Tailandia, el dulce es casero de la madre. Es el そうです de la unidad 8, aquí en las presentaciones de familia.",
      ejemplo:"帰るとき、アニスさんがおみやげにおかしをくれました。お母さんの手作りだそうです。" },

    { pat:"〜くれました", tipo:"gramatica",
      lectura:"kuremashita",
      es:"me dio…",
      formula:"persona + が + objeto + を + くれました. くれる es «dar» cuando el que recibe soy yo",
      uso:"Dar hacia mí. あげる es dar hacia otro, くれる es dar hacia mí; con もらう se dice desde el que recibe.",
      ejemplo:"アニスさんがおみやげにおかしをくれました。" },

    { pat:"〜のおかげで", tipo:"gramatica",
      lectura:"no okage de",
      es:"gracias a…",
      formula:"persona o cosa + のおかげで + lo bueno que pasó",
      uso:"Atribuir algo bueno a alguien: gracias a 坂本 volví a conectar con Japón. Solo para cosas buenas; para malas es 〜のせいで.",
      ejemplo:"坂本さんのおかげで私はまた日本とつながりました。" },

    { pat:"〜たり〜たりする機会", tipo:"gramatica",
      lectura:"tari ~ tari suru kikai",
      es:"ocasión de… y de…",
      formula:"forma たり + forma たり + する機会",
      uso:"Enumerar oportunidades: ocasiones de usar el japonés, de tocar la cultura japonesa. 機会 es «ocasión, oportunidad».",
      ejemplo:"日本語を使ったり日本の文化にふれたりする機会が少なくて、日本が遠くなっていました。" },

    { pat:"紹介します", tipo:"expresion",
      lectura:"しょうかいします · shōkai shimasu",
      es:"le presento a…",
      formula:"〜さん、紹介します。うちの + parentesco + です。",
      uso:"La fórmula para presentar a la familia a una visita. Se usa el nombre humilde: うちの母, no お母さん.",
      ejemplo:"カールさん、紹介します。うちの母です。今、英語をならってるんですよ。" },

    { pat:"いつもお世話になっています", tipo:"expresion",
      lectura:"いつもおせわになっています · itsumo osewa ni natte imasu",
      es:"gracias por cuidar siempre de…",
      formula:"いつも + persona + が／に + お世話になって（い）ます",
      uso:"Lo que se dice a quien trata con un familiar tuyo: gracias por cuidar de mi hija. La respuesta es こちらこそ, «al contrario, gracias a ustedes».",
      ejemplo:"はじめまして。いつもむすめがお世話になって（い）ます。" },

    { pat:"こちらこそ", tipo:"expresion",
      lectura:"kochira koso",
      es:"al contrario, soy yo quien…",
      formula:"こちらこそ、+ la misma fórmula devuelta",
      uso:"Devolver un agradecimiento: «soy yo quien está en deuda». Va siempre en pareja con お世話になっています.",
      ejemplo:"こちらこそ、いつも山本さんにお世話になって（い）ます。" },

    { pat:"家族のよび方", tipo:"expresion",
      lectura:"かぞくのよびかた · kazoku no yobikata",
      es:"cómo se nombra a la familia",
      formula:"la mía, humilde: 父, 母, 妻, 夫／しゅじん, 子ども, むすめ, むすこ, 姉, そふ · la del otro, respetuosa: お父さん, お母さん, おくさん, お子さん, むすめさん, お姉さん, おじいさん",
      uso:"En japonés hay dos juegos de palabras para la familia: uno para hablar de la mía (humilde) y otro para la del otro (respetuoso). El ejercicio 2 de p55 pide elegir en cada frase.",
      ejemplo:"私の父はエンジニアです。田中さんのおじいさんは、むかし、タイで働いていたそうです。" },

    { pat:"日本の家で", tipo:"expresion",
      lectura:"にほんのいえで · nihon no ie de",
      es:"lo que se hace al entrar en una casa japonesa",
      formula:"ベルをおす → くつをぬぐ → スリッパをはく → へやに入る → 座る／正座をする → 足がしびれる",
      uso:"La secuencia de p55: tocar el timbre, quitarse los zapatos, ponerse las zapatillas, entrar, sentarse en seiza… y que se te duerman las piernas.",
      ejemplo:"ベルをおす。くつをぬぐ。スリッパをはく。へやに入る。座る。正座をする。立つ。足がしびれる。" },

    { pat:"ぐうぜんですね", tipo:"expresion",
      lectura:"gūzen desu ne",
      es:"qué casualidad",
      formula:"ぐうぜんですね。",
      uso:"Lo que se dice al descubrir una coincidencia: yo también estudiaba en Nueva York por entonces.",
      ejemplo:"私もそのころニューヨークで勉強していたんですよ。—— ぐうぜんですね。" },

    { pat:"〜てくれてありがとう", tipo:"expresion",
      lectura:"te kurete arigatō",
      es:"gracias por…",
      formula:"forma て + くれてありがとう",
      uso:"Agradecer una acción concreta: gracias por venir a casa. Es 〜てくれる en forma て más ありがとう.",
      ejemplo:"このあいだはうちにあそびに来てくれてありがとう。" }
  ],

  verbos: [
    /* grupo 1 */
    { kana:"おす", kanji:"おす", g:1, es:"apretar, pulsar", c:1 },
    { kana:"ぬぐ", kanji:"ぬぐ", g:1, es:"quitarse (ropa, zapatos)", c:1 },
    { kana:"はく", kanji:"はく", g:1, es:"ponerse (zapatos, pantalones)", c:1 },
    { kana:"すわる", kanji:"座る", g:1, es:"sentarse", c:1 },
    { kana:"たつ", kanji:"立つ", g:1, es:"ponerse de pie", c:1 },
    { kana:"ならう", kanji:"習う", g:1, es:"aprender (con profesor)", c:1 },
    { kana:"まつ", kanji:"待つ", g:1, es:"esperar", c:1 },
    { kana:"たすかる", kanji:"たすかる", g:1, es:"ser un alivio, salvarse", c:1 },
    { kana:"おくる", kanji:"送る", g:1, es:"enviar", c:2 },
    { kana:"かす", kanji:"貸す", g:1, es:"prestar", c:2 },
    { kana:"かざる", kanji:"かざる", g:1, es:"decorar, poner de adorno", c:2 },
    { kana:"つながる", kanji:"つながる", g:1, es:"conectarse, vincularse", c:2 },
    { kana:"あがる", kanji:"上がる", g:1, es:"subir, pasar (a una casa)", c:1 },
    { kana:"つれていく", kanji:"連れていく", g:1, es:"llevar a alguien", c:2, nota:"Termina en いく: la forma て es つれていって, como 行く" },
    /* grupo 2 */
    { kana:"くれる", kanji:"くれる", g:2, es:"dar (a mí)", c:2 },
    { kana:"おぼえる", kanji:"おぼえる", g:2, es:"recordar, aprender", c:1 },
    { kana:"しびれる", kanji:"しびれる", g:2, es:"dormirse (una pierna)", c:1 },
    { kana:"ふれる", kanji:"ふれる", g:2, es:"tocar, entrar en contacto", c:2 },
    /* grupo 3 */
    { kana:"しょうかいする", kanji:"紹介する", g:3, es:"presentar (a alguien)", c:1 },
    { kana:"ほうもんする", kanji:"訪問する", g:3, es:"visitar", c:1 },
    { kana:"けいけんする", kanji:"経験する", g:3, es:"experimentar, vivir (algo)", c:1 },
    { kana:"りょこうする", kanji:"旅行する", g:3, es:"viajar", c:1 },
    { kana:"りゅうがくする", kanji:"留学する", g:3, es:"estudiar en el extranjero", c:2 },
    { kana:"でんわする", kanji:"電話する", g:3, es:"llamar por teléfono", c:2 },
    { kana:"びっくりする", kanji:"びっくりする", g:3, es:"sorprenderse", c:2 },
    { kana:"じゃまする", kanji:"じゃまする", g:3, es:"molestar (al entrar en una casa)", c:1 }
  ],

  vocab: [
    /* la familia, la mia y la del otro (p55, p56) */
    { jp:"家族", kana:"かぞく", es:"familia", c:1, cat:"persona" },
    { jp:"父", kana:"ちち", es:"mi padre", c:1, cat:"persona" },
    { jp:"お父さん", kana:"おとうさん", es:"padre (del otro)", c:1, cat:"persona" },
    { jp:"母", kana:"はは", es:"mi madre", c:1, cat:"persona" },
    { jp:"お母さん", kana:"おかあさん", es:"madre (del otro)", c:1, cat:"persona" },
    { jp:"妻", kana:"つま", es:"mi esposa", c:1, cat:"persona" },
    { jp:"おくさん", kana:"おくさん", es:"esposa (del otro)", c:1, cat:"persona" },
    { jp:"夫", kana:"おっと", es:"mi marido", c:1, cat:"persona" },
    { jp:"しゅじん", kana:"しゅじん", es:"mi marido (al presentarlo)", c:1, cat:"persona" },
    { jp:"むすめ", kana:"むすめ", es:"mi hija", c:1, cat:"persona" },
    { jp:"むすめさん", kana:"むすめさん", es:"hija (del otro)", c:1, cat:"persona" },
    { jp:"むすこ", kana:"むすこ", es:"mi hijo", c:1, cat:"persona" },
    { jp:"お子さん", kana:"おこさん", es:"hijo (del otro)", c:1, cat:"persona" },
    { jp:"姉", kana:"あね", es:"mi hermana mayor", c:1, cat:"persona" },
    { jp:"お姉さん", kana:"おねえさん", es:"hermana mayor (del otro)", c:1, cat:"persona" },
    { jp:"お兄さん", kana:"おにいさん", es:"hermano mayor (del otro)", c:2, cat:"persona" },
    { jp:"そふ", kana:"そふ", es:"mi abuelo", c:1, cat:"persona" },
    { jp:"おじいさん", kana:"おじいさん", es:"abuelo (del otro)", c:1, cat:"persona" },
    { jp:"そぼ", kana:"そぼ", es:"mi abuela", c:1, cat:"persona" },
    { jp:"ご両親", kana:"ごりょうしん", es:"los padres (del otro)", c:2, cat:"persona" },
    { jp:"ご家族", kana:"ごかぞく", es:"la familia (del otro)", c:2, cat:"persona" },
    { jp:"お客様", kana:"おきゃくさま", es:"invitado, visita (formal)", c:2, cat:"persona" },
    { jp:"エンジニア", kana:"エンジニア", es:"ingeniero", c:1, cat:"trabajo" },
    { jp:"ペット", kana:"ペット", es:"mascota", c:1, cat:"casa" },

    /* la visita (p55, p57) */
    { jp:"訪問", kana:"ほうもん", es:"visita", c:1, cat:"abstracto" },
    { jp:"げんかん", kana:"げんかん", es:"la entrada (de una casa)", c:1, cat:"casa" },
    { jp:"ベル", kana:"ベル", es:"timbre", c:1, cat:"casa" },
    { jp:"くつ", kana:"くつ", es:"zapatos", c:1, cat:"objetos" },
    { jp:"スリッパ", kana:"スリッパ", es:"zapatillas de casa", c:1, cat:"objetos" },
    { jp:"正座", kana:"せいざ", es:"seiza (sentarse de rodillas)", c:1, cat:"abstracto" },
    { jp:"足", kana:"あし", es:"pierna, pie", c:1, cat:"abstracto" },
    { jp:"おみやげ", kana:"おみやげ", es:"regalo (que se lleva de visita)", c:2, cat:"objetos" },
    { jp:"手作り", kana:"てづくり", es:"hecho a mano, casero", c:2, cat:"cualidad" },
    { jp:"住所", kana:"じゅうしょ", es:"dirección", c:2, cat:"abstracto" },
    { jp:"電話番号", kana:"でんわばんごう", es:"número de teléfono", c:2, cat:"abstracto" },
    { jp:"名前", kana:"なまえ", es:"nombre", c:1, cat:"abstracto" },
    { jp:"写真", kana:"しゃしん", es:"foto", c:2, cat:"objetos" },
    { jp:"カメラ", kana:"カメラ", es:"cámara", c:2, cat:"objetos" },
    { jp:"生け花", kana:"いけばな", es:"ikebana", c:2, cat:"abstracto" },
    { jp:"おどり", kana:"おどり", es:"baile, danza", c:2, cat:"abstracto" },
    { jp:"歌", kana:"うた", es:"canción", c:2, cat:"abstracto" },
    { jp:"音楽", kana:"おんがく", es:"música", c:2, cat:"abstracto" },
    { jp:"レシピ", kana:"レシピ", es:"receta", c:2, cat:"objetos" },
    { jp:"市場", kana:"いちば", es:"mercado", c:2, cat:"lugar" },
    { jp:"しゅみ", kana:"しゅみ", es:"afición", c:1, cat:"abstracto" },

    /* la experiencia en el extranjero (p58-59, p63) */
    { jp:"経験", kana:"けいけん", es:"experiencia", c:1, cat:"abstracto" },
    { jp:"思い出", kana:"おもいで", es:"recuerdo (de algo vivido)", c:1, cat:"abstracto" },
    { jp:"人生", kana:"じんせい", es:"la vida (de una persona)", c:1, cat:"abstracto" },
    { jp:"人生観", kana:"じんせいかん", es:"visión de la vida", c:1, cat:"abstracto" },
    { jp:"〜観", kana:"〜かん", es:"visión de…, manera de ver… (人生観)", c:1, cat:"abstracto" },
    { jp:"けしき", kana:"けしき", es:"paisaje, vistas", c:1, cat:"lugar" },
    { jp:"機会", kana:"きかい", es:"ocasión, oportunidad", c:2, cat:"abstracto" },
    { jp:"つながり", kana:"つながり", es:"vínculo, conexión", c:2, cat:"abstracto" },
    { jp:"ちがい", kana:"ちがい", es:"diferencia", c:1, cat:"abstracto" },
    { jp:"通訳", kana:"つうやく", es:"intérprete, interpretación", c:2, cat:"trabajo" },
    { jp:"インドネシア語", kana:"インドネシアご", es:"indonesio (idioma)", c:2, cat:"abstracto" },
    { jp:"英語", kana:"えいご", es:"inglés (idioma)", c:1, cat:"abstracto" },
    { jp:"約〜", kana:"やく〜", es:"unos…, aproximadamente", c:1, cat:"conector" },
    { jp:"〜年間", kana:"〜ねんかん", es:"durante … años", c:1, cat:"tiempo" },
    { jp:"むかし", kana:"むかし", es:"hace mucho, antes", c:1, cat:"tiempo" },
    { jp:"そのころ", kana:"そのころ", es:"por entonces", c:1, cat:"tiempo" },
    { jp:"いつごろ", kana:"いつごろ", es:"¿por cuándo?", c:1, cat:"tiempo" },
    { jp:"このあいだ", kana:"このあいだ", es:"el otro día", c:2, cat:"tiempo" },
    { jp:"初めて", kana:"はじめて", es:"por primera vez", c:2, cat:"tiempo" },

    /* como es la gente y las cosas */
    { jp:"親切", kana:"しんせつ", es:"amable, atento", c:1, cat:"cualidad" },
    { jp:"やさしい", kana:"やさしい", es:"amable, bueno (una persona)", c:2, cat:"cualidad" },
    { jp:"上手", kana:"じょうず", es:"hábil, que lo hace bien", c:2, cat:"cualidad" },
    { jp:"くわしい", kana:"くわしい", es:"que sabe mucho de, detallado", c:2, cat:"cualidad" },
    { jp:"すごい", kana:"すごい", es:"impresionante", c:1, cat:"cualidad" },
    { jp:"あたたかい", kana:"あたたかい", es:"cálido, acogedor", c:2, cat:"cualidad" },
    { jp:"さびしい", kana:"さびしい", es:"triste, solo", c:2, cat:"sentimiento" },
    { jp:"ぐうぜん", kana:"ぐうぜん", es:"casualidad", c:1, cat:"abstracto" },
    { jp:"おかげ", kana:"おかげ", es:"gracias a", c:2, cat:"conector" },
    { jp:"特に", kana:"とくに", es:"especialmente", c:1, cat:"conector" },
    { jp:"ゆっくり", kana:"ゆっくり", es:"despacio", c:2, cat:"conector" },

    /* muletillas de la visita */
    { jp:"はじめまして", kana:"はじめまして", es:"encantado (al conocer a alguien)", c:1, cat:"reaccion" },
    { jp:"いらっしゃい", kana:"いらっしゃい", es:"bienvenido (en casa)", c:1, cat:"reaccion" },
    { jp:"ごめんください", kana:"ごめんください", es:"¿se puede? (al llegar a una casa)", c:1, cat:"reaccion" },
    { jp:"お世話になっています", kana:"おせわになっています", es:"gracias por cuidar de…", c:1, cat:"reaccion" },
    { jp:"こちらこそ", kana:"こちらこそ", es:"al contrario", c:1, cat:"reaccion" },
    { jp:"へえ", kana:"へえ", es:"¿ah, sí?", c:1, cat:"reaccion" },
    { jp:"こっち", kana:"こっち", es:"por aquí (informal)", c:1, cat:"reaccion" }
  ],

  frases: [
    { k:"f4-01", es:"Había mucha gente amable y fue un alivio. — Viajamos mucho en familia, ¿eh?", c:1, pat:"ていねいたい・ふつうたい",
      ok:["親切な人が多くてたすかりました。家族でよく旅行したね。","しんせつなひとがおおくてたすかりました。かぞくでよくりょこうしたね。"] },
    { k:"f4-02", es:"Anis me invitó a su casa.", c:2, pat:"〜てくれます",
      ok:["アニスさんが家によんでくれました。","アニスさんがいえによんでくれました。"] },
    { k:"f4-03", es:"Anis me escribió la dirección y el número de teléfono.", c:2, pat:"〜てくれます",
      ok:["アニスさんは住所と電話番号を書いてくれました。","アニスさんはじゅうしょとでんわばんごうをかいてくれました。"] },
    { k:"f4-04", es:"Le pedí a Anis que me hiciera de intérprete.", c:2, pat:"〜てもらいます",
      ok:["アニスさんにつうやくをしてもらいました。","アニスさんに通訳をしてもらいました。"] },
    { k:"f4-05", es:"Como no entiendo bien el indonesio, pedí a sus padres que hablaran despacio.", c:2, pat:"〜てもらいます",
      ok:["インドネシア語がよくわからないので、ご両親にゆっくりはなしてもらいました。","インドネシアごがよくわからないので、ごりょうしんにゆっくりはなしてもらいました。"] },
    { k:"f4-06", es:"Señor Yamamoto, ¿ha estado alguna vez en Estados Unidos?", c:1, pat:"〜たこと、ありますか",
      ok:["山本さんは、アメリカに行ったこと、ありますか。","やまもとさんは、アメリカにいったこと、ありますか。"] },
    { k:"f4-07", es:"Karl, resulta que nosotros vivimos en Nueva York.", c:1, pat:"〜んですよ",
      ok:["カールさん、私たち、ニューヨークに住んでたんですよ。","カールさん、わたしたち、ニューヨークにすんでたんですよ。"] },
    { k:"f4-08", es:"De 2004 a 2010, unos seis años.", c:1, pat:"〜から〜まで、約〜",
      ok:["2004年から2010年まで、約6年間です。","2004ねんから2010ねんまで、やく6ねんかんです。"] },
    { k:"f4-09", es:"Lo pasé mal sin entender el idioma, pero había mucha gente amable y fue un alivio.", c:1, pat:"〜なくてこまったけど、〜てたすかりました",
      ok:["ことばがわからなくてこまったけど、親切な人が多くてたすかりました。","ことばがわからなくてこまったけど、しんせつなひとがおおくてたすかりました。"] },
    { k:"f4-10", es:"Al irme, Anis me dio unos dulces de regalo. Dice que los hizo su madre.", c:2, pat:"〜そうです（伝聞）",
      ok:["帰るとき、アニスさんがおみやげにおかしをくれました。お母さんの手作りだそうです。","かえるとき、アニスさんがおみやげにおかしをくれました。おかあさんのてづくりだそうです。"] },
    { k:"f4-11", es:"Anis me dio unos dulces de regalo.", c:2, pat:"〜くれました",
      ok:["アニスさんがおみやげにおかしをくれました。"] },
    { k:"f4-12", es:"Gracias a Sakamoto, volví a conectar con Japón.", c:2, pat:"〜のおかげで",
      ok:["坂本さんのおかげで私はまた日本とつながりました。","さかもとさんのおかげでわたしはまたにほんとつながりました。"] },
    { k:"f4-13", es:"Tenía pocas ocasiones de usar el japonés o de tocar la cultura japonesa, y Japón se me había vuelto lejano.", c:2, pat:"〜たり〜たりする機会",
      ok:["日本語を使ったり日本の文化にふれたりする機会が少なくて、日本が遠くなっていました。","にほんごをつかったりにほんのぶんかにふれたりするきかいがすくなくて、にほんがとおくなっていました。"] },
    { k:"f4-14", es:"Karl, le presento: mi madre. Ahora está aprendiendo inglés.", c:1, pat:"紹介します",
      ok:["カールさん、紹介します。うちの母です。今、英語をならってるんですよ。","カールさん、しょうかいします。うちのははです。いま、えいごをならってるんですよ。"] },
    { k:"f4-15", es:"Encantada. Gracias por cuidar siempre de mi hija.", c:1, pat:"いつもお世話になっています",
      ok:["はじめまして。いつもむすめがお世話になって（い）ます。","はじめまして。いつもむすめがおせわになっています。","はじめまして。いつもむすめがお世話になっています。"] },
    { k:"f4-16", es:"Al contrario, soy yo quien recibe siempre las atenciones de Yamamoto.", c:1, pat:"こちらこそ",
      ok:["こちらこそ、いつも山本さんにお世話になって（い）ます。","こちらこそ、いつもやまもとさんにおせわになっています。","こちらこそ、いつも山本さんにお世話になっています。"] },
    { k:"f4-17", es:"Mi padre es ingeniero. El abuelo de Tanaka, dicen, trabajó hace años en Tailandia.", c:1, pat:"家族のよび方",
      ok:["私の父はエンジニアです。田中さんのおじいさんは、むかし、タイで働いていたそうです。","わたしのちちはエンジニアです。たなかさんのおじいさんは、むかし、タイではたらいていたそうです。"] },
    { k:"f4-18", es:"Tocar el timbre. Quitarse los zapatos. Ponerse las zapatillas. Entrar. Sentarse. Seiza. Levantarse. Se duermen las piernas.", c:1, pat:"日本の家で",
      ok:["ベルをおす。くつをぬぐ。スリッパをはく。へやに入る。座る。正座をする。立つ。足がしびれる。","ベルをおす。くつをぬぐ。スリッパをはく。へやにはいる。すわる。せいざをする。たつ。あしがしびれる。"] },
    { k:"f4-19", es:"Yo también estudiaba en Nueva York por entonces. — Qué casualidad.", c:1, pat:"ぐうぜんですね",
      ok:["私もそのころニューヨークで勉強していたんですよ。—— ぐうぜんですね。","私もそのころニューヨークで勉強していたんですよ。ぐうぜんですね。","わたしもそのころニューヨークでべんきょうしていたんですよ。ぐうぜんですね。"] },
    { k:"f4-20", es:"Gracias por venir a casa el otro día.", c:2, pat:"〜てくれてありがとう",
      ok:["このあいだはうちにあそびに来てくれてありがとう。","このあいだはうちにあそびにきてくれてありがとう。"] }
  ],

  huecos: [
    /* p55, ejercicio 2: mi familia / la del otro */
    { k:"h4-01", pat:"家族のよび方", pre:"私の（", post:"）はエンジニアです。", hint:"mi padre, humilde: 父 o お父さん", ok:["父","ちち"], c:1, es:"Mi padre es ingeniero." },
    { k:"h4-02", pat:"家族のよび方", pre:"うちは、（", post:"）と子ども2人の、4人家族です。", hint:"mi mujer: 妻 o おくさん", ok:["妻","つま"], c:1, es:"Somos cuatro: mi mujer, los dos niños y yo." },
    { k:"h4-03", pat:"家族のよび方", pre:"シンさんは（", post:"）が3人いるそうです。", hint:"la hermana de otro: 姉 o お姉さん", ok:["お姉さん","おねえさん"], c:1, es:"Dicen que Shin tiene tres hermanas mayores." },
    { k:"h4-04", pat:"家族のよび方", pre:"田中さんの（", post:"）は、むかし、タイで働いていたそうです。", hint:"el abuelo de otro: そふ o おじいさん", ok:["おじいさん"], c:1, es:"Dicen que el abuelo de Tanaka trabajó hace años en Tailandia." },
    { k:"h4-05", pat:"家族のよび方", pre:"私の（", post:"）の家族は、広島に住んでいます。", hint:"mi hija: むすめ o むすめさん", ok:["むすめ"], c:1, es:"La familia de mi hija vive en Hiroshima." },
    /* p58-59, 文2: a quien se habla */
    { k:"h4-06", pat:"ていねいたい・ふつうたい", pre:"私たち、ニューヨークに住んでたんですよ。 ようこ → （", post:"）", hint:"cortés: ¿a la visita o al marido?", ok:["カール","カールさん"], c:1, es:"«Nosotros vivimos en Nueva York.» ¿A quién se lo dice Yōko?" },
    { k:"h4-07", pat:"ていねいたい・ふつうたい", pre:"ぐうぜんですね。 ようこ → （", post:"）", hint:"cortés", ok:["カール","カールさん"], c:1, es:"«Qué casualidad.» ¿A quién?" },
    { k:"h4-08", pat:"ていねいたい・ふつうたい", pre:"親切な人が多くてたすかりました。 ようこ → （", post:"）", hint:"cortés", ok:["カール","カールさん"], c:1, es:"«Había mucha gente amable y fue un alivio.» ¿A quién?" },
    { k:"h4-09", pat:"ていねいたい・ふつうたい", pre:"家族でよく旅行したね。 かずお → （", post:"）", hint:"llano: a su mujer", ok:["ようこ","ようこさん"], c:1, es:"«Viajamos mucho en familia, ¿eh?» ¿A quién?" },
    { k:"h4-10", pat:"ていねいたい・ふつうたい", pre:"おぼえてるか。 かずお → （", post:"）", hint:"llano", ok:["ようこ","ようこさん"], c:1, es:"«¿Te acuerdas?» ¿A quién?" },
    { k:"h4-11", pat:"ていねいたい・ふつうたい", pre:"わすれられないけしきだよね。 ようこ → （", post:"）", hint:"llano: a su marido", ok:["かずお","かずおさん"], c:1, es:"«Un paisaje que no se olvida, ¿verdad?» ¿A quién?" },
    /* p61, 文2: 〜てくれます */
    { k:"h4-12", pat:"〜てくれます", pre:"アニスさんは私を家に（", post:"）。", hint:"よびました → 〜てくれました", ok:["よんでくれました"], c:2, es:"Anis me invitó a su casa." },
    { k:"h4-13", pat:"〜てくれます", pre:"住所と電話番号を（", post:"）。", hint:"書きました → 〜てくれました", ok:["書いてくれました","かいてくれました"], c:2, es:"Me escribió la dirección y el número de teléfono." },
    { k:"h4-14", pat:"〜てくれます", pre:"私の家まで車で（", post:"）。", hint:"むかえに来ました → 〜てくれました", ok:["むかえに来てくれました","むかえにきてくれました"], c:2, es:"Vino a buscarme a casa en coche." },
    { k:"h4-15", pat:"〜てくれます", pre:"いちばに（", post:"）。", hint:"つれていきました → 〜てくれました", ok:["つれていってくれました"], c:2, es:"Me llevó al mercado." },
    { k:"h4-16", pat:"〜てくれます", pre:"坂本さんはおみやげを（", post:"）。", hint:"持ってきました → 〜てくれました", ok:["持ってきてくれました","もってきてくれました"], c:2, es:"Sakamoto me trajo un regalo." },
    { k:"h4-17", pat:"〜てくれます", pre:"いちばで買い物をするとき、（", post:"）。", hint:"てつだいました → 〜てくれました", ok:["てつだってくれました","手伝ってくれました"], c:2, es:"Cuando compramos en el mercado, me ayudó." },
    { k:"h4-18", pat:"〜てくれます", pre:"兄の子どもと（", post:"）。", hint:"あそびました → 〜てくれました", ok:["あそんでくれました"], c:2, es:"Jugó con el hijo de mi hermano." },
    { k:"h4-19", pat:"〜てくれます", pre:"うちの料理を何でもおいしいと言って（", post:"）。", hint:"食べました → 〜てくれました", ok:["食べてくれました","たべてくれました"], c:2, es:"Se comió todo lo de casa diciendo que estaba rico." },
    /* p62, 文3: 〜てもらいます */
    { k:"h4-20", pat:"〜てもらいます", pre:"インドネシア語がよくわからないので、ご両親にゆっくり（", post:"）。", hint:"話しました → 〜てもらいました", ok:["はなしてもらいました","話してもらいました"], c:2, es:"Como no entiendo bien el indonesio, pedí a sus padres que hablaran despacio." },
    { k:"h4-21", pat:"〜てもらいます", pre:"お兄さんのカメラで写真を（", post:"）。", hint:"とりました → 〜てもらいました", ok:["とってもらいました"], c:2, es:"Me hicieron una foto con la cámara de su hermano." },
    { k:"h4-22", pat:"〜てもらいます", pre:"そして、その写真をメールで（", post:"）。", hint:"送りました → 〜てもらいました", ok:["送ってもらいました","おくってもらいました"], c:2, es:"Y me enviaron esa foto por correo." },
    { k:"h4-23", pat:"〜てもらいます", pre:"アニスさんにインドネシアの音楽のCDを（", post:"）。", hint:"貸しました → 〜てもらいました", ok:["貸してもらいました","かしてもらいました"], c:2, es:"Anis me prestó un CD de música indonesia." },
    { k:"h4-24", pat:"〜てもらいます", pre:"アニスさんにつうやくを（", post:"）。", hint:"しました → 〜てもらいました", ok:["してもらいました"], c:2, es:"Le pedí a Anis que me hiciera de intérprete." },
    { k:"h4-25", pat:"〜てもらいます", pre:"アニスさんにインドネシア語を（", post:"）。", hint:"教えました → 〜てもらいました", ok:["教えてもらいました","おしえてもらいました"], c:2, es:"Anis me enseñó indonesio." },
    /* dialogos y textos */
    { k:"h4-26", pat:"紹介します", pre:"カールさん、（", post:"）。うちの母です。", hint:"presentar → forma ます", ok:["紹介します","しょうかいします"], c:1, es:"Karl, le presento: mi madre." },
    { k:"h4-27", pat:"いつもお世話になっています", pre:"はじめまして。いつもむすめが（", post:"）。", hint:"la fórmula: お世話に…", ok:["お世話になっています","おせわになっています","お世話になってます","おせわになってます"], c:1, es:"Encantada. Gracias por cuidar siempre de mi hija." },
    { k:"h4-28", pat:"〜たこと、ありますか", pre:"山本さんは、アメリカに（", post:"）、ありますか。", hint:"行きます → 〜たこと", ok:["行ったこと","いったこと"], c:1, es:"Señor Yamamoto, ¿ha estado alguna vez en Estados Unidos?" },
    { k:"h4-29", pat:"〜なくてこまったけど、〜てたすかりました", pre:"ことばが（", post:"）こまったけど、親切な人が（", post2:"）たすかりました。", hint:"わかりません → 〜なくて / 多いです → 〜くて", ok:["わからなくて"], ok2:["多くて","おおくて"], c:1, es:"Lo pasé mal sin entender el idioma, pero había mucha gente amable y fue un alivio." },
    { k:"h4-30", pat:"〜そうです（伝聞）", pre:"アニスさんがおみやげにおかしをくれました。お母さんの（", post:"）。", hint:"手作りです → dicen que es: 〜だそうです", ok:["手作りだそうです","てづくりだそうです"], c:2, es:"Anis me dio dulces. Dicen que son caseros, de su madre." },
    { k:"h4-31", pat:"〜のおかげで", pre:"坂本さん（", post:"）私はまた日本とつながりました。", hint:"gracias a…", ok:["のおかげで"], c:2, es:"Gracias a Sakamoto, volví a conectar con Japón." },
    { k:"h4-32", pat:"〜てくれてありがとう", pre:"このあいだはうちにあそびに（", post:"）ありがとう。", hint:"来ました → 〜てくれて", ok:["来てくれて","きてくれて"], c:2, es:"Gracias por venir a casa el otro día." }
  ],

  armar: [
    { k:"a4-01", es:"Karl, le presento: mi madre. Ahora está aprendiendo inglés.", c:1, chips:["カールさん、紹介します。","うちの母です。","今、英語を","ならってるんですよ"] },
    { k:"a4-02", es:"Encantada. Gracias por cuidar siempre de mi hija.", c:1, chips:["はじめまして。","いつも","むすめが","お世話になっています"] },
    { k:"a4-03", es:"Al contrario, soy yo quien recibe siempre las atenciones de Yamamoto.", c:1, chips:["こちらこそ、","いつも","山本さんに","お世話になっています"] },
    { k:"a4-04", es:"Señor Yamamoto, ¿ha estado alguna vez en Estados Unidos?", c:1, chips:["山本さんは、","アメリカに","行ったこと、","ありますか"] },
    { k:"a4-05", es:"Karl, resulta que nosotros vivimos en Nueva York.", c:1, chips:["カールさん、","私たち、","ニューヨークに","住んでたんですよ"] },
    { k:"a4-06", es:"De 2004 a 2010, unos seis años.", c:1, chips:["2004年から","2010年まで、","約6年間","です"] },
    { k:"a4-07", es:"Lo pasé mal sin entender el idioma, pero había mucha gente amable y fue un alivio.", c:1, chips:["ことばがわからなくて","こまったけど、","親切な人が多くて","たすかりました"] },
    { k:"a4-08", es:"Viajamos mucho en familia, ¿eh? ¿Te acuerdas? El Gran Cañón fue impresionante.", c:1, chips:["家族でよく旅行したね。","おぼえてるか。","グランドキャニオン、","すごかったよね"] },
    { k:"a4-09", es:"Anis me invitó a su casa.", c:2, chips:["アニスさんが","家に","よんで","くれました"] },
    { k:"a4-10", es:"Como no sé indonesio, pedí a Anis que me hiciera de intérprete.", c:2, chips:["インドネシア語ができないので、","アニスさんに","つうやくを","してもらいました"] },
    { k:"a4-11", es:"Anis me enseñó las fotos que hizo en Japón.", c:2, chips:["アニスさんは","日本でとった写真を","見せて","くれました"] },
    { k:"a4-12", es:"Al irme, Anis me dio unos dulces de regalo.", c:2, chips:["帰るとき、","アニスさんが","おみやげに","おかしをくれました"] },
    { k:"a4-13", es:"La familia de Anis me recibió con calidez y fue un día de verdad feliz.", c:2, chips:["アニスさんの家族が","あたたかく迎えてくれて、","ほんとうに","うれしい一日でした"] },
    { k:"a4-14", es:"Gracias a Sakamoto, volví a conectar con Japón.", c:2, chips:["坂本さんの","おかげで","私はまた","日本とつながりました"] },
    { k:"a4-15", es:"Gracias por venir a casa el otro día.", c:2, chips:["このあいだは","うちに","あそびに来てくれて","ありがとう"] },
    { k:"a4-16", es:"Con la receta que me enseñaste, la próxima vez lo haré yo.", c:2, chips:["教えてもらった","レシピで、","こんど自分で","作ってみます"] }
  ]
});
