/* Dojo Marugoto - unidad 5, ことばを学ぶ楽しみ
   Marugoto A2/B1 Parte 2 - clase 1 = libro p64-69 - clase 2 = p70-73

   De donde salen los huecos:
     h5-01 a h5-05  p65, ejercicio 2   (como se estudia un idioma)
     h5-06 a h5-08  p66, 文2           (〜ように)
     h5-09 a h5-14  p68-69, 文2        (estilo cortes y llano: a quien se habla)
     h5-15 a h5-18  p71, 文2           (〜ようと思っています, いこうけい)
     h5-19 a h5-23  p72, 文3           (〜そうです de aspecto)
     h5-24 a h5-28  p72, 文4           (も, だけ, しか)
     h5-29 a h5-34  los dialogos de p67-68 y los textos de p70 y p73 */

CONTENIDO.unidades.push({
  n: 5,
  titulo: "ことばを学ぶ楽しみ",
  es: "El gusto de aprender idiomas",
  paginas: { 1: "64-69", 2: "70-73" },
  estado: "lista",

  /* Tres formas nuevas: la volitiva いこうけい (p71, con su tabla), el
     〜そうです de aspecto (p72: とれそうです, 読めそうです) y 〜ようになりました
     (p66: 聞きとれるようになりました). */
  formas: {
    1: ["masu", "masen", "nai", "ta", "te", "pot", "youni", "tai"],
    2: ["masu", "nai", "ta", "te", "you", "sou2", "pot", "tara"]
  },

  patrones: [
    { pat:"〜ように", tipo:"gramatica",
      oficial:"～ように",
      lectura:"yō ni",
      es:"para que…, de modo que…",
      formula:"forma diccionario o potencial + ようにしています (procuro) · + ようになりました (he llegado a) · + ように、+ lo que hago (para poder)",
      uso:"Tres usos de la misma pieza: el hábito que me impongo (話すようにしています), el cambio que se logró (聞きとれるようになりました) y la meta (上手になれるように、毎日ニュースを見ています).",
      ejemplo:"せっきょく的に英語を話すようにして（い）ます。" },

    { pat:"ていねいたい・ふつうたい２", tipo:"gramatica",
      oficial:"普通体・丁寧体使い分け",
      lectura:"ていねいたい・ふつうたい · teineitai / futsūtai",
      es:"estilo cortés y llano, según quién sea",
      formula:"al せんぱい, cortés: 〜ます, 〜ですね · al こうはい o al amigo, llano: 〜てる, 〜よ, 〜ね",
      uso:"La relación decide el estilo, y en la misma conversación cambia: さいとう le habla llano a 田中 (su こうはい) y cortés a エスター; 田中 le habla cortés a さいとう y llano a エスター (su amiga).",
      ejemplo:"日本語の学校、続いてますね。英語の学校、続いてるね。" },

    { pat:"〜（よ）うと思っています", tipo:"gramatica",
      oficial:"～（よ）うと思っている",
      lectura:"〜（よ）うとおもっています · (y)ō to omotte imasu",
      es:"tengo pensado…, pienso…",
      formula:"いこうけい + と思っています. Grupo 1: última sílaba a la fila お + う (行く → 行こう); grupo 2: quita る + よう (食べよう); する → しよう, くる → こよう",
      uso:"Una intención que ya se ha tomado: cuando me gradúe pienso irme a estudiar a Japón. Más firme que 〜たいと思っています, que es solo el deseo.",
      ejemplo:"大学を卒業したら、日本に留学しようと思っています。" },

    { pat:"〜そうです（様態）", tipo:"gramatica",
      oficial:"～そうだ",
      lectura:"〜そうです（ようたい）· sō desu",
      es:"parece que…, tiene pinta de que…",
      formula:"raíz de ます + そうです (とれそうです); potencial: raíz + そうです (読めそうです); delante de sustantivo: 〜そうな + N (読めそうな本)",
      uso:"Lo que se ve venir por las señales: parece que sacaré buena nota, este libro parece que podré leerlo. No es el «dicen que» de la unidad 8: aquí va con la raíz, no con el verbo entero.",
      ejemplo:"つぎの試験は、いいせいせきがとれそうです。" },

    { pat:"（数量）も", tipo:"gramatica",
      oficial:"～も",
      lectura:"（すうりょう）も · mo",
      es:"nada menos que…, hasta…",
      formula:"cantidad + も (3時間も) · pregunta + も (何時間も, 何人も) = «muchísimos»",
      uso:"Subraya que una cantidad es grande: tres horas nada menos. Con una palabra de pregunta, «un montón»: 何時間も, «horas y horas». La pareja es しか + negativo, que subraya lo poco.",
      ejemplo:"毎日30分ぐらいチャットをしますが、きのうは3時間もしました。" },

    { pat:"も・だけ・しか", tipo:"gramatica",
      lectura:"mo / dake / shika",
      es:"nada menos que… / solo… / no más que…",
      formula:"cantidad + も (mucho) · cantidad + だけ (solo, neutro) · cantidad + しか + negativo (solo, y es poco)",
      uso:"Las tres partículas de cantidad del ejercicio de p72: 何人も «muchos», 3つだけ «solo tres», 4人しかいません «no hay más que cuatro». しか obliga al verbo en negativo.",
      ejemplo:"この学校には、外国人の先生が何人もいます。日本語のコースは、初級、中級、上級の3つだけです。上級コースは難しいので、学生が4人しかいません。" },

    { pat:"〜ようになりました", tipo:"gramatica",
      lectura:"yō ni narimashita",
      es:"he llegado a…, ya puedo…",
      formula:"forma potencial + ようになりました",
      uso:"El progreso conseguido: antes no entendía las conversaciones rápidas, ahora sí. Casi siempre con la potencial.",
      ejemplo:"CDをよく聞いたので、はやい会話が聞きとれるようになりました。" },

    { pat:"〜ようにしています", tipo:"gramatica",
      lectura:"yō ni shite imasu",
      es:"procuro…",
      formula:"forma diccionario o forma ない + ようにしています",
      uso:"El esfuerzo consciente: procuro hablar en inglés sin cortarme, procuro mirar el cuaderno de kanji. Un hábito, no una capacidad.",
      ejemplo:"できるだけ漢字のノートを見るようにして（い）ます。" },

    { pat:"〜し、〜し", tipo:"gramatica",
      lectura:"shi, shi",
      es:"…, y además…",
      formula:"forma simple + し、+ forma simple + し",
      uso:"Sumar razones sin cerrar la lista: se aprende lengua hablada, y además es divertido, así que le echo horas.",
      ejemplo:"話しことばが勉強できるし、楽しいので、何時間もやります。" },

    { pat:"〜たり〜たりしていると", tipo:"gramatica",
      lectura:"tari ~ tari shite iru to",
      es:"a base de… y de…",
      formula:"forma たり + forma たり + していると、+ lo que pasa",
      uso:"De tanto ver y leer, las palabras se pegan solas. El と aquí es «cuando / si se hace eso», y la consecuencia sigue.",
      ejemplo:"何回も見たり読んだりしていると、自然にことばをおぼえます。" },

    { pat:"〜てしまいました", tipo:"gramatica",
      lectura:"te shimaimashita",
      es:"acabé por…, terminé…",
      formula:"forma て + しまいました",
      uso:"Algo que pasó del todo y con lamento: dejé el francés porque el trabajo se puso serio. Lleva el «y ya está» que el pasado normal no tiene.",
      ejemplo:"じつは、私も前はフランス語を習っていましたが、仕事が忙しくなってやめてしまいました。" },

    { pat:"〜たくなりました", tipo:"gramatica",
      lectura:"taku narimashita",
      es:"me entraron ganas de…",
      formula:"raíz de ます + たくなりました",
      uso:"El deseo que aparece por algo que se vio: al ver a la gente de la academia, me entraron ganas de volver a empezar.",
      ejemplo:"こちらで、語学学校に通う人たちを見て、もう一度始めたくなりました。" },

    { pat:"〜てもう〜になります", tipo:"gramatica",
      lectura:"te mō ~ ni narimasu",
      es:"llevo ya…",
      formula:"forma て + もう + tiempo + になります",
      uso:"Cuánto se lleva en un sitio o haciendo algo: llevo ya medio año aquí, llevo ya un año en la academia.",
      ejemplo:"早いもので、こちらに来てもう半年になります。" },

    { pat:"上手になりましたね", tipo:"expresion",
      lectura:"じょうずになりましたね · jōzu ni narimashita ne",
      es:"cuánto has mejorado",
      formula:"〜、上手ですね／上手になりましたね。 Se responde いいえ、そんなこと、ないです。まだまだです。",
      uso:"El elogio y su respuesta. En japonés el elogio se rebaja: «qué va, todavía me falta mucho». Aceptarlo con ありがとう es la otra opción, más moderna.",
      ejemplo:"エスターさん、日本語、上手ですね。—— いいえ。そんなこと、ないです。まだまだです。" },

    { pat:"何かいい方法、ありませんか", tipo:"expresion",
      lectura:"なにかいいほうほう、ありませんか · nanika ii hōhō, arimasen ka",
      es:"¿tienes algún buen método?",
      formula:"私も〜たいんですが、何かいい + sustantivo + 、ありませんか。",
      uso:"Pedir consejo: yo también quiero mejorar, ¿conoces alguna buena manera? Primero se dice el deseo propio, luego se pregunta.",
      ejemplo:"私も上手になりたいんですが、何かいい勉強方法、ありませんか。" },

    { pat:"私もやってみます", tipo:"expresion",
      lectura:"わたしもやってみます · watashi mo yatte mimasu",
      es:"yo también lo voy a probar",
      formula:"私も + forma て + みます",
      uso:"Lo que se contesta a un consejo: lo probaré. 〜てみる es «intentar, probar a».",
      ejemplo:"私もやってみます。" },

    { pat:"勉強になります", tipo:"expresion",
      lectura:"べんきょうになります · benkyō ni narimasu",
      es:"se aprende mucho",
      formula:"lo que enseña + は／が + 勉強になります",
      uso:"Algo de lo que se saca provecho: oír opiniones distintas a la mía me enseña. No es «estudiar», es «aprender de».",
      ejemplo:"うん。自分とはちがう意見が聞けて、勉強になるよ。" },

    { pat:"〜を見習わなきゃ", tipo:"expresion",
      lectura:"〜をみならわなきゃ · o minarawanakya",
      es:"tengo que tomar ejemplo de…",
      formula:"persona + を見習わなきゃ（いけない）",
      uso:"Tomar a alguien como modelo. 見習う es «aprender mirando»; con なきゃ, «debería».",
      ejemplo:"田中くんも、エスターさんを見習わなきゃ。" },

    { pat:"〜が一番の楽しみです", tipo:"expresion",
      lectura:"〜がいちばんのたのしみです · ga ichiban no tanoshimi desu",
      es:"lo que más me gusta es…",
      formula:"forma diccionario + のが + 一番の楽しみです",
      uso:"Decir qué es lo que más se disfruta de algo: poder conocer a gente con mis mismas aficiones.",
      ejemplo:"私は日本語クラスで同じしゅみの人に会えるのが、一番の楽しみです。" },

    { pat:"いこうけい", tipo:"gramatica",
      lectura:"いこうけい · ikōkei",
      es:"la forma volitiva",
      formula:"grupo 1: última sílaba a la fila お + う (いきます → いこう, はいります → はいろう); grupo 2: quita ます + よう (たべよう, はじめよう); する → しよう",
      uso:"La tabla de p71. Es el «vamos a», «voy a» en llano, y la base de 〜ようと思っています.",
      ejemplo:"いきます → いこう。はいります → はいろう。たべます → たべよう。します → しよう。" }
  ],

  verbos: [
    { kana:"まなぶ", kanji:"学ぶ", g:1, es:"aprender, estudiar", c:1 },
    { kana:"ならう", kanji:"習う", g:1, es:"aprender (con profesor)", c:1 },
    { kana:"かよう", kanji:"通う", g:1, es:"ir regularmente a, asistir", c:2 },
    { kana:"ききとる", kanji:"聞きとる", g:1, es:"entender al oír", c:1 },
    { kana:"つづく", kanji:"続く", g:1, es:"continuar, seguir", c:1 },
    { kana:"まちがう", kanji:"まちがう", g:1, es:"equivocarse", c:1 },
    { kana:"みならう", kanji:"見習う", g:1, es:"tomar ejemplo de", c:1 },
    { kana:"やすむ", kanji:"休む", g:1, es:"descansar, faltar", c:2 },
    { kana:"はずかしがる", kanji:"はずかしがる", g:1, es:"cortarse, sentir vergüenza", c:1 },
    { kana:"うける", kanji:"受ける", g:2, es:"presentarse a (un examen)", c:1 },
    { kana:"ためる", kanji:"ためる", g:2, es:"ahorrar, acumular", c:2 },
    { kana:"つうじる", kanji:"通じる", g:2, es:"hacerse entender", c:1, nota:"Grupo 2, aunque termine en 〜じる" },
    { kana:"はじめる", kanji:"始める", g:2, es:"empezar (algo)", c:2 },
    { kana:"みかける", kanji:"見かける", g:2, es:"ver por ahí, cruzarse con", c:2 },
    { kana:"つづける", kanji:"続ける", g:2, es:"continuar (algo)", c:1 },
    { kana:"さんかする", kanji:"参加する", g:3, es:"participar", c:1 },
    { kana:"たいしょくする", kanji:"退職する", g:3, es:"jubilarse, dejar la empresa", c:1 },
    { kana:"ひかくする", kanji:"ひかくする", g:3, es:"comparar", c:1 },
    { kana:"らくだいする", kanji:"らくだいする", g:3, es:"suspender", c:2 },
    { kana:"チャットする", kanji:"チャットする", g:3, es:"chatear", c:2 }
  ],

  vocab: [
    /* estudiar un idioma (p65, p66) */
    { jp:"外国語", kana:"がいこくご", es:"idioma extranjero", c:1, cat:"estudio" },
    { jp:"母語", kana:"ぼご", es:"lengua materna", c:1, cat:"estudio" },
    { jp:"日本語", kana:"にほんご", es:"japonés (idioma)", c:1, cat:"estudio" },
    { jp:"フランス語", kana:"フランスご", es:"francés (idioma)", c:2, cat:"estudio" },
    { jp:"会話", kana:"かいわ", es:"conversación", c:1, cat:"estudio" },
    { jp:"文法", kana:"ぶんぽう", es:"gramática", c:1, cat:"estudio" },
    { jp:"漢字", kana:"かんじ", es:"kanji", c:1, cat:"estudio" },
    { jp:"たんご", kana:"たんご", es:"vocabulario, palabra", c:2, cat:"estudio" },
    { jp:"話しことば", kana:"はなしことば", es:"lengua hablada", c:2, cat:"estudio" },
    { jp:"教科書", kana:"きょうかしょ", es:"libro de texto", c:2, cat:"estudio" },
    { jp:"ノート", kana:"ノート", es:"cuaderno", c:1, cat:"objetos" },
    { jp:"方法", kana:"ほうほう", es:"método, manera", c:1, cat:"estudio" },
    { jp:"勉強方法", kana:"べんきょうほうほう", es:"método de estudio", c:1, cat:"estudio" },
    { jp:"目的", kana:"もくてき", es:"objetivo, propósito", c:1, cat:"estudio" },
    { jp:"計画", kana:"けいかく", es:"plan", c:2, cat:"estudio" },
    { jp:"自信", kana:"じしん", es:"confianza en uno mismo", c:1, cat:"estudio" },
    { jp:"試験", kana:"しけん", es:"examen", c:2, cat:"estudio" },
    { jp:"成績", kana:"せいせき", es:"nota, resultado", c:2, cat:"estudio" },
    { jp:"しめきり", kana:"しめきり", es:"fecha límite", c:2, cat:"estudio" },
    { jp:"コース", kana:"コース", es:"curso", c:2, cat:"estudio" },
    { jp:"クラス", kana:"クラス", es:"clase (grupo)", c:1, cat:"estudio" },
    { jp:"初級", kana:"しょきゅう", es:"nivel inicial", c:2, cat:"estudio" },
    { jp:"中級", kana:"ちゅうきゅう", es:"nivel intermedio", c:2, cat:"estudio" },
    { jp:"上級", kana:"じょうきゅう", es:"nivel avanzado", c:2, cat:"estudio" },
    { jp:"〜級", kana:"〜きゅう", es:"nivel (初級, 中級, 上級)", c:2, cat:"estudio" },
    { jp:"語学学校", kana:"ごがくがっこう", es:"academia de idiomas", c:2, cat:"lugar" },
    { jp:"受講料", kana:"じゅこうりょう", es:"matrícula, cuota del curso", c:2, cat:"estudio" },
    { jp:"大学", kana:"だいがく", es:"universidad", c:2, cat:"lugar" },
    { jp:"本屋", kana:"ほんや", es:"librería", c:1, cat:"lugar" },
    { jp:"カフェ", kana:"カフェ", es:"cafetería", c:2, cat:"lugar" },
    { jp:"チャット", kana:"チャット", es:"chat", c:2, cat:"objetos" },
    { jp:"ニュース", kana:"ニュース", es:"noticias", c:1, cat:"objetos" },
    { jp:"アニメ", kana:"アニメ", es:"anime", c:1, cat:"objetos" },
    { jp:"マンガ", kana:"マンガ", es:"manga", c:2, cat:"objetos" },
    { jp:"小説", kana:"しょうせつ", es:"novela", c:2, cat:"objetos" },
    { jp:"手紙", kana:"てがみ", es:"carta", c:2, cat:"objetos" },
    { jp:"情報", kana:"じょうほう", es:"información", c:1, cat:"abstracto" },
    { jp:"意見", kana:"いけん", es:"opinión", c:1, cat:"abstracto" },
    { jp:"関係", kana:"かんけい", es:"relación", c:1, cat:"abstracto" },
    { jp:"しょうらい", kana:"しょうらい", es:"el futuro (de uno)", c:2, cat:"tiempo" },
    { jp:"とちゅう", kana:"とちゅう", es:"a medias, a medio camino", c:2, cat:"tiempo" },
    { jp:"ひさしぶり", kana:"ひさしぶり", es:"cuánto tiempo", c:2, cat:"reaccion" },

    /* la gente de la clase (p68, p69) */
    { jp:"先生", kana:"せんせい", es:"profesor", c:2, cat:"persona" },
    { jp:"せんぱい", kana:"せんぱい", es:"veterano, compañero mayor", c:1, cat:"persona" },
    { jp:"こうはい", kana:"こうはい", es:"compañero más nuevo", c:1, cat:"persona" },
    { jp:"会社員", kana:"かいしゃいん", es:"empleado de empresa", c:1, cat:"persona" },
    { jp:"芸術家", kana:"げいじゅつか", es:"artista", c:1, cat:"persona" },
    { jp:"外国人", kana:"がいこくじん", es:"extranjero (persona)", c:2, cat:"persona" },
    { jp:"ボランティア", kana:"ボランティア", es:"voluntariado", c:2, cat:"trabajo" },
    { jp:"はずかしがりや", kana:"はずかしがりや", es:"persona tímida", c:1, cat:"persona" },
    { jp:"話し好き", kana:"はなしずき", es:"hablador", c:1, cat:"cualidad" },

    /* como es (p65, p66, p70) */
    { jp:"難しい", kana:"むずかしい", es:"difícil", c:2, cat:"cualidad" },
    { jp:"正しい", kana:"ただしい", es:"correcto", c:1, cat:"cualidad" },
    { jp:"楽しい", kana:"たのしい", es:"divertido, agradable", c:1, cat:"cualidad" },
    { jp:"はやい", kana:"はやい", es:"rápido", c:1, cat:"cualidad" },
    { jp:"同じ", kana:"おなじ", es:"igual, el mismo", c:1, cat:"cualidad" },
    { jp:"せっきょく的", kana:"せっきょくてき", es:"activo, con iniciativa", c:1, cat:"cualidad" },
    { jp:"自然", kana:"しぜん", es:"natural, sin darse cuenta", c:2, cat:"cualidad" },
    { jp:"大切", kana:"たいせつ", es:"importante", c:1, cat:"cualidad" },
    { jp:"ふしぎ", kana:"ふしぎ", es:"raro, curioso", c:2, cat:"cualidad" },
    { jp:"うらやましい", kana:"うらやましい", es:"qué envidia", c:1, cat:"sentimiento" },
    { jp:"まだまだ", kana:"まだまだ", es:"todavía me falta mucho", c:1, cat:"reaccion" },
    { jp:"ぜったい", kana:"ぜったい", es:"sin falta, de ninguna manera", c:2, cat:"conector" },
    { jp:"どうやって", kana:"どうやって", es:"¿cómo?, ¿de qué manera?", c:1, cat:"conector" },
    { jp:"うん", kana:"うん", es:"sí (informal)", c:1, cat:"reaccion" }
  ],

  frases: [
    { k:"f5-01", es:"Procuro hablar en inglés con iniciativa.", c:1, pat:"〜ように",
      ok:["せっきょく的に英語を話すようにして（い）ます。","せっきょく的に英語を話すようにしています。","せっきょくてきにえいごをはなすようにしています。"] },
    { k:"f5-02", es:"Como escuché mucho los CD, he llegado a entender las conversaciones rápidas.", c:1, pat:"〜ようになりました",
      ok:["CDをよく聞いたので、はやい会話が聞きとれるようになりました。","CDをよくきいたので、はやいかいわがききとれるようになりました。"] },
    { k:"f5-03", es:"Procuro, en lo posible, mirar el cuaderno de kanji.", c:1, pat:"〜ようにしています",
      ok:["できるだけ漢字のノートを見るようにして（い）ます。","できるだけ漢字のノートを見るようにしています。","できるだけかんじのノートをみるようにしています。"] },
    { k:"f5-04", es:"La academia de japonés, sigues yendo, ¿no? — La de inglés, sigues yendo, ¿eh?", c:1, pat:"ていねいたい・ふつうたい２",
      ok:["日本語の学校、続いてますね。英語の学校、続いてるね。","にほんごのがっこう、つづいてますね。えいごのがっこう、つづいてるね。"] },
    { k:"f5-05", es:"Cuando me gradúe, tengo pensado irme a estudiar a Japón.", c:2, pat:"〜（よ）うと思っています",
      ok:["大学を卒業したら、日本に留学しようと思っています。","だいがくをそつぎょうしたら、にほんにりゅうがくしようとおもっています。"] },
    { k:"f5-06", es:"En el próximo examen parece que sacaré buena nota.", c:2, pat:"〜そうです（様態）",
      ok:["つぎの試験は、いいせいせきがとれそうです。","つぎのしけんは、いいせいせきがとれそうです。"] },
    { k:"f5-07", es:"Un libro que hasta yo parezco capaz de leer.", c:2, pat:"〜そうです（様態）",
      ok:["私にも読めそうな本","わたしにもよめそうなほん","私にも読めそうな本。"] },
    { k:"f5-08", es:"Chateo cada día una media hora, pero ayer fueron tres horas nada menos.", c:2, pat:"（数量）も",
      ok:["毎日30分ぐらいチャットをしますが、きのうは3時間もしました。","まいにち30ぷんぐらいチャットをしますが、きのうは3じかんもしました。"] },
    { k:"f5-09", es:"En esta escuela hay muchísimos profesores extranjeros. Los cursos son solo tres. En el avanzado no hay más que cuatro alumnos.", c:2, pat:"も・だけ・しか",
      ok:["この学校には、外国人の先生が何人もいます。日本語のコースは、初級、中級、上級の3つだけです。上級コースは難しいので、学生が4人しかいません。","このがっこうには、がいこくじんのせんせいがなんにんもいます。にほんごのコースは、しょきゅう、ちゅうきゅう、じょうきゅうの3つだけです。じょうきゅうコースはむずかしいので、がくせいが4にんしかいません。"] },
    { k:"f5-10", es:"Se aprende lengua hablada, y además es divertido, así que le echo horas y horas.", c:2, pat:"〜し、〜し",
      ok:["話しことばが勉強できるし、楽しいので、何時間もやります。","はなしことばがべんきょうできるし、たのしいので、なんじかんもやります。"] },
    { k:"f5-11", es:"A base de verlo y leerlo muchas veces, las palabras se aprenden solas.", c:2, pat:"〜たり〜たりしていると",
      ok:["何回も見たり読んだりしていると、自然にことばをおぼえます。","なんかいもみたりよんだりしていると、しぜんにことばをおぼえます。"] },
    { k:"f5-12", es:"La verdad es que yo también estudiaba francés, pero el trabajo se puso serio y lo dejé.", c:2, pat:"〜てしまいました",
      ok:["じつは、私も前はフランス語を習っていましたが、仕事が忙しくなってやめてしまいました。","じつは、わたしもまえはフランスごをならっていましたが、しごとがいそがしくなってやめてしまいました。"] },
    { k:"f5-13", es:"Aquí, al ver a la gente que va a la academia, me entraron ganas de volver a empezar.", c:2, pat:"〜たくなりました",
      ok:["こちらで、語学学校に通う人たちを見て、もう一度始めたくなりました。","こちらで、ごがくがっこうにかようひとたちをみて、もういちどはじめたくなりました。"] },
    { k:"f5-14", es:"El tiempo vuela: llevo ya medio año aquí.", c:2, pat:"〜てもう〜になります",
      ok:["早いもので、こちらに来てもう半年になります。","はやいもので、こちらにきてもうはんとしになります。"] },
    { k:"f5-15", es:"Esther, qué bien hablas japonés. — Qué va. Todavía me falta mucho.", c:1, pat:"上手になりましたね",
      ok:["エスターさん、日本語、上手ですね。—— いいえ。そんなこと、ないです。まだまだです。","エスターさん、日本語、上手ですね。いいえ。そんなこと、ないです。まだまだです。","エスターさん、にほんご、じょうずですね。いいえ。そんなこと、ないです。まだまだです。"] },
    { k:"f5-16", es:"Yo también quiero mejorar. ¿Conoces algún buen método?", c:1, pat:"何かいい方法、ありませんか",
      ok:["私も上手になりたいんですが、何かいい勉強方法、ありませんか。","わたしもじょうずになりたいんですが、なにかいいべんきょうほうほう、ありませんか。"] },
    { k:"f5-17", es:"Yo también lo voy a probar.", c:1, pat:"私もやってみます",
      ok:["私もやってみます。","わたしもやってみます。"] },
    { k:"f5-18", es:"Sí. Se aprende mucho oyendo opiniones distintas a la tuya.", c:1, pat:"勉強になります",
      ok:["うん。自分とはちがう意見が聞けて、勉強になるよ。","うん。じぶんとはちがういけんがきけて、べんきょうになるよ。"] },
    { k:"f5-19", es:"Tanaka, tú también deberías tomar ejemplo de Esther.", c:1, pat:"〜を見習わなきゃ",
      ok:["田中くんも、エスターさんを見習わなきゃ。","たなかくんも、エスターさんをみならわなきゃ。"] },
    { k:"f5-20", es:"Lo que más me gusta de la clase de japonés es poder conocer a gente con mis mismas aficiones.", c:1, pat:"〜が一番の楽しみです",
      ok:["私は日本語クラスで同じしゅみの人に会えるのが、一番の楽しみです。","わたしはにほんごクラスでおなじしゅみのひとにあえるのが、いちばんのたのしみです。"] },
    { k:"f5-21", es:"いきます → いこう, はいります → はいろう, たべます → たべよう, します → しよう.", c:2, pat:"いこうけい",
      ok:["いきます → いこう。はいります → はいろう。たべます → たべよう。します → しよう。"] }
  ],

  huecos: [
    /* p65, ejercicio 2 */
    { k:"h5-01", pat:"〜ようになりました", pre:"CDをよく聞いたので、はやい会話が（", post:"）ようになりました。", hint:"entender al oír, potencial", ok:["聞きとれる","ききとれる"], c:1, es:"Como escuché mucho los CD, he llegado a entender las conversaciones rápidas." },
    { k:"h5-02", pat:"〜ように", pre:"いっしょに学ぶ友だちがいるので、日本語の勉強が（", post:"）。", hint:"つづきます → 〜ています", ok:["つづいています","続いています"], c:1, es:"Como tengo amigos con los que estudiar, sigo con el japonés." },
    { k:"h5-03", pat:"〜ようにしています", pre:"文法は、ほかの外国語や母語と（", post:"）考えるようにしています。", hint:"ひかくします → forma て", ok:["ひかくして"], c:1, es:"La gramática procuro pensarla comparándola con otros idiomas y con mi lengua materna." },
    { k:"h5-04", pat:"〜ように", pre:"はずかしがらないで、（", post:"）話すことがたいせつです。", hint:"con iniciativa (adverbio)", ok:["せっきょく的に","せっきょくてきに"], c:1, es:"Es importante hablar con iniciativa, sin cortarse." },
    { k:"h5-05", pat:"〜ように", pre:"日本人と話して、自分の日本語が（", post:"）と、自信がつきます。", hint:"hacerse entender → forma diccionario", ok:["通じる","つうじる"], c:1, es:"Al hablar con japoneses y ver que mi japonés se entiende, gano confianza." },
    /* p66, 文2 */
    { k:"h5-06", pat:"〜ようになりました", pre:"はやい会話も（", post:"）ようになりました。", hint:"聞きとれます → forma simple", ok:["聞きとれる","ききとれる"], c:1, es:"He llegado a entender también las conversaciones rápidas." },
    { k:"h5-07", pat:"〜ようにしています", pre:"できるだけ漢字のノートを（", post:"）ようにして（い）ます。", hint:"見ます → forma simple", ok:["見る","みる"], c:1, es:"Procuro mirar el cuaderno de kanji todo lo que puedo." },
    { k:"h5-08", pat:"〜ように", pre:"漢字を（", post:"）ように、ノートをいつも持って（い）ます。", hint:"わすれません → forma ない", ok:["わすれない","忘れない"], c:1, es:"Para no olvidar los kanji, llevo siempre el cuaderno." },
    /* p68-69, 文2: a quien se habla */
    { k:"h5-09", pat:"ていねいたい・ふつうたい２", pre:"英語の学校、つづいてるね。 さいとう → （", post:"）", hint:"llano: a su こうはい", ok:["たなか","田中","田中くん"], c:1, es:"«La de inglés, sigues yendo, ¿eh?» ¿A quién?" },
    { k:"h5-10", pat:"ていねいたい・ふつうたい２", pre:"ええ、もう1年です。 田中 → （", post:"）", hint:"cortés: a su せんぱい", ok:["さいとう","さいとうさん"], c:1, es:"«Sí, ya un año.» ¿A quién?" },
    { k:"h5-11", pat:"ていねいたい・ふつうたい２", pre:"げいじゅつかもいるよ。 田中 → （", post:"）", hint:"llano: a su amiga", ok:["エスター","エスターさん"], c:1, es:"«También hay artistas.» ¿A quién?" },
    { k:"h5-12", pat:"ていねいたい・ふつうたい２", pre:"うん。自分とはちがういけんが聞けて、勉強になるよ。 田中 → （", post:"）", hint:"llano", ok:["エスター","エスターさん"], c:1, es:"«Sí. Se aprende oyendo otras opiniones.» ¿A quién?" },
    { k:"h5-13", pat:"ていねいたい・ふつうたい２", pre:"日本語の学校、つづいてますね。 さいとう → （", post:"）", hint:"cortés: no es su こうはい", ok:["エスター","エスターさん"], c:1, es:"«La academia de japonés, sigues yendo, ¿no?» ¿A quién?" },
    { k:"h5-14", pat:"ていねいたい・ふつうたい２", pre:"エスターさんを見習わなきゃ。 さいとう → （", post:"）", hint:"llano", ok:["たなか","田中","田中くん"], c:1, es:"«Deberías tomar ejemplo de Esther.» ¿A quién?" },
    /* p71, 文2 */
    { k:"h5-15", pat:"〜（よ）うと思っています", pre:"タイ語の手紙をほんやくするボランティアを（", post:"）。", hint:"します → 〜ようと思っています", ok:["しようと思っています","しようとおもっています"], c:2, es:"Tengo pensado hacer de voluntario traduciendo cartas en tailandés." },
    { k:"h5-16", pat:"〜（よ）うと思っています", pre:"アニメをつくる会社に（", post:"）。", hint:"入ります → 〜ろうと思っています", ok:["入ろうと思っています","はいろうとおもっています","はいろうと思っています"], c:2, es:"Tengo pensado entrar en una empresa que hace anime." },
    { k:"h5-17", pat:"〜（よ）うと思っています", pre:"スペインにフラメンコを（", post:"）。", hint:"習いに行きます → 〜こうと思っています", ok:["習いに行こうと思っています","ならいにいこうとおもっています","ならいに行こうと思っています"], c:2, es:"Tengo pensado ir a España a aprender flamenco." },
    { k:"h5-18", pat:"〜（よ）うと思っています", pre:"日本料理の店を（", post:"）。", hint:"始めます → 〜ようと思っています", ok:["始めようと思っています","はじめようとおもっています","はじめようと思っています"], c:2, es:"Tengo pensado abrir un restaurante japonés." },
    /* p72, 文3 */
    { k:"h5-19", pat:"〜そうです（様態）", pre:"これなら難しくないから、私にも（", post:"）。", hint:"読めます → 〜そうです", ok:["読めそうです","よめそうです"], c:2, es:"Este no es difícil, así que hasta yo parezco capaz de leerlo." },
    { k:"h5-20", pat:"〜そうです（様態）", pre:"そうですか。1日に5つなら、（", post:"）。", hint:"おぼえられます → 〜そうです", ok:["おぼえられそうです"], c:2, es:"Ah. Cinco al día parece que sí podré aprenderlos." },
    { k:"h5-21", pat:"〜そうです（様態）", pre:"シンさんにいい本を貸してもらったので、今日中に（", post:"）。", hint:"できます → 〜そうです", ok:["できそうです"], c:2, es:"Shin me prestó un buen libro, así que parece que lo acabaré hoy." },
    { k:"h5-22", pat:"〜そうです（様態）", pre:"来週、試験があるんです。試験に（", post:"）漢字を教えてください。", hint:"出ます → 〜そうな", ok:["出そうな","でそうな"], c:2, es:"La semana que viene tengo examen. Enséñame los kanji que parece que van a salir." },
    { k:"h5-23", pat:"〜そうです（様態）", pre:"すみません。今日はもう時間、ないんです。英語の学校に（", post:"）。", hint:"おくれます → 〜そうです", ok:["おくれそうです"], c:2, es:"Perdona, hoy ya no tengo tiempo. Parece que llego tarde a la academia de inglés." },
    /* p72, 文4 */
    { k:"h5-24", pat:"も・だけ・しか", pre:"この学校には、外国人の先生が何人（", post:"）います。", hint:"muchísimos", ok:["も"], c:2, es:"En esta escuela hay muchísimos profesores extranjeros." },
    { k:"h5-25", pat:"も・だけ・しか", pre:"この学校は、文化イベントが年に何回（", post:"）あるので、楽しみです。", hint:"muchas veces", ok:["も"], c:2, es:"En esta escuela hay un montón de eventos culturales al año, y lo espero con ganas." },
    { k:"h5-26", pat:"も・だけ・しか", pre:"日本語のコースは、初級、中級、上級の3つ（", post:"）です。", hint:"solo (neutro)", ok:["だけ"], c:2, es:"Los cursos de japonés son solo tres: inicial, intermedio y avanzado." },
    { k:"h5-27", pat:"も・だけ・しか", pre:"上級コースは難しいので、学生が4人（", post:"）いません。", hint:"solo, y es poco (con negativo)", ok:["しか"], c:2, es:"El curso avanzado es difícil, así que no hay más que cuatro alumnos." },
    { k:"h5-28", pat:"も・だけ・しか", pre:"この学校の受講料は、48,000円（", post:"）するので、私はぜったい休みません。", hint:"nada menos que", ok:["も"], c:2, es:"La matrícula cuesta 48.000 yenes nada menos, así que no falto ni un día." },
    /* dialogos y textos */
    { k:"h5-29", pat:"上手になりましたね", pre:"エスターさん、日本語、上手ですね。—— いいえ。そんなこと、ないです。（", post:"）。", hint:"«todavía me falta mucho»", ok:["まだまだです"], c:1, es:"Esther, qué bien hablas japonés. — Qué va. Todavía me falta mucho." },
    { k:"h5-30", pat:"何かいい方法、ありませんか", pre:"私も上手になりたいんですが、何かいい勉強方法、（", post:"）。", hint:"¿no hay…?", ok:["ありませんか"], c:1, es:"Yo también quiero mejorar. ¿Conoces algún buen método?" },
    { k:"h5-31", pat:"〜が一番の楽しみです", pre:"私は日本語クラスで同じしゅみの人に（", post:"）のが、一番の楽しみです。", hint:"会います → potencial", ok:["会える","あえる"], c:1, es:"Lo que más me gusta de la clase es poder conocer a gente con mis mismas aficiones." },
    { k:"h5-32", pat:"〜し、〜し", pre:"話しことばが（", post:"）し、楽しいので、何時間もやります。", hint:"勉強できます → forma simple", ok:["勉強できる","べんきょうできる"], c:2, es:"Se aprende lengua hablada, y además es divertido, así que le echo horas." },
    { k:"h5-33", pat:"〜てしまいました", pre:"仕事が忙しくなって（", post:"）。", hint:"やめます → 〜てしまいました", ok:["やめてしまいました"], c:2, es:"El trabajo se puso serio y acabé dejándolo." },
    { k:"h5-34", pat:"〜たくなりました", pre:"語学学校に通う人たちを見て、もう一度（", post:"）。", hint:"始めます → 〜たくなりました", ok:["始めたくなりました","はじめたくなりました"], c:2, es:"Al ver a la gente que va a la academia, me entraron ganas de volver a empezar." }
  ],

  armar: [
    { k:"a5-01", es:"Procuro hablar en inglés con iniciativa.", c:1, chips:["せっきょく的に","英語を","話すように","しています"] },
    { k:"a5-02", es:"Como escuché mucho los CD, he llegado a entender las conversaciones rápidas.", c:1, chips:["CDをよく聞いたので、","はやい会話が","聞きとれる","ようになりました"] },
    { k:"a5-03", es:"Para poder llegar a hablar bien, veo las noticias en inglés cada día.", c:1, chips:["上手になれるように、","毎日","英語のニュースを","見ています"] },
    { k:"a5-04", es:"Esther, qué bien hablas japonés. — Qué va. Todavía me falta mucho.", c:1, chips:["エスターさん、日本語、上手ですね。","いいえ。","そんなこと、ないです。","まだまだです"] },
    { k:"a5-05", es:"Yo también quiero mejorar. ¿Conoces algún buen método?", c:1, chips:["私も","上手になりたいんですが、","何かいい勉強方法、","ありませんか"] },
    { k:"a5-06", es:"Se aprende mucho oyendo opiniones distintas a la tuya.", c:1, chips:["自分とは","ちがう意見が","聞けて、","勉強になるよ"] },
    { k:"a5-07", es:"Lo que más me gusta de la clase es poder conocer a gente con mis mismas aficiones.", c:1, chips:["私は日本語クラスで","同じしゅみの人に","会えるのが、","一番の楽しみです"] },
    { k:"a5-08", es:"Tanaka, tú también deberías tomar ejemplo de Esther.", c:1, chips:["田中くんも、","エスターさんを","見習わ","なきゃ"] },
    { k:"a5-09", es:"Cuando me gradúe, tengo pensado irme a estudiar a Japón.", c:2, chips:["大学を","卒業したら、","日本に","留学しようと思っています"] },
    { k:"a5-10", es:"En el próximo examen parece que sacaré buena nota.", c:2, chips:["つぎの試験は、","いい","せいせきが","とれそうです"] },
    { k:"a5-11", es:"Chateo cada día una media hora, pero ayer fueron tres horas nada menos.", c:2, chips:["毎日30分ぐらい","チャットをしますが、","きのうは","3時間もしました"] },
    { k:"a5-12", es:"A base de verlo y leerlo muchas veces, las palabras se aprenden solas.", c:2, chips:["何回も","見たり読んだりしていると、","自然に","ことばをおぼえます"] },
    { k:"a5-13", es:"El trabajo se puso serio y acabé dejándolo.", c:2, chips:["仕事が","忙しくなって","やめて","しまいました"] },
    { k:"a5-14", es:"El mes que viene tengo pensado apuntarme a un curso de francés.", c:2, chips:["来月、","フランス語の","コースに","入ろうと思っています"] },
    { k:"a5-15", es:"El tiempo vuela: llevo ya medio año aquí.", c:2, chips:["早いもので、","こちらに来て","もう","半年になります"] },
    { k:"a5-16", es:"En el avanzado, como es difícil, no hay más que cuatro alumnos.", c:2, chips:["上級コースは","難しいので、","学生が","4人しかいません"] }
  ]
});
