/* Dojo Marugoto - unidad 6, 結婚
   Marugoto A2/B1 Parte 2 - clase 1 = libro p76-81 - clase 2 = p82-85
   (p74-75 es el test de mitad de curso, entre el tema 5 y este)

   De donde salen los huecos:
     h6-01 a h6-05  p77, ejercicio 2   (お祝い, おみまい, なぐさめる, はげます)
     h6-06 a h6-11  p78, 文2           (〜でしょうね y 〜ようと思うんですが)
     h6-12 a h6-15  p80, 文2           (よ / ね / よね)
     h6-16 a h6-20  p83, 文2 (1)       (〜てあげます)
     h6-21 a h6-25  p83-84, 文2 (2)    (あげる / くれる / もらう)
     h6-26 a h6-29  p84, 文3           (〜なくてもいいです)
     h6-30 a h6-34  los dialogos de p79-81 y los textos de p82 y p85 */

CONTENIDO.unidades.push({
  n: 6,
  titulo: "結婚",
  es: "La boda",
  paginas: { 1: "76-81", 2: "82-85" },
  estado: "lista",

  /* Tres formas nuevas: forma て + あげました (p83), forma ない sin la い +
     くてもいいです (p84) y forma simple + でしょう (p78). La volitiva vuelve
     de la unidad 5: しよう, さそおう, なぐさめよう. */
  formas: {
    1: ["masu", "masen", "nai", "ta", "te", "you", "deshou", "tai"],
    2: ["masu", "nai", "ta", "te", "teageru", "nakutemo", "tekureru", "temorau"]
  },

  patrones: [
    { pat:"〜でしょう（ね）", tipo:"gramatica",
      oficial:"～でしょう",
      lectura:"deshō (ne)",
      es:"seguro que…, supongo que…",
      formula:"forma simple + でしょう（ね）. Sustantivo y adjetivo な pelados: 幸せでしょう. Casi siempre con きっと o たぶん delante",
      uso:"Una suposición sobre el otro, dicha con empatía: seguro que ahora es feliz, en el hospital estará aburrido. El ね busca que el otro asienta.",
      ejemplo:"のりかさんは、今、きっと幸せでしょうね。" },

    { pat:"〜（よ）うと思うんですが", tipo:"gramatica",
      oficial:"～（よ）うと思うんですが",
      lectura:"〜（よ）うとおもうんですが · (y)ō to omou n desu ga",
      es:"estaba pensando en…, ¿qué te parece?",
      formula:"いこうけい + と思うんですが。",
      uso:"Una propuesta abierta a los demás: pensaba hacerle algo de celebración… El が del final deja que el otro se sume (いいですね。そうしましょう).",
      ejemplo:"のりかさんに、何かお祝いをしようと思うんですが。" },

    { pat:"よ／ね／よね", tipo:"gramatica",
      oficial:"～よ／ね／よね",
      lectura:"yo / ne / yo ne",
      es:"las partículas del final",
      formula:"S + よ (te informo) · S + ね (busco que estés de acuerdo) · S + よね (creo que es así, ¿verdad?)",
      uso:"よ entrega algo que el otro no sabe (聞きましたよ); ね pide confirmación de algo que los dos saben (結婚するそうですね); よね afirma con algo de duda y pide que el otro lo ratifique (やさしい人なんですよね).",
      ejemplo:"のりかさん、聞きましたよ。結婚するそうですね。やさしい人なんですよね。" },

    { pat:"〜てあげます", tipo:"gramatica",
      oficial:"～てあげる",
      lectura:"te agemasu",
      es:"hago algo por alguien",
      formula:"（私は）+ persona + に／を + forma て + あげます",
      uso:"El favor que uno hace a otro: celebrarles la boda, ayudarles con los preparativos. Cuidado: dicho directamente a quien lo recibe suena a que se le hace un favor; entre iguales está bien.",
      ejemplo:"（私は）のりかの願いを聞いてあげます。" },

    { pat:"〜なくてもいいです", tipo:"gramatica",
      oficial:"～なくてもいい／だいじょうぶ",
      lectura:"nakutemo ii desu",
      es:"no hace falta…",
      formula:"forma ない sin la い + くてもいいです／だいじょうぶです",
      uso:"Lo que no es obligatorio: no hace falta hacer una gran fiesta, no hace falta llevar sobre con dinero. Lo contrario de 〜なければなりません.",
      ejemplo:"大きなパーティーはしなくてもいいです。" },

    { pat:"あげる・くれる・もらう", tipo:"gramatica",
      lectura:"ageru / kureru / morau",
      es:"dar y recibir, según quién",
      formula:"私 → otro: 〜てあげます · otro → 私: 〜てくれます · 私 ← otro (yo lo pido o recibo): 〜てもらいます",
      uso:"Los tres verbos del favor. El ejercicio de p83-84 pide elegir: ジョージ vino a verme al hospital → くれました; yo le enseñé a bailar → あげました; me ayudó con el informe → てつだってもらいました.",
      ejemplo:"入院したとき、ジョージは毎日おみまいに来てくれました。ジョージにダンスを教えてあげました。" },

    { pat:"〜そうですね（伝聞）", tipo:"gramatica",
      lectura:"〜そうですね（でんぶん）· sō desu ne",
      es:"me han dicho que…, ¿no?",
      formula:"forma simple + そうですね. Sustantivo: 〜だそうです",
      uso:"Confirmar con la persona un rumor que se oyó: he oído que te casas. Es el «dicen que» de la unidad 8 usado para verificar.",
      ejemplo:"のりかさん、結婚するそうですよ。—— 日本祭で知り合った人だそうです。" },

    { pat:"〜まで／〜までに", tipo:"gramatica",
      lectura:"made / made ni",
      es:"hasta… / antes de…",
      formula:"結婚するまでに + lo que pasa antes",
      uso:"Lo que ocurre antes de un momento: hasta casarse, se conocen, salen juntos, hay una pedida… La secuencia del ejercicio 3 de p77.",
      ejemplo:"結婚するまでに、どんなことがありますか。知り合う → つき合う → プロポーズする → 結婚式をする → いっしょにくらす。" },

    { pat:"〜ば、じゅうぶんです", tipo:"gramatica",
      lectura:"ba, jūbun desu",
      es:"con… basta",
      formula:"forma ば + じゅうぶんです",
      uso:"Lo mínimo que hace falta: con celebrarlo con la familia y los amigos íntimos basta. じゅうぶん es «suficiente».",
      ejemplo:"家族やしたしい友だちとお祝いすればじゅうぶんです。" },

    { pat:"〜より〜方がいい", tipo:"gramatica",
      lectura:"yori ~ hō ga ii",
      es:"mejor… que…",
      formula:"A + より + B + 方がいい（と思います）",
      uso:"La comparación de la unidad 9, aquí en la opinión de ジョージ: mejor gastar el dinero en la vida nueva que en la boda.",
      ejemplo:"お金は結婚式やパーティーよりふたりの新しい生活のために使った方がいいと思います。" },

    { pat:"〜にとって〜がだいじなら", tipo:"gramatica",
      lectura:"ni totte ~ ga daiji nara",
      es:"si para… es importante…",
      formula:"persona + にとって + cosa + がだいじなら、+ lo que se acepta",
      uso:"Ceder a lo que importa al otro: si para Norika una gran boda es importante, adelante. にとって fija el punto de vista, なら la condición.",
      ejemplo:"でも、のりかにとって大きな結婚式をすることがだいじなら、それでもいいです。" },

    { pat:"〜によると", tipo:"gramatica",
      lectura:"ni yoru to",
      es:"según…",
      formula:"fuente + によると、+ lo que dice",
      uso:"Citar de dónde sale un dato: según una encuesta reciente, la forma más común de conocer a la pareja es en el trabajo.",
      ejemplo:"最近のアンケートによると、結婚相手と知り合ったきっかけで一番多いのは、職場での出会いです。" },

    { pat:"きっかけ", tipo:"expresion",
      lectura:"kikkake",
      es:"la ocasión, cómo empezó",
      formula:"〜と知り合ったきっかけは + circunstancia",
      uso:"Cómo se conocieron: en el trabajo, por un amigo, en la escuela, por internet. きっかけ es el detonante de algo.",
      ejemplo:"結婚相手と知り合ったきっかけで一番多いのは、職場での出会いです。つぎに多いのは、友だちの紹介、そして学校での出会いです。" },

    { pat:"おめでとうございます", tipo:"expresion",
      lectura:"omedetō gozaimasu",
      es:"enhorabuena",
      formula:"〜さん、ご結婚おめでとうございます。 · おめでとうございます。よかったですね。",
      uso:"La felicitación. Con ご delante del sustantivo (ご結婚, ご婚約) es más formal; entre amigos, おめでとう a secas.",
      ejemplo:"のりかさん、ジョージさん、ご結婚おめでとうございます。" },

    { pat:"結婚式のスピーチ", tipo:"expresion",
      lectura:"けっこんしきのスピーチ · kekkonshiki no supīchi",
      es:"el discurso de boda",
      formula:"1 ご結婚おめでとうございます · 2 私は〜ともうします · 3 la novia es… · 4 ふたりの家庭は、きっと〜になると思います · 5 すえながいお幸せをおいのりしています",
      uso:"La plantilla de p81. Quién soy, cómo es la persona que se casa, qué les deseo. La fórmula del cierre, «les deseo una larga felicidad», se dice entera.",
      ejemplo:"私は、のりかさんと同じ会社に勤めているパウロともうします。ふたりの家庭は、きっと明るくて、あたたかい家庭になると思います。すえながいお幸せをおいのりしています。" },

    { pat:"ほんとうですか／えっ、うそ！", tipo:"expresion",
      lectura:"hontō desu ka / e', uso!",
      es:"¿en serio? / ¡no me digas!",
      formula:"えっ、ほんとうですか。(cortés) · えっ、うそ！(entre amigos) · へえ、そうですか。(neutro)",
      uso:"Las reacciones a un rumor sorprendente, de p79. うそ no acusa de mentir: es el «¡no!» de la sorpresa, solo entre cercanos.",
      ejemplo:"聞きましたか。川野さん、恋人とわかれたそうですよ。—— えっ、ほんとうですか。" },

    { pat:"お祝い・おみまい", tipo:"expresion",
      lectura:"おいわい・おみまい · oiwai / omimai",
      es:"celebrar / visitar a un enfermo",
      formula:"お祝い（をする）: boda, nacimiento, ascenso · おみまい（に行く）: hospital, enfermedad · なぐさめる: consolar · はげます: animar",
      uso:"Las cuatro palabras del ejercicio 2 de p77, una por situación: a la que se casa, お祝い; a la que está ingresada, おみまい; a quien perdió a alguien, なぐさめる; a quien tiene un mal momento, はげます.",
      ejemplo:"姉が病気で入院しています。姉が好きな花を持っておみまいに行きます。友だちが留学します。みんなでカードを書いてはげまします。" },

    { pat:"ぜひ出席してください", tipo:"expresion",
      lectura:"ぜひしゅっせきしてください · zehi shusseki shite kudasai",
      es:"ven sin falta",
      formula:"〜も招待しますから、ぜひ出席してくださいね。",
      uso:"Invitar a la boda: os invito, así que venid sin falta. 出席する es «asistir», 招待する «invitar».",
      ejemplo:"5月です。森さんも、パウロさんも、招待しますから、ぜひ出席してくださいね。" }
  ],

  verbos: [
    { kana:"けっこんする", kanji:"結婚する", g:3, es:"casarse", c:1 },
    { kana:"しりあう", kanji:"知り合う", g:1, es:"conocerse", c:1 },
    { kana:"つきあう", kanji:"つき合う", g:1, es:"salir con alguien", c:1 },
    { kana:"プロポーズする", kanji:"プロポーズする", g:3, es:"pedir matrimonio", c:1 },
    { kana:"くらす", kanji:"くらす", g:1, es:"vivir, llevar la vida", c:1 },
    { kana:"いわう", kanji:"祝う", g:1, es:"celebrar, felicitar", c:2 },
    { kana:"なぐさめる", kanji:"なぐさめる", g:2, es:"consolar", c:1 },
    { kana:"はげます", kanji:"はげます", g:1, es:"animar, dar ánimos", c:1 },
    { kana:"にゅういんする", kanji:"入院する", g:3, es:"ingresar en el hospital", c:1 },
    { kana:"なくなる", kanji:"なくなる", g:1, es:"fallecer; acabarse", c:1 },
    { kana:"きまる", kanji:"決まる", g:1, es:"decidirse (algo)", c:1, nota:"Intransitivo: la pareja es 決める" },
    { kana:"おどろく", kanji:"おどろく", g:1, es:"asombrarse", c:1 },
    { kana:"わかれる", kanji:"別れる", g:2, es:"separarse, romper", c:1 },
    { kana:"あげる", kanji:"あげる", g:2, es:"dar (a otro)", c:2 },
    { kana:"うまれる", kanji:"生まれる", g:2, es:"nacer", c:1 },
    { kana:"かわいがる", kanji:"かわいがる", g:1, es:"mimar, tratar con cariño", c:2 },
    { kana:"いのる", kanji:"いのる", g:1, es:"rezar, desear", c:1 },
    { kana:"にる", kanji:"にる", g:2, es:"parecerse", c:2, nota:"Casi siempre 〜にている" },
    { kana:"もうす", kanji:"もうす", g:1, es:"llamarse (humilde)", c:1 },
    { kana:"しゅっせきする", kanji:"出席する", g:3, es:"asistir", c:1 },
    { kana:"じゅんびする", kanji:"準備する", g:3, es:"preparar", c:2 },
    { kana:"れんしゅうする", kanji:"練習する", g:3, es:"practicar", c:2 },
    { kana:"もっていく", kanji:"持っていく", g:1, es:"llevar (algo)", c:2, nota:"Termina en いく: la forma て es 持っていって" }
  ],

  vocab: [
    /* la boda y la pareja (p76-77, p80, p82) */
    { jp:"結婚", kana:"けっこん", es:"matrimonio, boda", c:1, cat:"pareja" },
    { jp:"結婚式", kana:"けっこんしき", es:"ceremonia de boda", c:1, cat:"pareja" },
    { jp:"婚約", kana:"こんやく", es:"compromiso", c:2, cat:"pareja" },
    { jp:"相手", kana:"あいて", es:"la pareja, el otro", c:1, cat:"pareja" },
    { jp:"恋人", kana:"こいびと", es:"novio, novia", c:1, cat:"pareja" },
    { jp:"彼", kana:"かれ", es:"él; el novio", c:1, cat:"pareja" },
    { jp:"出会い", kana:"であい", es:"el encuentro (con alguien)", c:1, cat:"pareja" },
    { jp:"つき合い", kana:"つきあい", es:"trato, relación", c:2, cat:"pareja" },
    { jp:"〜合う", kana:"〜あう", es:"…se mutuamente (知り合う, つき合う, 助け合う)", c:1, cat:"pareja" },
    { jp:"気持ち", kana:"きもち", es:"sentimiento, lo que uno siente", c:1, cat:"sentimiento" },
    { jp:"幸せ", kana:"しあわせ", es:"felicidad, feliz", c:1, cat:"sentimiento" },
    { jp:"願い", kana:"ねがい", es:"deseo, petición", c:2, cat:"sentimiento" },
    { jp:"家庭", kana:"かてい", es:"hogar", c:1, cat:"casa" },
    { jp:"家事", kana:"かじ", es:"tareas de la casa", c:2, cat:"casa" },
    { jp:"お祝い", kana:"おいわい", es:"celebración, felicitación", c:1, cat:"pareja" },
    { jp:"お見舞い", kana:"おみまい", es:"visita a un enfermo", c:1, cat:"abstracto" },
    { jp:"招待", kana:"しょうたい", es:"invitación", c:1, cat:"pareja" },
    { jp:"招待状", kana:"しょうたいじょう", es:"tarjeta de invitación", c:2, cat:"objetos" },
    { jp:"出席", kana:"しゅっせき", es:"asistencia", c:1, cat:"abstracto" },
    { jp:"スピーチ", kana:"スピーチ", es:"discurso", c:1, cat:"abstracto" },
    { jp:"パーティー", kana:"パーティー", es:"fiesta", c:2, cat:"pareja" },
    { jp:"カード", kana:"カード", es:"tarjeta", c:1, cat:"objetos" },
    { jp:"カップ", kana:"カップ", es:"taza", c:1, cat:"objetos" },
    { jp:"花", kana:"はな", es:"flor", c:1, cat:"objetos" },
    { jp:"ケーキ", kana:"ケーキ", es:"tarta", c:2, cat:"comida" },
    { jp:"ピアノ", kana:"ピアノ", es:"piano", c:2, cat:"objetos" },
    { jp:"きょく", kana:"きょく", es:"pieza musical", c:2, cat:"objetos" },
    { jp:"ビデオ", kana:"ビデオ", es:"vídeo", c:2, cat:"objetos" },
    { jp:"ネクタイ", kana:"ネクタイ", es:"corbata", c:2, cat:"objetos" },
    { jp:"ダンス", kana:"ダンス", es:"baile", c:2, cat:"abstracto" },
    { jp:"島", kana:"しま", es:"isla", c:2, cat:"lugar" },
    { jp:"銀行", kana:"ぎんこう", es:"banco", c:1, cat:"lugar" },
    { jp:"お寺", kana:"おてら", es:"templo budista", c:2, cat:"lugar" },
    { jp:"神社", kana:"じんじゃ", es:"santuario sintoísta", c:2, cat:"lugar" },
    { jp:"日本祭", kana:"にほんまつり", es:"festival japonés", c:1, cat:"lugar" },
    { jp:"職場", kana:"しょくば", es:"lugar de trabajo", c:2, cat:"trabajo" },
    { jp:"アンケート", kana:"アンケート", es:"encuesta", c:2, cat:"abstracto" },
    { jp:"けっか", kana:"けっか", es:"resultado", c:2, cat:"abstracto" },
    { jp:"きっかけ", kana:"きっかけ", es:"la ocasión, el detonante", c:2, cat:"abstracto" },
    { jp:"価値観", kana:"かちかん", es:"valores, escala de valores", c:2, cat:"abstracto" },
    { jp:"せいかく", kana:"せいかく", es:"carácter", c:2, cat:"abstracto" },
    { jp:"考え方", kana:"かんがえかた", es:"manera de pensar", c:2, cat:"abstracto" },
    { jp:"うわさ", kana:"うわさ", es:"rumor", c:1, cat:"abstracto" },
    { jp:"うそ", kana:"うそ", es:"mentira; ¡no me digas!", c:1, cat:"reaccion" },
    { jp:"一生", kana:"いっしょう", es:"toda la vida", c:2, cat:"tiempo" },
    { jp:"最近", kana:"さいきん", es:"últimamente", c:1, cat:"tiempo" },
    { jp:"近ごろ", kana:"ちかごろ", es:"hoy en día", c:2, cat:"tiempo" },
    { jp:"おととし", kana:"おととし", es:"hace dos años", c:1, cat:"tiempo" },

    /* la gente (p77, p80, p85) */
    { jp:"まご", kana:"まご", es:"nieto, nieta", c:2, cat:"persona" },
    { jp:"おばあさん", kana:"おばあさん", es:"abuela", c:2, cat:"persona" },
    { jp:"きょうだい", kana:"きょうだい", es:"hermanos", c:2, cat:"persona" },
    { jp:"女性", kana:"じょせい", es:"mujer", c:2, cat:"persona" },
    { jp:"男性", kana:"だんせい", es:"hombre", c:2, cat:"persona" },
    { jp:"男女", kana:"だんじょ", es:"hombres y mujeres", c:2, cat:"persona" },
    { jp:"お金持ち", kana:"おかねもち", es:"rico (persona)", c:2, cat:"persona" },
    { jp:"ふたり", kana:"ふたり", es:"los dos, la pareja", c:1, cat:"persona" },

    /* como es (p77-78, p81-82) */
    { jp:"最高", kana:"さいこう", es:"el mejor, inmejorable", c:2, cat:"cualidad" },
    { jp:"やさしい", kana:"やさしい", es:"amable, bueno", c:1, cat:"cualidad" },
    { jp:"かわいい", kana:"かわいい", es:"mono, adorable", c:2, cat:"cualidad" },
    { jp:"すてき", kana:"すてき", es:"estupendo, precioso", c:1, cat:"cualidad" },
    { jp:"したしい", kana:"したしい", es:"íntimo, cercano", c:2, cat:"cualidad" },
    { jp:"大事", kana:"だいじ", es:"importante", c:2, cat:"cualidad" },
    { jp:"じゅうぶん", kana:"じゅうぶん", es:"suficiente", c:2, cat:"cualidad" },
    { jp:"たいくつ", kana:"たいくつ", es:"aburrido", c:1, cat:"sentimiento" },
    { jp:"さびしい", kana:"さびしい", es:"solo, triste", c:1, cat:"sentimiento" },
    { jp:"きっと", kana:"きっと", es:"seguro que", c:1, cat:"conector" },
    { jp:"たぶん", kana:"たぶん", es:"probablemente", c:1, cat:"conector" },
    { jp:"もちろん", kana:"もちろん", es:"por supuesto", c:1, cat:"conector" },
    { jp:"おめでとう", kana:"おめでとう", es:"enhorabuena", c:1, cat:"reaccion" },
    { jp:"ほんとう", kana:"ほんとう", es:"verdad, de verdad", c:1, cat:"reaccion" }
  ],

  frases: [
    { k:"f6-01", es:"Norika, ahora seguro que es feliz.", c:1, pat:"〜でしょう（ね）",
      ok:["のりかさんは、今、きっと幸せでしょうね。","のりかさんは、いま、きっとしあわせでしょうね。"] },
    { k:"f6-02", es:"Estaba pensando en hacerle a Norika algo de celebración…", c:1, pat:"〜（よ）うと思うんですが",
      ok:["のりかさんに、何かお祝いをしようと思うんですが。","のりかさんに、なにかおいわいをしようとおもうんですが。"] },
    { k:"f6-03", es:"Norika, me he enterado. He oído que te casas. Es una persona amable, ¿verdad?", c:1, pat:"よ／ね／よね",
      ok:["のりかさん、聞きましたよ。結婚するそうですね。やさしい人なんですよね。","のりかさん、ききましたよ。けっこんするそうですね。やさしいひとなんですよね。"] },
    { k:"f6-04", es:"Voy a hacerle caso a lo que Norika desea.", c:2, pat:"〜てあげます",
      ok:["（私は）のりかの願いを聞いてあげます。","のりかの願いを聞いてあげます。","のりかのねがいをきいてあげます。"] },
    { k:"f6-05", es:"No hace falta hacer una gran fiesta.", c:2, pat:"〜なくてもいいです",
      ok:["大きなパーティーはしなくてもいいです。","おおきなパーティーはしなくてもいいです。"] },
    { k:"f6-06", es:"Cuando estuve ingresada, George vino a verme todos los días. Yo le enseñé a bailar.", c:2, pat:"あげる・くれる・もらう",
      ok:["入院したとき、ジョージは毎日おみまいに来てくれました。ジョージにダンスを教えてあげました。","にゅういんしたとき、ジョージはまいにちおみまいにきてくれました。ジョージにダンスをおしえてあげました。"] },
    { k:"f6-07", es:"He oído que Norika se casa. — Dicen que es alguien que conoció en el festival japonés.", c:1, pat:"〜そうですね（伝聞）",
      ok:["のりかさん、結婚するそうですよ。—— 日本祭で知り合った人だそうです。","のりかさん、結婚するそうですよ。日本祭で知り合った人だそうです。","のりかさん、けっこんするそうですよ。にほんまつりでしりあったひとだそうです。"] },
    { k:"f6-08", es:"¿Qué pasa hasta casarse? Conocerse → salir → la pedida → la boda → vivir juntos.", c:1, pat:"〜まで／〜までに",
      ok:["結婚するまでに、どんなことがありますか。知り合う → つき合う → プロポーズする → 結婚式をする → いっしょにくらす。","けっこんするまでに、どんなことがありますか。しりあう → つきあう → プロポーズする → けっこんしきをする → いっしょにくらす。"] },
    { k:"f6-09", es:"Con celebrarlo con la familia y los amigos íntimos basta.", c:2, pat:"〜ば、じゅうぶんです",
      ok:["家族やしたしい友だちとお祝いすればじゅうぶんです。","かぞくやしたしいともだちとおいわいすればじゅうぶんです。"] },
    { k:"f6-10", es:"Creo que el dinero es mejor gastarlo en la nueva vida de los dos que en la boda o la fiesta.", c:2, pat:"〜より〜方がいい",
      ok:["お金は結婚式やパーティーよりふたりの新しい生活のために使った方がいいと思います。","おかねはけっこんしきやパーティーよりふたりのあたらしいせいかつのためにつかったほうがいいとおもいます。"] },
    { k:"f6-11", es:"Pero si para Norika hacer una gran boda es importante, entonces vale.", c:2, pat:"〜にとって〜がだいじなら",
      ok:["でも、のりかにとって大きな結婚式をすることがだいじなら、それでもいいです。","でも、のりかにとっておおきなけっこんしきをすることがだいじなら、それでもいいです。"] },
    { k:"f6-12", es:"Según una encuesta reciente, la forma más común de conocer a la pareja es en el trabajo.", c:2, pat:"〜によると",
      ok:["最近のアンケートによると、結婚相手と知り合ったきっかけで一番多いのは、職場での出会いです。","さいきんのアンケートによると、けっこんあいてとしりあったきっかけでいちばんおおいのは、しょくばでのであいです。"] },
    { k:"f6-13", es:"Lo más común es conocerse en el trabajo. Después, por presentación de un amigo, y luego en la escuela.", c:2, pat:"きっかけ",
      ok:["結婚相手と知り合ったきっかけで一番多いのは、職場での出会いです。つぎに多いのは、友だちの紹介、そして学校での出会いです。","けっこんあいてとしりあったきっかけでいちばんおおいのは、しょくばでのであいです。つぎにおおいのは、ともだちのしょうかい、そしてがっこうでのであいです。"] },
    { k:"f6-14", es:"Norika, George, enhorabuena por vuestra boda.", c:1, pat:"おめでとうございます",
      ok:["のりかさん、ジョージさん、ご結婚おめでとうございます。","のりかさん、ジョージさん、ごけっこんおめでとうございます。"] },
    { k:"f6-15", es:"Me llamo Paulo y trabajo en la misma empresa que Norika. Seguro que su hogar será alegre y cálido. Les deseo una larga felicidad.", c:1, pat:"結婚式のスピーチ",
      ok:["私は、のりかさんと同じ会社に勤めているパウロともうします。ふたりの家庭は、きっと明るくて、あたたかい家庭になると思います。すえながいお幸せをおいのりしています。","わたしは、のりかさんとおなじかいしゃにつとめているパウロともうします。ふたりのかていは、きっとあかるくて、あたたかいかていになるとおもいます。すえながいおしあわせをおいのりしています。"] },
    { k:"f6-16", es:"¿Te has enterado? Dicen que Kawano ha roto con su pareja. — ¿En serio?", c:1, pat:"ほんとうですか／えっ、うそ！",
      ok:["聞きましたか。川野さん、恋人とわかれたそうですよ。—— えっ、ほんとうですか。","聞きましたか。川野さん、恋人とわかれたそうですよ。えっ、ほんとうですか。","ききましたか。かわのさん、こいびととわかれたそうですよ。えっ、ほんとうですか。"] },
    { k:"f6-17", es:"Mi hermana está ingresada. Le llevo sus flores favoritas a verla. Un amigo se va a estudiar fuera: le escribimos una tarjeta entre todos para animarle.", c:1, pat:"お祝い・おみまい",
      ok:["姉が病気で入院しています。姉が好きな花を持っておみまいに行きます。友だちが留学します。みんなでカードを書いてはげまします。","あねがびょうきでにゅういんしています。あねがすきなはなをもっておみまいにいきます。ともだちがりゅうがくします。みんなでカードをかいてはげまします。"] },
    { k:"f6-18", es:"Es en mayo. Os invito a los dos, así que venid sin falta.", c:1, pat:"ぜひ出席してください",
      ok:["5月です。森さんも、パウロさんも、招待しますから、ぜひ出席してくださいね。","5がつです。もりさんも、パウロさんも、しょうたいしますから、ぜひしゅっせきしてくださいね。"] }
  ],

  huecos: [
    /* p77, ejercicio 2 */
    { k:"h6-01", pat:"お祝い・おみまい", pre:"友だちが留学します。みんなでカードを書いて（", post:"）。", hint:"animar → forma ます", ok:["はげまします"], c:1, es:"Un amigo se va a estudiar fuera. Le escribimos una tarjeta entre todos para animarle." },
    { k:"h6-02", pat:"お祝い・おみまい", pre:"来月、友だちが結婚します。（", post:"）にペアのカップをあげます。", hint:"como regalo de celebración", ok:["お祝い","おいわい"], c:1, es:"El mes que viene se casa un amigo. Le regalo unas tazas de pareja de celebración." },
    { k:"h6-03", pat:"お祝い・おみまい", pre:"恋人が、海外に転勤したので、会えなくて（", post:"）。", hint:"me siento solo → adjetivo い + です", ok:["さびしいです"], c:1, es:"A mi pareja la han trasladado al extranjero, no podemos vernos y me siento solo." },
    { k:"h6-04", pat:"お祝い・おみまい", pre:"友だちのお父さんがなくなりました。友だちの家に行って（", post:"）。", hint:"consolar → forma ます", ok:["なぐさめます"], c:1, es:"El padre de un amigo ha fallecido. Voy a su casa a consolarle." },
    { k:"h6-05", pat:"お祝い・おみまい", pre:"姉が病気で入院しています。姉が好きな花を持って（", post:"）に行きます。", hint:"visita al hospital", ok:["おみまい","お見舞い"], c:1, es:"Mi hermana está ingresada. Le llevo sus flores favoritas a verla." },
    /* p78, 文2 */
    { k:"h6-06", pat:"〜でしょう（ね）", pre:"吉田さんは、病院でたぶん（", post:"）。", hint:"たいくつです → 〜でしょう", ok:["たいくつでしょう"], c:1, es:"Yoshida, en el hospital, seguramente esté aburrido." },
    { k:"h6-07", pat:"〜でしょう（ね）", pre:"キムさんは、転勤が決まって、きっと（", post:"）。", hint:"うれしいです → 〜でしょう", ok:["うれしいでしょう"], c:1, es:"A Kim le han confirmado el traslado; seguro que está contenta." },
    { k:"h6-08", pat:"〜でしょう（ね）", pre:"のりかさんの結婚をご両親もきっと（", post:"）。", hint:"喜んでいます → 〜でしょう", ok:["喜んでいるでしょう","よろこんでいるでしょう"], c:1, es:"Los padres de Norika seguro que están contentos con su boda." },
    { k:"h6-09", pat:"〜（よ）うと思うんですが", pre:"明日、おみまいに（", post:"）。", hint:"行きます → 〜こうと思うんですが", ok:["行こうと思うんですが","いこうとおもうんですが","いこうと思うんですが"], c:1, es:"Mañana estaba pensando en ir a verle al hospital…" },
    { k:"h6-10", pat:"〜（よ）うと思うんですが", pre:"川野さんにメールを書いて、（", post:"）。", hint:"なぐさめます → 〜ようと思うんですが", ok:["なぐさめようと思うんですが","なぐさめようとおもうんですが"], c:1, es:"Pensaba escribirle a Kawano para consolarle…" },
    { k:"h6-11", pat:"〜（よ）うと思うんですが", pre:"キムさんをはげますために、食事に（", post:"）。", hint:"さそいます → 〜おうと思うんですが", ok:["さそおうと思うんですが","さそおうとおもうんですが"], c:1, es:"Para animar a Kim, pensaba invitarla a comer…" },
    /* p80, 文2: よ・ね・よね */
    { k:"h6-12", pat:"よ／ね／よね", pre:"のりかさん、聞きました（", post:"）。", hint:"le informo de algo", ok:["よ"], c:1, es:"Norika, me he enterado." },
    { k:"h6-13", pat:"よ／ね／よね", pre:"結婚するそうです（", post:"）。", hint:"busco que confirme", ok:["ね"], c:1, es:"He oído que te casas, ¿no?" },
    { k:"h6-14", pat:"よ／ね／よね", pre:"やさしい人なんです（", post:"）。", hint:"lo creo, y pido que lo ratifique", ok:["よね"], c:1, es:"Es una persona amable, ¿verdad?" },
    { k:"h6-15", pat:"よ／ね／よね", pre:"のりかさんとかれは、日本祭でボランティアとして働いてました（", post:"）。", hint:"lo recuerdo, ¿verdad?", ok:["よね"], c:1, es:"Norika y él trabajaron de voluntarios en el festival japonés, ¿verdad?" },
    /* p83, 文2 (1): 〜てあげます */
    { k:"h6-16", pat:"〜てあげます", pre:"友だちみんなでパーティーをして、ふたりの結婚を（", post:"）。", hint:"祝います → 〜てあげます", ok:["いわってあげます","祝ってあげます"], c:2, es:"Hacemos una fiesta entre todos los amigos y les celebramos la boda." },
    { k:"h6-17", pat:"〜てあげます", pre:"結婚式の前は忙しいので、じゅんびを（", post:"）。", hint:"てつだいます → 〜てあげます", ok:["てつだってあげます","手伝ってあげます"], c:2, es:"Antes de la boda hay mucho lío, así que les ayudo con los preparativos." },
    { k:"h6-18", pat:"〜てあげます", pre:"のりかは私のかわいいまごです。何があっても結婚式に（", post:"）。", hint:"出席します → 〜てあげたいです", ok:["出席してあげたいです","しゅっせきしてあげたいです"], c:2, es:"Norika es mi nieta querida. Pase lo que pase quiero ir a su boda." },
    { k:"h6-19", pat:"〜てあげます", pre:"結婚式の日、ふたりのビデオを（", post:"）。", hint:"とります → 〜てあげようと思います", ok:["とってあげようと思います","とってあげようとおもいます"], c:2, es:"El día de la boda pienso grabarles un vídeo." },
    { k:"h6-20", pat:"〜てあげます", pre:"私は、結婚式でピアノを（", post:"）。", hint:"ひきます → 〜てあげようと思います", ok:["ひいてあげようと思います","ひいてあげようとおもいます"], c:2, es:"Yo pienso tocarles el piano en la boda." },
    /* p83-84, 文2 (2): あげる / くれる / もらう */
    { k:"h6-21", pat:"あげる・くれる・もらう", pre:"入院したとき、ジョージは毎日おみまいに来て（", post:"）。", hint:"él → a mí", ok:["くれました"], c:2, es:"Cuando estuve ingresada, George vino a verme todos los días." },
    { k:"h6-22", pat:"あげる・くれる・もらう", pre:"ジョージにダンスを教えて（", post:"）。", hint:"yo → a él", ok:["あげました"], c:2, es:"Yo le enseñé a bailar a George." },
    { k:"h6-23", pat:"あげる・くれる・もらう", pre:"結婚式のあと、ジョージにきれいな島につれていって（", post:"）。", hint:"yo recibo de él (に)", ok:["もらいます"], c:2, es:"Después de la boda, George me llevará a una isla preciosa." },
    { k:"h6-24", pat:"あげる・くれる・もらう", pre:"よくのりかにケーキを作って（", post:"）。のりかはたくさん食べて、「おいしい」と言って（", post2:"）。", hint:"yo → ella / ella → a mí", ok:["あげます"], ok2:["くれます"], c:2, es:"Le hago tartas a Norika a menudo. Ella come mucho y me dice «qué rica»." },
    { k:"h6-25", pat:"あげる・くれる・もらう", pre:"仕事で日本についてレポートを書いたとき、のりかにてつだって（", post:"）。", hint:"yo recibo de ella (に)", ok:["もらいました"], c:2, es:"Cuando escribí un informe sobre Japón para el trabajo, Norika me ayudó." },
    /* p84, 文3 */
    { k:"h6-26", pat:"〜なくてもいいです", pre:"大きなパーティーは（", post:"）いいです。", hint:"します → 〜なくても", ok:["しなくても"], c:2, es:"No hace falta hacer una gran fiesta." },
    { k:"h6-27", pat:"〜なくてもいいです", pre:"招待状が（", post:"）だいじょうぶです。", hint:"ありません → 〜なくても", ok:["なくても"], c:2, es:"No pasa nada si no hay invitación." },
    { k:"h6-28", pat:"〜なくてもいいです", pre:"お祝いのお金を（", post:"）いいです。", hint:"持っていきます → 〜なくても", ok:["持っていかなくても","もっていかなくても"], c:2, es:"No hace falta llevar dinero de regalo." },
    { k:"h6-29", pat:"〜なくてもいいです", pre:"お寺や神社で（", post:"）いいです。", hint:"します → 〜なくても", ok:["しなくても"], c:2, es:"No hace falta hacerla en un templo o santuario." },
    /* dialogos y textos */
    { k:"h6-30", pat:"〜そうですね（伝聞）", pre:"日本祭で知り合った人（", post:"）。", hint:"sustantivo + だそうです", ok:["だそうです"], c:1, es:"Dicen que es alguien que conoció en el festival japonés." },
    { k:"h6-31", pat:"結婚式のスピーチ", pre:"私は、のりかさんと同じ会社に勤めているパウロ（", post:"）。", hint:"me llamo, humilde", ok:["ともうします"], c:1, es:"Me llamo Paulo y trabajo en la misma empresa que Norika." },
    { k:"h6-32", pat:"〜ば、じゅうぶんです", pre:"家族やしたしい友だちと（", post:"）じゅうぶんです。", hint:"お祝いします → 〜ば", ok:["お祝いすれば","おいわいすれば"], c:2, es:"Con celebrarlo con la familia y los amigos íntimos basta." },
    { k:"h6-33", pat:"〜より〜方がいい", pre:"お金は結婚式やパーティーよりふたりの新しい生活のために（", post:"）いいと思います。", hint:"使いました → 〜た方が", ok:["使った方が","つかったほうが","使ったほうが"], c:2, es:"Creo que el dinero es mejor gastarlo en la nueva vida de los dos." },
    { k:"h6-34", pat:"〜によると", pre:"最近のアンケート（", post:"）、結婚相手と知り合ったきっかけで一番多いのは、職場での出会いです。", hint:"según…", ok:["によると"], c:2, es:"Según una encuesta reciente, lo más común es conocer a la pareja en el trabajo." }
  ],

  armar: [
    { k:"a6-01", es:"¿Te has enterado? He oído que Norika se casa.", c:1, chips:["聞きましたか。","のりかさん、","結婚する","そうですよ"] },
    { k:"a6-02", es:"Dicen que es alguien que conoció en el festival japonés.", c:1, chips:["日本祭で","知り合った","人だ","そうです"] },
    { k:"a6-03", es:"Pues ahora seguro que es feliz.", c:1, chips:["じゃあ、","今、","きっと幸せ","でしょうね"] },
    { k:"a6-04", es:"Por eso estaba pensando en hacerle algo de celebración…", c:1, chips:["それで、","何か","お祝いをしようと","思うんですが"] },
    { k:"a6-05", es:"Norika, me he enterado. He oído que te casas.", c:1, chips:["のりかさん、","聞きましたよ。","結婚する","そうですね"] },
    { k:"a6-06", es:"La verdad es que nos vimos por primera vez en el festival japonés de hace dos años.", c:1, chips:["じつは、","おととしの日本祭のとき、","初めて","会ったんです"] },
    { k:"a6-07", es:"Es en mayo. Os invito a los dos, así que venid sin falta.", c:1, chips:["5月です。","森さんも、パウロさんも、","招待しますから、","ぜひ出席してくださいね"] },
    { k:"a6-08", es:"Seguro que su hogar será alegre y cálido.", c:1, chips:["ふたりの家庭は、","きっと","明るくて、あたたかい家庭に","なると思います"] },
    { k:"a6-09", es:"Es una vez en la vida, así que quiero la mejor boda.", c:2, chips:["一生に一度の","ことだから、","最高の結婚式に","したいです"] },
    { k:"a6-10", es:"Quiero que venga toda la gente posible.", c:2, chips:["できるだけ","たくさんの人に","来て","もらいたいです"] },
    { k:"a6-11", es:"Yo no necesito boda.", c:2, chips:["ぼくは、","結婚式は","しなくても","いいです"] },
    { k:"a6-12", es:"Con celebrarlo con la familia y los amigos íntimos basta.", c:2, chips:["家族や","したしい友だちと","お祝いすれば","じゅうぶんです"] },
    { k:"a6-13", es:"Al final, quiero hacerle caso a lo que Norika desea.", c:2, chips:["やっぱり、","のりかの","願いを","聞いてあげたいです"] },
    { k:"a6-14", es:"Cuando estuve ingresada, George vino a verme todos los días.", c:2, chips:["入院したとき、","ジョージは","毎日おみまいに","来てくれました"] },
    { k:"a6-15", es:"No hace falta llevar dinero de regalo.", c:2, chips:["お祝いの","お金を","持っていかなくても","いいです"] },
    { k:"a6-16", es:"Tanto hombres como mujeres quieren casarse con alguien de valores parecidos.", c:2, chips:["女性も男性も、","価値観がにている人と","結婚したいと","思っています"] }
  ]
});
