/* Dojo Marugoto - unidad 7, なやみ相談
   Marugoto A2/B1 Parte 2 - clase 1 = libro p86-91 - clase 2 = p92-95

   De donde salen los huecos:
     h7-01 a h7-04  p87, ejercicio 3   (que se hace por un amigo con problemas)
     h7-05 a h7-08  p87, ejercicio 4   (de que es cada preocupacion)
     h7-09 a h7-12  p88, 文2           (〜て / Nのことで)
     h7-13 a h7-15  p90, 文2           (〜かもしれません)
     h7-16 a h7-23  p93, 文2           (〜のに)
     h7-24 a h7-28  p94, 文3           (〜てほしい / 〜ないでほしい)
     h7-29 a h7-34  los dialogos de p89-90 y los textos de p92 y p95 */

CONTENIDO.unidades.push({
  n: 7,
  titulo: "なやみ相談",
  es: "Contar lo que preocupa",
  paginas: { 1: "86-91", 2: "92-95" },
  estado: "lista",

  /* Tres formas nuevas: forma て + ほしいです y forma ない + でほしいです
     (p94, 文3), y forma simple + かもしれません (p90, 文2). */
  formas: {
    1: ["masu", "masen", "nai", "ta", "te", "kamo", "tai", "tara"],
    2: ["masu", "nai", "ta", "te", "tehoshii", "naidehoshii", "kamo", "pot"]
  },

  patrones: [
    { pat:"〜て（い）て", tipo:"gramatica",
      oficial:"～て（い）て",
      lectura:"te (i) te",
      es:"es que estoy…",
      formula:"forma て + （い）て。 La frase se deja abierta; lo que sigue (元気がありません) se sobreentiende",
      uso:"La explicación a medias de quien no está bien: es que estoy cansada… es que no duermo… Con el い comido al hablar: つかれてて.",
      ejemplo:"ちょっと疲れて（い）て（元気がありません）。" },

    { pat:"Nのことで", tipo:"gramatica",
      oficial:"～のことで",
      lectura:"no koto de",
      es:"por lo de…, con el tema de…",
      formula:"sustantivo + のことで + ちょっと（こまっています）",
      uso:"Nombrar el asunto sin entrar en detalle: por lo del trabajo, por lo de casa, por lo de los niños. Es la respuesta prudente a どうしたんですか.",
      ejemplo:"仕事のことでちょっと（困っています）。" },

    { pat:"〜かもしれません", tipo:"gramatica",
      oficial:"～かもしれない",
      lectura:"kamo shiremasen",
      es:"puede que…, quizá…",
      formula:"forma simple + かもしれません. Sustantivo y adjetivo な pelados: 同じかもしれません",
      uso:"Una posibilidad que uno señala sin afirmar: en mi trabajo puede que pase lo mismo. Más dubitativo que でしょう.",
      ejemplo:"私の職場でも、同じかもしれません。" },

    { pat:"〜のに", tipo:"gramatica",
      oficial:"～のに",
      lectura:"noni",
      es:"aunque…, a pesar de que…",
      formula:"forma simple + のに、+ lo que no encaja. Sustantivo y adjetivo な: 〜なのに",
      uso:"Lo que pasa va contra lo esperado, y duele: con lo que cuesta quedar, se pone a hablar por teléfono. Lleva queja; けど no.",
      ejemplo:"せっかく会っているのに、友だちはカレシと長電話をします。" },

    { pat:"〜てほしいです／〜ないでほしいです", tipo:"gramatica",
      oficial:"～て欲しい",
      lectura:"te hoshii desu / naide hoshii desu",
      es:"quiero que… / quiero que no…",
      formula:"（persona + に）+ forma て + ほしいです · + forma ない + でほしいです",
      uso:"Lo que uno quiere del otro: que respete las normas, que no se pase con el teléfono. La persona lleva に. Es el deseo sobre la conducta ajena, no sobre la propia (〜たい).",
      ejemplo:"私はS子にマナーをまもってほしいです。長電話をしないでほしいです。" },

    { pat:"せっかく〜のに", tipo:"gramatica",
      lectura:"sekkaku ~ noni",
      es:"con lo que cuesta…, y encima…",
      formula:"せっかく + forma simple + のに、+ lo que lo estropea",
      uso:"せっかく subraya el esfuerzo o la ocasión especial; のに, que se desaprovecha. Con lo que me ha costado hacer tiempo para verla, y se pone al teléfono.",
      ejemplo:"せっかく時間をつくって会っているのに、ほかの人と長電話をするのはひどいと思います。" },

    { pat:"どうしたらいいか", tipo:"gramatica",
      lectura:"dō shitara ii ka",
      es:"qué debería hacer",
      formula:"どうしたらいいか + まよっています／わかりません",
      uso:"La duda sobre qué hacer, como sustantivo dentro de la frase. どうしたら es «si hago qué», いい «está bien».",
      ejemplo:"友だちとしての関係はつづけていきたいので、今後どうしたらいいかまよっています。" },

    { pat:"〜てはだめですよね", tipo:"gramatica",
      lectura:"te wa dame desu yo ne",
      es:"no está bien que…, ¿verdad?",
      formula:"forma て + はだめですよね",
      uso:"Un reproche con el que se busca acuerdo: hablar largo por teléfono cuando estás con alguien no está bien, ¿no? ては + だめ es la prohibición suave.",
      ejemplo:"人と会っているときに、ほかの人と長電話をしてはだめですよね。" },

    { pat:"〜た方がいいと思います", tipo:"gramatica",
      lectura:"ta hō ga ii to omoimasu",
      es:"creo que sería mejor…",
      formula:"forma た + 方がいいと思います",
      uso:"El consejo: si es un amigo, mejor decirle claramente incluso lo que cuesta decir. Con た es un consejo concreto para esta situación.",
      ejemplo:"友だちなら、言いにくいこともはっきり言ってあげた方がいいと思います。" },

    { pat:"〜ないようにしてはどうですか", tipo:"gramatica",
      lectura:"nai yō ni shite wa dō desu ka",
      es:"¿y si procuraras no…?",
      formula:"forma ない + ようにしてはどうですか",
      uso:"Otra manera de aconsejar, como pregunta: ¿y si durante un tiempo procuras no verla? Menos directa que 〜た方がいい.",
      ejemplo:"しばらく、S子さんと会わないようにしてはどうですか。" },

    { pat:"〜たらいいんじゃないかと思います", tipo:"gramatica",
      lectura:"tara ii n ja nai ka to omoimasu",
      es:"creo que estaría bien que…",
      formula:"forma たら + いいんじゃないかと思います",
      uso:"El consejo más suave de los tres: ¿no sería buena idea escucharla por teléfono de vez en cuando? Lo dice ドクタートランプ en p95.",
      ejemplo:"そしてときどき、電話でS子さんの話を聞いてあげたらいいんじゃないかと思います。" },

    { pat:"〜と、すっきりします", tipo:"gramatica",
      lectura:"to, sukkiri shimasu",
      es:"cuando uno…, se queda a gusto",
      formula:"forma diccionario + と、+ consecuencia",
      uso:"El と de «cada vez que»: las preocupaciones, cuando se cuentan, alivian. すっきりする es quedarse despejado.",
      ejemplo:"なやみは人に話すと、すっきりしますよ。" },

    { pat:"〜として", tipo:"gramatica",
      lectura:"to shite",
      es:"como…, en calidad de…",
      formula:"sustantivo + として（の）",
      uso:"El papel en que se hace algo: como amiga quiero seguir la relación; trabajaron como voluntarios. 〜としての delante de sustantivo.",
      ejemplo:"友だちとしての関係はつづけていきたいので、今後どうしたらいいかまよっています。" },

    { pat:"〜らしくないですよ", tipo:"expresion",
      lectura:"rashiku nai desu yo",
      es:"no pareces tú",
      formula:"nombre + らしくないですよ",
      uso:"Lo que se dice a quien está raro: no es propio de ti. 〜らしい es «propio de», «típico de».",
      ejemplo:"カーラさんらしくないですよ。" },

    { pat:"いつもより元気がないですね", tipo:"expresion",
      lectura:"いつもよりげんきがないですね · itsumo yori genki ga nai desu ne",
      es:"te veo con menos ánimo que de costumbre",
      formula:"〜さん、どうしたんですか。いつもより元気がないですね。",
      uso:"La manera de abordar a quien no está bien, de p89: primero どうしたんですか, luego la observación. いつもより es «más que de costumbre».",
      ejemplo:"カーラさん、どうしたんですか。いつもより元気がないですね。" },

    { pat:"私でよかったら、相談にのりますよ", tipo:"expresion",
      lectura:"わたしでよかったら、そうだんにのりますよ · watashi de yokattara, sōdan ni norimasu yo",
      es:"si te sirvo, te escucho",
      formula:"私でよかったら、相談にのりますよ。 · じゃあ、座って話しましょう。",
      uso:"Ofrecerse a escuchar sin presionar. 相談にのる es «prestarse a que te consulten». La condición 私でよかったら rebaja: «si yo valgo».",
      ejemplo:"私でよかったら、相談にのりますよ。" },

    { pat:"こえをかける・話を聞く・相談にのる・そばにいる", tipo:"expresion",
      lectura:"koe o kakeru / hanashi o kiku / sōdan ni noru / soba ni iru",
      es:"lo que se hace por un amigo con problemas",
      formula:"こえをかける (dirigirle la palabra) · 話を聞く (escucharle) · 相談にのる (dejarse consultar) · そばにいる (estar a su lado)",
      uso:"Las cuatro expresiones del ejercicio 3 de p87. Cada una lleva su verbo fijo: こえ va con かける, 相談 con のる.",
      ejemplo:"こえをかける。話を聞く。相談にのる。そばにいる。" },

    { pat:"なやみの種類", tipo:"expresion",
      lectura:"なやみのしゅるい · nayami no shurui",
      es:"de qué van las preocupaciones",
      formula:"恋愛 · 結婚・家庭 · 人間関係 · 仕事 · 生活 · 健康（体や心）· お金",
      uso:"Las siete categorías del ejercicio 4 de p87 y del ranking de p90. El primero del ranking, con diferencia, es 人間関係.",
      ejemplo:"兄に30万円貸しましたが、返してくれません。（お金）最近、恋人が私に会ってくれません。（恋愛）" },

    { pat:"だいじょうぶです。ちょっと〜て。", tipo:"expresion",
      lectura:"daijōbu desu. chotto ~ te.",
      es:"no es nada. Es que estoy un poco…",
      formula:"だいじょうぶです。ちょっと + forma て（い）て。",
      uso:"La primera respuesta, que quita importancia: no es nada, solo estoy cansada. Después de un ほんとに？ suele venir la verdad: じつは、〜のことでちょっと…",
      ejemplo:"だいじょうぶです。ちょっとつかれてて。" }
  ],

  verbos: [
    { kana:"なやむ", kanji:"なやむ", g:1, es:"estar preocupado, darle vueltas", c:1 },
    { kana:"しゃべる", kanji:"しゃべる", g:1, es:"charlar, hablar", c:2, nota:"Grupo 1, aunque termine en 〜べる" },
    { kana:"あやまる", kanji:"あやまる", g:1, es:"pedir perdón", c:2 },
    { kana:"かえす", kanji:"返す", g:1, es:"devolver", c:1 },
    { kana:"まもる", kanji:"まもる", g:1, es:"respetar, cumplir (una norma)", c:2 },
    { kana:"まよう", kanji:"まよう", g:1, es:"dudar, no saber qué hacer", c:2 },
    { kana:"わらう", kanji:"わらう", g:1, es:"reír", c:1 },
    { kana:"ねむる", kanji:"ねむる", g:1, es:"dormir, conciliar el sueño", c:1 },
    { kana:"のむ", kanji:"飲む", g:1, es:"beber", c:1 },
    { kana:"ふる", kanji:"ふる", g:1, es:"mover (la cabeza), agitar", c:1 },
    { kana:"いれる", kanji:"いれる", g:2, es:"preparar (café, té)", c:2 },
    { kana:"すすめる", kanji:"すすめる", g:2, es:"ofrecer, recomendar", c:2 },
    { kana:"けんかする", kanji:"けんかする", g:3, es:"pelearse, discutir", c:2 },
    { kana:"すっきりする", kanji:"すっきりする", g:3, es:"quedarse a gusto, despejarse", c:1 },
    { kana:"とうこうする", kanji:"とうこうする", g:3, es:"publicar (en una web)", c:2 },
    { kana:"しんぱいする", kanji:"心配する", g:3, es:"preocuparse", c:1 }
  ],

  vocab: [
    /* la preocupacion y el consejo (p86-87, p89-90) */
    { jp:"なやみ", kana:"なやみ", es:"preocupación, problema", c:1, cat:"sentimiento" },
    { jp:"相談", kana:"そうだん", es:"consulta, pedir consejo", c:1, cat:"abstracto" },
    { jp:"アドバイス", kana:"アドバイス", es:"consejo", c:2, cat:"abstracto" },
    { jp:"心", kana:"こころ", es:"corazón, mente", c:1, cat:"sentimiento" },
    { jp:"心配", kana:"しんぱい", es:"preocupación, inquietud", c:1, cat:"sentimiento" },
    { jp:"不安", kana:"ふあん", es:"inquietud, desasosiego", c:1, cat:"sentimiento" },
    { jp:"気分", kana:"きぶん", es:"estado de ánimo", c:1, cat:"sentimiento" },
    { jp:"かなしい", kana:"かなしい", es:"triste", c:2, cat:"sentimiento" },
    { jp:"ひどい", kana:"ひどい", es:"horrible, cruel", c:2, cat:"cualidad" },
    { jp:"意外", kana:"いがい", es:"inesperado, sorprendente", c:1, cat:"cualidad" },
    { jp:"なまいき", kana:"なまいき", es:"impertinente, creído", c:1, cat:"cualidad" },
    { jp:"いっしょうけんめい", kana:"いっしょうけんめい", es:"con todas las fuerzas", c:2, cat:"cualidad" },
    { jp:"ハッピー", kana:"ハッピー", es:"feliz, contento", c:2, cat:"sentimiento" },
    { jp:"こえ", kana:"こえ", es:"voz", c:1, cat:"abstracto" },
    { jp:"話", kana:"はなし", es:"lo que uno cuenta, conversación", c:1, cat:"abstracto" },
    { jp:"へんじ", kana:"へんじ", es:"respuesta", c:2, cat:"abstracto" },
    { jp:"マナー", kana:"マナー", es:"modales, buenas maneras", c:2, cat:"abstracto" },
    { jp:"関係", kana:"かんけい", es:"relación", c:2, cat:"abstracto" },
    { jp:"人間関係", kana:"にんげんかんけい", es:"relaciones personales", c:1, cat:"abstracto" },
    { jp:"恋愛", kana:"れんあい", es:"amor, relación de pareja", c:1, cat:"pareja" },
    { jp:"カレシ", kana:"カレシ", es:"novio", c:2, cat:"pareja" },
    { jp:"親友", kana:"しんゆう", es:"mejor amigo", c:1, cat:"persona" },
    { jp:"親", kana:"おや", es:"padres", c:1, cat:"persona" },
    { jp:"社会人", kana:"しゃかいじん", es:"adulto que trabaja", c:1, cat:"persona" },
    { jp:"新人", kana:"しんじん", es:"nuevo, novato", c:2, cat:"persona" },
    { jp:"ドクター", kana:"ドクター", es:"doctor", c:2, cat:"persona" },
    { jp:"社会", kana:"しゃかい", es:"sociedad", c:1, cat:"abstracto" },
    { jp:"職場", kana:"しょくば", es:"lugar de trabajo", c:1, cat:"trabajo" },
    { jp:"給料", kana:"きゅうりょう", es:"sueldo", c:1, cat:"trabajo" },
    { jp:"飲み会", kana:"のみかい", es:"salida a beber (del trabajo)", c:2, cat:"trabajo" },
    { jp:"わりかん", kana:"わりかん", es:"pagar a escote", c:2, cat:"abstracto" },
    { jp:"ランキング", kana:"ランキング", es:"ranking", c:1, cat:"abstracto" },
    { jp:"人数", kana:"にんずう", es:"número de personas", c:1, cat:"abstracto" },
    { jp:"お酒", kana:"おさけ", es:"alcohol, sake", c:2, cat:"comida" },
    { jp:"コーヒー", kana:"コーヒー", es:"café", c:2, cat:"comida" },
    { jp:"朝ご飯", kana:"あさごはん", es:"desayuno", c:1, cat:"comida" },
    { jp:"タバコ", kana:"タバコ", es:"tabaco", c:2, cat:"objetos" },
    { jp:"新聞", kana:"しんぶん", es:"periódico", c:2, cat:"objetos" },
    { jp:"長電話", kana:"ながでんわ", es:"llamada interminable", c:2, cat:"abstracto" },
    { jp:"くび", kana:"くび", es:"cuello", c:1, cat:"abstracto" },
    { jp:"目", kana:"め", es:"ojo", c:1, cat:"abstracto" },
    { jp:"そば", kana:"そば", es:"al lado", c:1, cat:"lugar" },
    { jp:"後ろ", kana:"うしろ", es:"detrás", c:1, cat:"lugar" },
    { jp:"ホーム", kana:"ホーム", es:"andén", c:2, cat:"lugar" },
    { jp:"今夜", kana:"こんや", es:"esta noche", c:1, cat:"tiempo" },
    { jp:"今後", kana:"こんご", es:"de ahora en adelante", c:2, cat:"tiempo" },
    { jp:"しばらく", kana:"しばらく", es:"durante un tiempo", c:2, cat:"tiempo" },
    { jp:"休み", kana:"やすみ", es:"día libre", c:2, cat:"tiempo" },
    { jp:"はっきり", kana:"はっきり", es:"con claridad", c:2, cat:"conector" },
    { jp:"せっかく", kana:"せっかく", es:"con lo que cuesta…, expresamente", c:2, cat:"conector" },
    { jp:"じっと", kana:"じっと", es:"fijamente, quieto", c:1, cat:"conector" },
    { jp:"なんだか", kana:"なんだか", es:"no sé por qué, como que", c:1, cat:"conector" },
    { jp:"おたがい", kana:"おたがい", es:"los dos, mutuamente", c:2, cat:"conector" },
    { jp:"それより", kana:"それより", es:"más que eso", c:1, cat:"conector" },
    { jp:"だから", kana:"だから", es:"por eso", c:2, cat:"conector" },
    { jp:"そしたら", kana:"そしたら", es:"y entonces", c:2, cat:"conector" },
    { jp:"うーん", kana:"うーん", es:"mmm…", c:1, cat:"reaccion" },
    { jp:"ふうん", kana:"ふうん", es:"ah, ya", c:1, cat:"reaccion" }
  ],

  frases: [
    { k:"f7-01", es:"Es que estoy un poco cansada.", c:1, pat:"〜て（い）て",
      ok:["ちょっと疲れて（い）て（元気がありません）。","ちょっと疲れてて。","ちょっとつかれてて。","ちょっとつかれていて。"] },
    { k:"f7-02", es:"Por lo del trabajo, estoy un poco…", c:1, pat:"Nのことで",
      ok:["仕事のことでちょっと（困っています）。","仕事のことでちょっと困っています。","しごとのことでちょっとこまっています。"] },
    { k:"f7-03", es:"En mi trabajo puede que pase lo mismo.", c:1, pat:"〜かもしれません",
      ok:["私の職場でも、同じかもしれません。","わたしのしょくばでも、おなじかもしれません。"] },
    { k:"f7-04", es:"Con lo que cuesta quedar, mi amiga se pone a hablar por teléfono con el novio.", c:2, pat:"〜のに",
      ok:["せっかく会っているのに、友だちはカレシと長電話をします。","せっかくあっているのに、ともだちはカレシとながでんわをします。"] },
    { k:"f7-05", es:"Quiero que S respete las normas. Quiero que no hable tanto por teléfono.", c:2, pat:"〜てほしいです／〜ないでほしいです",
      ok:["私はS子にマナーをまもってほしいです。長電話をしないでほしいです。","わたしはSこにマナーをまもってほしいです。ながでんわをしないでほしいです。"] },
    { k:"f7-06", es:"Con lo que me cuesta hacer tiempo para verla, ponerse a hablar con otro me parece horrible.", c:2, pat:"せっかく〜のに",
      ok:["せっかく時間をつくって会っているのに、ほかの人と長電話をするのはひどいと思います。","せっかくじかんをつくってあっているのに、ほかのひととながでんわをするのはひどいとおもいます。"] },
    { k:"f7-07", es:"Quiero seguir siendo su amiga, así que no sé qué hacer de ahora en adelante.", c:2, pat:"どうしたらいいか",
      ok:["友だちとしての関係はつづけていきたいので、今後どうしたらいいかまよっています。","ともだちとしてのかんけいはつづけていきたいので、こんごどうしたらいいかまよっています。"] },
    { k:"f7-08", es:"Cuando estás con alguien no está bien ponerse a hablar por teléfono con otro, ¿verdad?", c:2, pat:"〜てはだめですよね",
      ok:["人と会っているときに、ほかの人と長電話をしてはだめですよね。","ひととあっているときに、ほかのひととながでんわをしてはだめですよね。"] },
    { k:"f7-09", es:"Si es tu amiga, creo que es mejor decirle con claridad incluso lo que cuesta decir.", c:2, pat:"〜た方がいいと思います",
      ok:["友だちなら、言いにくいこともはっきり言ってあげた方がいいと思います。","ともだちなら、いいにくいこともはっきりいってあげたほうがいいとおもいます。"] },
    { k:"f7-10", es:"¿Y si durante un tiempo procuras no ver a S?", c:2, pat:"〜ないようにしてはどうですか",
      ok:["しばらく、S子さんと会わないようにしてはどうですか。","しばらく、Sこさんとあわないようにしてはどうですか。"] },
    { k:"f7-11", es:"Y de vez en cuando, creo que estaría bien escuchar a S por teléfono.", c:2, pat:"〜たらいいんじゃないかと思います",
      ok:["そしてときどき、電話でS子さんの話を聞いてあげたらいいんじゃないかと思います。","そしてときどき、でんわでSこさんのはなしをきいてあげたらいいんじゃないかとおもいます。"] },
    { k:"f7-12", es:"Las preocupaciones, cuando se cuentan, alivian.", c:1, pat:"〜と、すっきりします",
      ok:["なやみは人に話すと、すっきりしますよ。","なやみはひとにはなすと、すっきりしますよ。"] },
    { k:"f7-13", es:"No pareces tú, Carla.", c:1, pat:"〜らしくないですよ",
      ok:["カーラさんらしくないですよ。"] },
    { k:"f7-14", es:"Carla, ¿qué te pasa? Te veo con menos ánimo que de costumbre.", c:1, pat:"いつもより元気がないですね",
      ok:["カーラさん、どうしたんですか。いつもより元気がないですね。","カーラさん、どうしたんですか。いつもよりげんきがないですね。"] },
    { k:"f7-15", es:"Si te sirvo, te escucho.", c:1, pat:"私でよかったら、相談にのりますよ",
      ok:["私でよかったら、相談にのりますよ。","わたしでよかったら、そうだんにのりますよ。"] },
    { k:"f7-16", es:"Dirigirle la palabra. Escucharle. Dejarse consultar. Estar a su lado.", c:1, pat:"こえをかける・話を聞く・相談にのる・そばにいる",
      ok:["こえをかける。話を聞く。相談にのる。そばにいる。","こえをかける。はなしをきく。そうだんにのる。そばにいる。"] },
    { k:"f7-17", es:"Le presté 300.000 yenes a mi hermano y no me los devuelve. (dinero) Últimamente mi pareja no quiere verme. (amor)", c:1, pat:"なやみの種類",
      ok:["兄に30万円貸しましたが、返してくれません。（お金）最近、恋人が私に会ってくれません。（恋愛）","あにに30まんえんかしましたが、かえしてくれません。（おかね）さいきん、こいびとがわたしにあってくれません。（れんあい）"] },
    { k:"f7-18", es:"No es nada. Es que estoy un poco cansada.", c:1, pat:"だいじょうぶです。ちょっと〜て。",
      ok:["だいじょうぶです。ちょっとつかれてて。","だいじょうぶです。ちょっと疲れてて。"] }
  ],

  huecos: [
    /* p87, ejercicio 3 */
    { k:"h7-01", pat:"こえをかける・話を聞く・相談にのる・そばにいる", pre:"こえを（", post:"）", hint:"el verbo fijo de こえ", ok:["かける"], c:1, es:"Dirigirle la palabra." },
    { k:"h7-02", pat:"こえをかける・話を聞く・相談にのる・そばにいる", pre:"話を（", post:"）", hint:"escuchar", ok:["聞く","きく"], c:1, es:"Escucharle." },
    { k:"h7-03", pat:"こえをかける・話を聞く・相談にのる・そばにいる", pre:"相談に（", post:"）", hint:"el verbo fijo de 相談", ok:["のる"], c:1, es:"Dejarse consultar." },
    { k:"h7-04", pat:"こえをかける・話を聞く・相談にのる・そばにいる", pre:"そばに（", post:"）", hint:"estar (una persona)", ok:["いる"], c:1, es:"Estar a su lado." },
    /* p87, ejercicio 4 */
    { k:"h7-05", pat:"なやみの種類", pre:"最近、恋人が私に会ってくれません。（", post:"）", hint:"de qué va: 恋愛 / 仕事 / お金…", ok:["恋愛","れんあい"], c:1, es:"Últimamente mi pareja no quiere verme." },
    { k:"h7-06", pat:"なやみの種類", pre:"学校でなまいきだと言われます。（", post:"）", hint:"de qué va", ok:["人間関係","にんげんかんけい"], c:1, es:"En la escuela me dicen que soy un creído." },
    { k:"h7-07", pat:"なやみの種類", pre:"働きたいんですが、いい会社が見つかりません。（", post:"）", hint:"de qué va", ok:["仕事","しごと"], c:1, es:"Quiero trabajar, pero no encuentro una buena empresa." },
    { k:"h7-08", pat:"なやみの種類", pre:"夫・妻の親と考え方がちがいます。（", post:"）", hint:"de qué va", ok:["結婚・家庭","結婚","家庭","けっこん","かてい"], c:1, es:"Pienso distinto que los padres de mi marido / mi mujer." },
    /* p88, 文2 */
    { k:"h7-09", pat:"〜て（い）て", pre:"ちょっと（", post:"）。", hint:"寝て（い）ない → 〜なくて", ok:["寝てなくて","ねてなくて","寝ていなくて","ねていなくて"], c:1, es:"Es que no estoy durmiendo mucho." },
    { k:"h7-10", pat:"〜て（い）て", pre:"ちょっと朝ご飯、（", post:"）。", hint:"食べて（い）ない → 〜なくて", ok:["食べてなくて","たべてなくて","食べていなくて","たべていなくて"], c:1, es:"Es que no estoy desayunando." },
    { k:"h7-11", pat:"Nのことで", pre:"ちょっと（", post:"）。", hint:"うち → 〜のことで", ok:["うちのことで"], c:1, es:"Es por lo de casa." },
    { k:"h7-12", pat:"Nのことで", pre:"（", post:"）ちょっと…。", hint:"子ども → 〜のことで", ok:["子どものことで","こどものことで"], c:1, es:"Por lo de los niños, un poco…" },
    /* p90, 文2 */
    { k:"h7-13", pat:"〜かもしれません", pre:"職場では人間関係のなやみが一番（", post:"）。", hint:"多いです → 〜かもしれません", ok:["多いかもしれません","おおいかもしれません"], c:1, es:"En el trabajo puede que la preocupación más común sean las relaciones." },
    { k:"h7-14", pat:"〜かもしれません", pre:"人間関係に問題があると、心の病気に（", post:"）。", hint:"なります → 〜かもしれません", ok:["なるかもしれません"], c:1, es:"Si hay problemas de relación, puede que uno enferme del ánimo." },
    { k:"h7-15", pat:"〜かもしれません", pre:"今の社会で、ストレスがない人は（", post:"）。", hint:"いません → 〜かもしれません", ok:["いないかもしれません"], c:1, es:"En la sociedad de hoy puede que no haya nadie sin estrés." },
    /* p93, 文2 (1) */
    { k:"h7-16", pat:"〜のに", pre:"メールで（", post:"）のに、サビタさんはまだおこっています。", hint:"あやまりました → forma た", ok:["あやまった"], c:2, es:"Aunque le pedí perdón por correo, Sabita sigue enfadada." },
    { k:"h7-17", pat:"〜のに", pre:"今日、会社でこえを（", post:"）のに、サビタさんはへんじをしてくれませんでした。", hint:"かけました → forma た", ok:["かけた"], c:2, es:"Aunque hoy le hablé en la oficina, Sabita no me contestó." },
    { k:"h7-18", pat:"〜のに", pre:"せっかくコーヒーを（", post:"）のに、いらないと言われました。", hint:"いれてあげました → forma た", ok:["いれてあげた"], c:2, es:"Con lo que le preparé un café, me dijo que no lo quería." },
    { k:"h7-19", pat:"〜のに", pre:"いつもいっしょに昼食を（", post:"）のに、今日はひとりです。", hint:"食べます → forma diccionario", ok:["食べる","たべる"], c:2, es:"Siempre comemos juntas, y hoy estoy sola." },
    /* p93, 文2 (2) */
    { k:"h7-20", pat:"〜のに", pre:"（", post:"）のに、すすめられます。", hint:"お酒は好きじゃないです → forma simple", ok:["お酒は好きじゃない","おさけはすきじゃない"], c:2, es:"Aunque no me gusta beber, me lo ofrecen." },
    { k:"h7-21", pat:"〜のに", pre:"（", post:"）のに、つぎの店にさそわれます。", hint:"早く帰りたいです → forma simple", ok:["早く帰りたい","はやくかえりたい"], c:2, es:"Aunque quiero volver pronto, me arrastran al siguiente bar." },
    { k:"h7-22", pat:"〜のに", pre:"（", post:"）のに、わりかんでお金をはらいます。", hint:"あまり飲んだり食べたりしません → forma simple", ok:["あまり飲んだり食べたりしない","あまりのんだりたべたりしない"], c:2, es:"Aunque casi no bebo ni como, pago a escote." },
    { k:"h7-23", pat:"〜のに", pre:"（", post:"）のに、なまいきだと言われました。", hint:"新人です → sustantivo + なのに", ok:["新人な","しんじんな"], c:2, es:"Aunque soy nuevo, me han dicho que soy un creído." },
    /* p94, 文3 */
    { k:"h7-24", pat:"〜てほしいです／〜ないでほしいです", pre:"もっと早く（", post:"）です。", hint:"帰ってきます → 〜てほしい", ok:["帰ってきてほしい","かえってきてほしい"], c:2, es:"Quiero que vuelva más pronto." },
    { k:"h7-25", pat:"〜てほしいです／〜ないでほしいです", pre:"子どもの問題について、いっしょに（", post:"）です。", hint:"考えます → 〜てほしい", ok:["考えてほしい","かんがえてほしい"], c:2, es:"Quiero que piense conmigo los problemas de los niños." },
    { k:"h7-26", pat:"〜てほしいです／〜ないでほしいです", pre:"休みの日にはいっしょに（", post:"）です。", hint:"あそびます → 〜てほしい", ok:["あそんでほしい"], c:2, es:"Quiero que los días libres juegue conmigo." },
    { k:"h7-27", pat:"〜てほしいです／〜ないでほしいです", pre:"お母さんと（", post:"）と思っています。", hint:"けんかしません → 〜ないでほしい", ok:["けんかしないでほしい"], c:2, es:"Quiere que no discuta con mamá." },
    { k:"h7-28", pat:"〜てほしいです／〜ないでほしいです", pre:"いっしょうけんめい働いているので、あまりむりを（", post:"）と思っています。", hint:"言いません → 〜ないでほしい", ok:["言わないでほしい","いわないでほしい"], c:2, es:"Como trabaja con todas sus fuerzas, quiere que no le pidan imposibles." },
    /* dialogos y textos */
    { k:"h7-29", pat:"いつもより元気がないですね", pre:"カーラさん、どうしたんですか。いつもより（", post:"）ね。", hint:"no tiene ánimo", ok:["元気がないです","げんきがないです"], c:1, es:"Carla, ¿qué te pasa? Te veo con menos ánimo que de costumbre." },
    { k:"h7-30", pat:"だいじょうぶです。ちょっと〜て。", pre:"だいじょうぶです。ちょっと（", post:"）。", hint:"つかれています → 〜てて", ok:["つかれてて","疲れてて","つかれていて"], c:1, es:"No es nada. Es que estoy un poco cansada." },
    { k:"h7-31", pat:"私でよかったら、相談にのりますよ", pre:"私でよかったら、（", post:"）よ。", hint:"相談 + su verbo fijo, forma ます", ok:["相談にのります","そうだんにのります"], c:1, es:"Si te sirvo, te escucho." },
    { k:"h7-32", pat:"〜と、すっきりします", pre:"なやみは人に（", post:"）と、すっきりしますよ。", hint:"話します → forma diccionario", ok:["話す","はなす"], c:1, es:"Las preocupaciones, cuando se cuentan, alivian." },
    { k:"h7-33", pat:"〜た方がいいと思います", pre:"友だちなら、言いにくいこともはっきり（", post:"）方がいいと思います。", hint:"言ってあげます → forma た", ok:["言ってあげた","いってあげた"], c:2, es:"Si es tu amiga, mejor decirle con claridad incluso lo que cuesta decir." },
    { k:"h7-34", pat:"〜ないようにしてはどうですか", pre:"しばらく、S子さんと（", post:"）ようにしてはどうですか。", hint:"会いません → forma ない", ok:["会わない","あわない"], c:2, es:"¿Y si durante un tiempo procuras no ver a S?" }
  ],

  armar: [
    { k:"a7-01", es:"Carla, ¿qué te pasa? Te veo con menos ánimo que de costumbre.", c:1, chips:["カーラさん、","どうしたんですか。","いつもより","元気がないですね"] },
    { k:"a7-02", es:"No es nada. Es que estoy un poco cansada.", c:1, chips:["だいじょうぶです。","ちょっと","つかれ","てて"] },
    { k:"a7-03", es:"Si te sirvo, te escucho.", c:1, chips:["私で","よかったら、","相談に","のりますよ"] },
    { k:"a7-04", es:"Perdona. La verdad es que es por lo del trabajo…", c:1, chips:["すみません。","じつは、","仕事のことで","ちょっと…"] },
    { k:"a7-05", es:"En mi trabajo puede que pase lo mismo.", c:1, chips:["私の","職場でも、","同じ","かもしれません"] },
    { k:"a7-06", es:"Si hay problemas de relación, puede que uno enferme del ánimo.", c:1, chips:["人間関係に","問題があると、","心の病気に","なるかもしれませんね"] },
    { k:"a7-07", es:"Las preocupaciones, cuando se cuentan, alivian.", c:1, chips:["なやみは","人に話すと、","すっきり","しますよ"] },
    { k:"a7-08", es:"Le presté 300.000 yenes a mi hermano y no me los devuelve.", c:1, chips:["兄に","30万円","貸しましたが、","返してくれません"] },
    { k:"a7-09", es:"Con lo que cuesta quedar, mi amiga se pone a hablar por teléfono con el novio.", c:2, chips:["せっかく","会っているのに、","友だちは","カレシと長電話をします"] },
    { k:"a7-10", es:"Quiero que S respete las normas.", c:2, chips:["私は","S子に","マナーを","まもってほしいです"] },
    { k:"a7-11", es:"Quiero que no hable tanto por teléfono.", c:2, chips:["長電話を","しないで","ほしい","です"] },
    { k:"a7-12", es:"Aunque le pedí perdón por correo, Sabita sigue enfadada.", c:2, chips:["メールで","あやまったのに、","サビタさんは","まだおこっています"] },
    { k:"a7-13", es:"Aunque no me gusta beber, me lo ofrecen.", c:2, chips:["お酒は","好きじゃない","のに、","すすめられます"] },
    { k:"a7-14", es:"Si es tu amiga, creo que es mejor decirle con claridad incluso lo que cuesta decir.", c:2, chips:["友だちなら、","言いにくいことも","はっきり言ってあげた","方がいいと思います"] },
    { k:"a7-15", es:"¿Y si durante un tiempo procuras no ver a S?", c:2, chips:["しばらく、","S子さんと","会わないように","してはどうですか"] },
    { k:"a7-16", es:"Quiero seguir siendo su amiga, así que no sé qué hacer de ahora en adelante.", c:2, chips:["友だちとしての関係は","つづけていきたいので、","今後どうしたらいいか","まよっています"] }
  ]
});
