/* Dojo Marugoto - unidad 8, 旅行中のトラブル
   Marugoto A2/B1 Parte 2 - clase 1 = libro p96-100 - clase 2 = p101-105
   Copia literal del archivo congelado del 2026-08-21. El orden de
   frases, huecos y armar es el del archivo congelado y no se toca:
   la tabla de migracion de M1 depende de ese orden (plano 5.3). */

CONTENIDO.unidades.push({
  n: 8,
  titulo: "旅行中のトラブル",
  es: "Contratiempos en el viaje",
  paginas: { 1: "96-100", 2: "101-105" },
  estado: "lista",

  /* --- VERBOS ---------------------------------------------------
     kana  : forma diccionario en kana (base de la conjugación)
     kanji : forma diccionario con kanji (si no tiene, repite kana)
     g     : grupo 1 / 2 / 3
     es    : significado
     c     : clase (1 o 2)
     par   : pareja transitivo/intransitivo, si la tiene
     nota  : advertencia (trampas de grupo)
  --------------------------------------------------------------- */
  verbos: [
    { kana:"のる", kanji:"乗る", g:1, es:"subir a (un transporte)", c:1 },
    { kana:"とぶ", kanji:"とぶ", g:1, es:"volar", c:1 },
    { kana:"はじまる", kanji:"始まる", g:1, es:"empezar (algo empieza)", c:1 },
    { kana:"かわる", kanji:"変わる", g:1, es:"cambiar (algo cambia)", c:1 },
    { kana:"おくれる", kanji:"おくれる", g:2, es:"atrasarse", c:1, nota:"Grupo 2, aunque termine en 〜る" },
    { kana:"わすれる", kanji:"忘れる", g:2, es:"olvidar", c:1 },
    { kana:"はいる", kanji:"入る", g:1, es:"entrar", c:1, nota:"Grupo 1, aunque termine en 〜いる" },
    { kana:"あらう", kanji:"洗う", g:1, es:"lavar", c:1 },
    { kana:"はらう", kanji:"はらう", g:1, es:"pagar", c:1 },
    { kana:"おく", kanji:"おく", g:1, es:"dejar, colocar", c:1 },
    { kana:"おもいだす", kanji:"思い出す", g:1, es:"recordar, hacer memoria", c:1 },
    { kana:"うけとる", kanji:"受けとる", g:1, es:"recibir, retirar", c:1 },
    { kana:"まちがえる", kanji:"まちがえる", g:2, es:"confundirse de", c:1 },
    { kana:"しらせる", kanji:"知らせる", g:2, es:"avisar, informar", c:1 },
    { kana:"たずねる", kanji:"たずねる", g:2, es:"preguntar (formal)", c:1 },
    { kana:"ある", kanji:"ある", g:1, es:"haber, estar", c:1, nota:"Negativo irregular: ない" },
    { kana:"いく", kanji:"行く", g:1, es:"ir", c:1, nota:"Excepción: forma て 行って" },
    { kana:"すごす", kanji:"すごす", g:1, es:"pasar (el rato)", c:2 },
    { kana:"たのむ", kanji:"たのむ", g:1, es:"pedir", c:2 },
    { kana:"あるく", kanji:"歩く", g:1, es:"caminar", c:2 },
    { kana:"なく", kanji:"なく", g:1, es:"llorar", c:2 },
    { kana:"すわる", kanji:"座る", g:1, es:"sentarse", c:2 },
    { kana:"ねる", kanji:"寝る", g:2, es:"dormir, acostarse", c:2 },
    { kana:"おりる", kanji:"おりる", g:2, es:"bajarse (de un transporte)", c:2 },
    { kana:"たすける", kanji:"助ける", g:2, es:"ayudar, salvar", c:2 },
    { kana:"にげる", kanji:"にげる", g:2, es:"huir, escapar", c:2 },
    { kana:"みせる", kanji:"見せる", g:2, es:"mostrar", c:2 },
    { kana:"てつだう", kanji:"手伝う", g:1, es:"echar una mano", c:2 },
    { kana:"わかれる", kanji:"わかれる", g:2, es:"separarse, despedirse", c:2 },
    { kana:"こわれる", kanji:"こわれる", g:2, es:"romperse", c:2 },
    { kana:"なおす", kanji:"なおす", g:1, es:"arreglar", c:2 },
    /* pares transitivo / intransitivo (clase 2) */
    { kana:"つく", kanji:"つく", g:1, es:"encenderse", c:2, par:"つける", tipo:"自" },
    { kana:"つける", kanji:"つける", g:2, es:"encender", c:2, par:"つく", tipo:"他" },
    { kana:"きえる", kanji:"きえる", g:2, es:"apagarse", c:2, par:"けす", tipo:"自" },
    { kana:"けす", kanji:"けす", g:1, es:"apagar", c:2, par:"きえる", tipo:"他" },
    { kana:"あく", kanji:"あく", g:1, es:"abrirse", c:2, par:"あける", tipo:"自" },
    { kana:"あける", kanji:"あける", g:2, es:"abrir", c:2, par:"あく", tipo:"他" },
    { kana:"しまる", kanji:"しまる", g:1, es:"cerrarse", c:2, par:"しめる", tipo:"自" },
    { kana:"しめる", kanji:"しめる", g:2, es:"cerrar", c:2, par:"しまる", tipo:"他" },
    { kana:"でる", kanji:"出る", g:2, es:"salir", c:2, par:"だす", tipo:"自" },
    { kana:"だす", kanji:"出す", g:1, es:"sacar, echar", c:2, par:"でる", tipo:"他" },
    { kana:"とまる", kanji:"止まる", g:1, es:"pararse, detenerse", c:2, par:"とめる", tipo:"自" },
    { kana:"とめる", kanji:"止める", g:2, es:"parar, cortar", c:2, par:"とまる", tipo:"他" },
    { kana:"かかる", kanji:"かかる", g:1, es:"quedar cerrado (con llave)", c:2, par:"かける", tipo:"自" },
    { kana:"かける", kanji:"かける", g:2, es:"echar la llave", c:2, par:"かかる", tipo:"他" },
    { kana:"ながれる", kanji:"ながれる", g:2, es:"fluir, correr (el agua)", c:2, par:"ながす", tipo:"自" },
    { kana:"ながす", kanji:"ながす", g:1, es:"hacer correr (el agua)", c:2, par:"ながれる", tipo:"他" },
    /* grupo 3 */
    { kana:"する", kanji:"する", g:3, es:"hacer", c:1 },
    { kana:"くる", kanji:"来る", g:3, es:"venir", c:1 },
    { kana:"チェックインする", kanji:"チェックインする", g:3, es:"facturar", c:1 },
    { kana:"しゅっぱつする", kanji:"出発する", g:3, es:"partir, salir", c:1 },
    { kana:"とうちゃくする", kanji:"到着する", g:3, es:"llegar", c:1 },
    { kana:"こしょうする", kanji:"故障する", g:3, es:"averiarse", c:2 },
    { kana:"せつめいする", kanji:"説明する", g:3, es:"explicar", c:2 },
    { kana:"きこくする", kanji:"帰国する", g:3, es:"volver al país de origen", c:1 },
    { kana:"かいしする", kanji:"開始する", g:3, es:"dar comienzo", c:1 }
  ],

  /* --- VOCABULARIO ---------------------------------------------- */
  vocab: [
    { jp:"空港", kana:"くうこう", es:"aeropuerto", c:1, cat:"viaje" },
    { jp:"飛行機", kana:"ひこうき", es:"avión", c:1, cat:"viaje" },
    { jp:"〜便", kana:"〜びん", es:"vuelo número…", c:1, cat:"viaje" },
    { jp:"〜航空", kana:"〜こうくう", es:"aerolínea", c:1, cat:"viaje" },
    { jp:"〜行き", kana:"〜いき", es:"con destino a", c:1, cat:"viaje" },
    { jp:"フライト", kana:"フライト", es:"vuelo", c:1, cat:"viaje" },
    { jp:"手続き", kana:"てつづき", es:"trámite", c:1, cat:"viaje" },
    { jp:"搭乗", kana:"とうじょう", es:"embarque", c:1, cat:"viaje" },
    { jp:"チェックイン", kana:"チェックイン", es:"facturación", c:1, cat:"viaje" },
    { jp:"出発ゲート", kana:"しゅっぱつゲート", es:"puerta de embarque", c:1, cat:"viaje" },
    { jp:"荷物", kana:"にもつ", es:"equipaje", c:1, cat:"objetos" },
    { jp:"スーツケース", kana:"スーツケース", es:"maleta", c:1, cat:"objetos" },
    { jp:"パスポート", kana:"パスポート", es:"pasaporte", c:1, cat:"objetos" },
    { jp:"忘れ物", kana:"わすれもの", es:"objeto olvidado", c:1, cat:"objetos" },
    { jp:"受付", kana:"うけつけ", es:"recepción", c:1, cat:"viaje" },
    { jp:"到着時間", kana:"とうちゃくじかん", es:"hora de llegada", c:1, cat:"viaje" },
    { jp:"予定", kana:"よてい", es:"plan, previsión", c:1, cat:"abstracto" },
    { jp:"変更", kana:"へんこう", es:"cambio", c:1, cat:"problema" },
    { jp:"故障", kana:"こしょう", es:"avería", c:1, cat:"problema" },
    { jp:"エンジン", kana:"エンジン", es:"motor", c:1, cat:"objetos" },
    { jp:"トラブル", kana:"トラブル", es:"problema", c:1, cat:"problema" },
    { jp:"アナウンス", kana:"アナウンス", es:"anuncio por megafonía", c:1, cat:"viaje" },
    { jp:"お客様", kana:"おきゃくさま", es:"pasajero, cliente (formal)", c:1, cat:"viaje" },
    { jp:"利用", kana:"りよう", es:"uso", c:1, cat:"abstracto" },
    { jp:"見送り", kana:"みおくり", es:"ir a despedir a alguien", c:1, cat:"abstracto" },
    { jp:"かばん", kana:"かばん", es:"bolso", c:1, cat:"objetos" },
    { jp:"ていねいたい", kana:"ていねいたい", es:"estilo formal", c:1, cat:"abstracto" },
    { jp:"ふつうたい", kana:"ふつうたい", es:"estilo informal", c:1, cat:"abstracto" },
    { jp:"もうすぐ", kana:"もうすぐ", es:"dentro de poco", c:1, cat:"tiempo" },
    { jp:"〜ほど", kana:"〜ほど", es:"aproximadamente (formal)", c:1, cat:"tiempo" },
    { jp:"とにかく", kana:"とにかく", es:"en fin, de todas formas", c:1, cat:"conector" },
    { jp:"それから", kana:"それから", es:"después de eso", c:1, cat:"conector" },
    { jp:"どこか", kana:"どこか", es:"algún lugar", c:1, cat:"conector" },
    { jp:"しまった", kana:"しまった", es:"¡rayos!", c:1, cat:"reaccion" },
    { jp:"どうしよう", kana:"どうしよう", es:"¿qué hago?", c:1, cat:"reaccion" },
    { jp:"たぶん", kana:"たぶん", es:"seguramente", c:1, cat:"reaccion" },
    { jp:"電気", kana:"でんき", es:"luz eléctrica", c:2, cat:"hotel" },
    { jp:"エアコン", kana:"エアコン", es:"aire acondicionado", c:2, cat:"hotel" },
    { jp:"まど", kana:"まど", es:"ventana", c:2, cat:"hotel" },
    { jp:"ドア", kana:"ドア", es:"puerta", c:2, cat:"hotel" },
    { jp:"かぎ", kana:"かぎ", es:"llave", c:2, cat:"hotel" },
    { jp:"お湯", kana:"おゆ", es:"agua caliente", c:2, cat:"hotel" },
    { jp:"水", kana:"みず", es:"agua", c:2, cat:"hotel" },
    { jp:"部屋", kana:"へや", es:"habitación", c:2, cat:"hotel" },
    { jp:"〜号室", kana:"〜ごうしつ", es:"habitación número", c:2, cat:"hotel" },
    { jp:"エレベーター", kana:"エレベーター", es:"ascensor", c:2, cat:"hotel" },
    { jp:"歴史", kana:"れきし", es:"historia", c:2, cat:"abstracto" },
    { jp:"説明", kana:"せつめい", es:"explicación", c:2, cat:"abstracto" },
    { jp:"火事", kana:"かじ", es:"incendio", c:2, cat:"problema" },
    { jp:"どろぼう", kana:"どろぼう", es:"ladrón", c:2, cat:"problema" },
    { jp:"マッサージ", kana:"マッサージ", es:"masaje", c:2, cat:"objetos" },
    { jp:"ガイドブック", kana:"ガイドブック", es:"guía de viaje", c:2, cat:"objetos" },
    { jp:"計画", kana:"けいかく", es:"plan, planificación", c:2, cat:"abstracto" },
    { jp:"映画", kana:"えいが", es:"película", c:2, cat:"objetos" },
    { jp:"外国語", kana:"がいこくご", es:"lengua extranjera", c:2, cat:"abstracto" },
    { jp:"思い出", kana:"おもいで", es:"recuerdo", c:2, cat:"abstracto" },
    { jp:"親切", kana:"しんせつ", es:"amabilidad, amable", c:2, cat:"abstracto" },
    { jp:"仕事", kana:"しごと", es:"trabajo", c:2, cat:"abstracto" },
    { jp:"やっと", kana:"やっと", es:"por fin", c:2, cat:"tiempo" },
    { jp:"それに", kana:"それに", es:"además", c:2, cat:"conector" },
    { jp:"ずっと", kana:"ずっと", es:"todo el rato", c:2, cat:"tiempo" },
    { jp:"なぜか", kana:"なぜか", es:"por algún motivo", c:2, cat:"conector" },
    { jp:"ひどい目にあう", kana:"ひどいめにあう", es:"pasarlo fatal", c:2, cat:"reaccion" },
    { jp:"へたな", kana:"へたな", es:"malo (en algo)", c:2, cat:"reaccion" }
  ],

  /* --- FRASES: español → japonés --------------------------------
     ok : lista de respuestas aceptadas (la primera es la modelo)
  --------------------------------------------------------------- */
  frases: [
    { es:"Dicen que los trámites empiezan en unos 20 minutos.", c:1, pat:"〜そうです",
      ok:["あと20分ほどで、手続きが始まるそうです。","あと20分ほどで手続きが始まるそうです。","手続きが始まるそうです。"] },
    { es:"Al parecer la salida se atrasa una hora.", c:1, pat:"〜そうです",
      ok:["出発が1時間おくれるそうです。","しゅっぱつが1じかんおくれるそうです。"] },
    { es:"Dicen que cambió la puerta de embarque.", c:1, pat:"〜そうです",
      ok:["出発ゲートが変わったそうです。","しゅっぱつゲートがかわったそうです。"] },
    { es:"Dicen que hoy el avión no vuela.", c:1, pat:"〜そうです",
      ok:["今日は飛行機がとばないそうです。","きょうはひこうきがとばないそうです。","飛行機がとばないそうです。"] },
    { es:"Dicen que es la puerta 25. (ojo con el だ)", c:1, pat:"N + だそうです",
      ok:["25番だそうです。","にじゅうごばんだそうです。"] },
    { es:"Dicen que ese hotel es cómodo. (ojo con el だ)", c:1, pat:"adj-な + だそうです",
      ok:["あのホテルはべんりだそうです。","ホテルはべんりだそうです。"] },
    { es:"¿Qué acaban de decir en el aviso?", c:1, pat:"何て言ってましたか",
      ok:["今のアナウンス、何て言ってましたか。","いまのアナウンス、なんていってましたか。","今のアナウンス、何て言っていましたか。"] },
    { es:"Disculpe. Esto… ¿va usted en el mismo vuelo?", c:1, pat:"abordaje",
      ok:["すみません。あのう、同じフライトですか。","すみません、あのう、同じフライトですか。","すみません。あのう、おなじフライトですか。"] },
    { es:"Después del check-in me tomé un té en la cafetería.", c:1, pat:"〜た後で",
      ok:["チェックインした後で、カフェでお茶を飲んだ。","チェックインしたあとで、カフェでおちゃをのんだ。"] },
    { es:"Una vez que llegue al aeropuerto, revisaré el correo.", c:1, pat:"〜た後で",
      ok:["空港についた後で、メールをチェックします。","くうこうについたあとで、メールをチェックします。"] },
    { es:"En fin, vamos a ver.", c:1, pat:"とにかく〜てみましょう",
      ok:["とにかく行ってみましょう。","とにかくいってみましょう。"] },
    { es:"¿Has tenido alguna vez un problema en el aeropuerto?", c:1, pat:"〜たことがあります",
      ok:["空港でトラブルにあったことがありますか。","くうこうでトラブルにあったことがありますか。"] },
    { es:"¡Socorro!", c:2, pat:"pedir ayuda", ok:["助けて！","たすけて！","助けて","たすけて"] },
    { es:"¡Por favor, que alguien!", c:2, pat:"pedir ayuda", ok:["すみません、だれか！","すみません、だれか"] },
    { es:"¡Fuego! ¡Huyan! (en estilo llano)", c:2, pat:"命令形", ok:["火事だ、にげろ！","かじだ、にげろ！","火事だ、にげろ"] },
    { es:"Disculpe, ¡me bajo!", c:2, pat:"pedir paso", ok:["すみません、おります！","すみません、おります"] },
    { es:"El personal del hotel enciende la luz.", c:2, pat:"他動詞",
      ok:["ホテルの人が電気をつけます。","ホテルのひとがでんきをつけます。"] },
    { es:"La luz no se enciende.", c:2, pat:"自動詞", ok:["電気がつきません。","でんきがつきません。"] },
    { es:"La ventana no cierra.", c:2, pat:"自動詞", ok:["まどがしまりません。"] },
    { es:"No sale agua caliente.", c:2, pat:"自動詞", ok:["お湯が出ません。","おゆがでません。"] },
    { es:"El personal del hotel cortó el agua del baño.", c:2, pat:"他動詞",
      ok:["ホテルの人はトイレの水を止めました。","ホテルの人がトイレの水を止めました。","ホテルのひとはトイレのみずをとめました。"] },
    { es:"Reviso el correo mientras me tomo un café.", c:2, pat:"〜ながら",
      ok:["コーヒーを飲みながら、メールをチェックします。","コーヒーをのみながら、メールをチェックします。"] },
    { es:"Espero leyendo la guía de viaje.", c:2, pat:"〜ながら",
      ok:["ガイドブックを読みながら、待ちます。","ガイドブックをよみながら、まちます。"] },
    { es:"Me contó la historia del hotel mientras caminábamos.", c:2, pat:"〜ながら + 〜てくれる",
      ok:["歩きながら、ホテルの歴史を説明してくれました。","あるきながら、ホテルのれきしをせつめいしてくれました。"] },
    { es:"Conseguí que me cambiaran de habitación.", c:2, pat:"〜てもらう",
      ok:["部屋をかえてもらいました。","へやをかえてもらいました。","部屋をかえてもらった。"] },
    { es:"Quiero ser amable con los extranjeros.", c:2, pat:"〜てあげる",
      ok:["外国の人に親切にしてあげたいです。","がいこくのひとにしんせつにしてあげたいです。"] },
    { es:"Estudio idiomas, duermo, cosas así.", c:2, pat:"〜たり〜たり",
      ok:["外国語の勉強をしたり、寝たりしています。","がいこくごのべんきょうをしたり、ねたりしています。"] },
    { es:"Lo pasé fatal.", c:2, pat:"ひどい目にあう", ok:["ひどい目にあいました。","ひどいめにあいました。"] }
  ],

  /* --- FRASES CON HUECO ----------------------------------------- */
  huecos: [
    { pre:"あと20分ほどで、手続きが（", post:"）。", hint:"始まります → 〜そうです", ok:["始まるそうです","はじまるそうです"], c:1, es:"Dicen que los trámites empiezan en unos 20 minutos." },
    { pre:"飛行機の出発が1時間（", post:"）。", hint:"おくれます → 〜そうです", ok:["おくれるそうです"], c:1, es:"Dicen que la salida se atrasa una hora." },
    { pre:"出発ゲートが（", post:"）。", hint:"変わりました → 〜そうです", ok:["変わったそうです","かわったそうです"], c:1, es:"Dicen que cambió la puerta." },
    { pre:"今日は天気が悪くて、飛行機が（", post:"）。", hint:"とびません → 〜そうです", ok:["とばないそうです"], c:1, es:"Dicen que hoy no vuela." },
    { pre:"チェックイン（", post:"）、カフェでお茶を飲んだ。", hint:"します → 〜た後で", ok:["した後で","したあとで"], c:1, es:"Después del check-in…" },
    { pre:"空港に（", post:"）、メールをチェックします。", hint:"つきます → 〜た後で", ok:["ついた後で","ついたあとで"], c:1, es:"Una vez llegado al aeropuerto…" },
    { pre:"とにかく（", post:"）。", hint:"行きます → 〜てみましょう", ok:["行ってみましょう","いってみましょう"], c:1, es:"En fin, vamos a ver." },
    { pre:"かばんが1つない。どこかに（", post:"）かな。", hint:"忘れます → forma た", ok:["忘れた","わすれた"], c:1, es:"¿La habré olvidado en alguna parte?" },
    { pre:"ホテルの人が電気を（", post:"）。", hint:"transitivo, forma ます", ok:["つけます"], c:2, es:"El personal enciende la luz." },
    { pre:"電気が（", post:"）。", hint:"intransitivo, forma ません", ok:["つきません"], c:2, es:"La luz no se enciende." },
    { pre:"まどが（", post:"）。", hint:"intransitivo, forma ません", ok:["しまりません"], c:2, es:"La ventana no cierra." },
    { pre:"田中さんがまどを（", post:"）。", hint:"transitivo, forma ました", ok:["あけました"], c:2, es:"Tanaka abrió la ventana." },
    { pre:"シャワーのお湯が（", post:"）。", hint:"intransitivo, forma ません", ok:["出ません","でません"], c:2, es:"No sale agua caliente de la ducha." },
    { pre:"ホテルの人がトイレの水を（", post:"）。", hint:"transitivo, forma ました", ok:["止めました","とめました"], c:2, es:"El personal cortó el agua del baño." },
    { pre:"セーフティボックスのかぎが（", post:"）。", hint:"intransitivo, forma ません", ok:["かかりません"], c:2, es:"La caja fuerte no cierra con llave." },
    { pre:"へやに入ったら、まどが（", post:"）ままでした。", hint:"intransitivo, forma た", ok:["あいた"], c:2, es:"La ventana estaba abierta." },
    { pre:"コーヒーを（", post:"）、メールをチェックしました。", hint:"飲みます → 〜ながら", ok:["飲みながら","のみながら"], c:2, es:"Revisé el correo mientras tomaba café." },
    { pre:"マッサージを（", post:"）、ねむってしまいました。", hint:"してもらいます → 〜ながら", ok:["してもらいながら"], c:2, es:"Me quedé dormido mientras me hacían el masaje." },
    { pre:"子どもたちは、おかしを（", post:"）、ゲームをしていました。", hint:"食べます → 〜ながら", ok:["食べながら","たべながら"], c:2, es:"Los niños jugaban mientras comían dulces." },
    { pre:"アリさんは、サインを（", post:"）、出発ゲートをさがしました。", hint:"見ます → 〜ながら", ok:["見ながら","みながら"], c:2, es:"Ali buscó la puerta mirando los letreros." },
    { pre:"私のむすめは、空港で（", post:"）、友だちとわかれました。", hint:"なきます → 〜ながら", ok:["なきながら"], c:2, es:"Mi hija se despidió llorando." },
    { pre:"ガイドブックを（", post:"）、旅行の計画をたてます。", hint:"読みます → 〜ながら", ok:["読みながら","よみながら"], c:2, es:"Planifico el viaje leyendo la guía." },
    { pre:"となりに座った人と（", post:"）、すごします。", hint:"話します → 〜ながら", ok:["話しながら","はなしながら"], c:2, es:"Paso el rato conversando con el de al lado." },
    { pre:"外国語の勉強を（", post:"）、（", post2:"）しています。", hint:"します / 寝ます → 〜たり〜たり", ok:["したり"], ok2:["寝たり","ねたり"], c:2, es:"Estudio idiomas, duermo, cosas así." },
    { pre:"へたな英語で人に（", post:"）、親切な人に助けて（", post2:"）しました。", hint:"たのみます / もらいます → 〜たり〜たり", ok:["たのんだり"], ok2:["もらったり"], c:2, es:"Pedí ayuda en mal inglés, dejé que me ayudaran…" }
  ],

  /* --- ARMAR LA FRASE (piezas desordenadas) ---------------------- */
  armar: [
    { es:"Dicen que la salida se atrasa una hora.", c:1, chips:["出発が","1時間","おくれる","そうです"] },
    { es:"Dicen que los trámites empiezan en unos 20 minutos.", c:1, chips:["あと20分ほどで","手続きが","始まる","そうです"] },
    { es:"¿Qué acaban de decir en el aviso?", c:1, chips:["今の","アナウンス、","何て","言ってましたか"] },
    { es:"Dicen que el vuelo 115 quedó cancelado.", c:1, chips:["115便は","キャンセルに","なった","そうです"] },
    { es:"Después del check-in me tomé un té en la cafetería.", c:1, chips:["チェックインした後で、","カフェで","お茶を","飲んだ"] },
    { es:"Puede que esté en el baño. En fin, vamos a ver.", c:1, chips:["トイレに","あるかもしれません。","とにかく","行ってみましょう"] },
    { es:"Al parecer ya casi podemos subir al avión.", c:1, chips:["もうすぐ","飛行機に","乗れる","そうです"] },
    { es:"El personal del hotel enciende la luz de la habitación.", c:2, chips:["ホテルの人が","へやの","電気を","つけます"] },
    { es:"Como en la habitación de al lado hacían ruido, me cambiaron de pieza.", c:2, chips:["となりのへやが","うるさかったから、","へやを","かえてもらいました"] },
    { es:"Revisé el correo mientras tomaba café en la cafetería.", c:2, chips:["カフェで","コーヒーを","飲みながら、","メールをチェックしました"] },
    { es:"Contó la historia del hotel mientras caminaba.", c:2, chips:["歩きながら、","ホテルの","歴史を","説明しました"] },
    { es:"Paso el rato conversando con la persona sentada al lado.", c:2, chips:["となりに","座った人と","話しながら、","すごします"] },
    { es:"Pedí ayuda en mal inglés y me cambiaron de habitación.", c:2, chips:["がんばって","英語で話して、","部屋を","かえてもらった"] },
    { es:"Yo también quiero ser amable con los extranjeros en Japón.", c:2, chips:["ぼくも","日本では","外国の人に","親切にしてあげたい"] },
    { es:"Al entrar a la habitación, la luz no se encendía.", c:2, chips:["部屋に","入ったら、","電気が","つかなかった"] }
  ]
});
